### ISSUE TITLE
Failed to obtain the symbols information from a modified pdb for a modified assembly

### ISSUE THREAD

**Issue by qxshower** [jbevain/cecil#107]
Hi,

I followed this link (https://github.com/jbevain/cecil/wiki/Debug-symbols) to modifying the pdb file to match with the modified assembly. It worked great -- I was able to create a matched pair of assembly and pdb file (checked by a tool called "chkmatch").

However, I have some "follow-up" problems:

First, I did nothing in the "make required changes" section (as shown in the following code snippet) --- in other words, I just read the assembly and write it back without making any change to it.  But the new pdb file is smaller than the original one (although the size of modified assembly does not change). What is missing inside?

var readerParameters = new ReaderParameters { ReadSymbols = true };
var assemblyDefinition = AssemblyDefinition.ReadAssembly (fileName, readerParameters);

// make required changes.

var writerParameters = new WriterParameters { WriteSymbols = true };
assemblyDefinition.Write (outputFile, writerParameters);

Second, I tried to collect coverage information by running a test suite on the new assembly along with the new pdb, in a VS2010 test project using MSTest, but I failed to add the new assembly when I setting up the test configuration. The error message is "Cannot obtain the symbols information for the binary ... Please ensure that both the binary and the symbols files are accessible."... -- I doubt this was caused by the first issue.

Could anyone help on this?

Thanks in advance!

**Comment by jbevain** [comment]
Closing this. Please re-open if you still have issues with 0.10.
