### ISSUE TITLE
Feature request: Customizable Scope Importing

### ISSUE THREAD

**Issue by sucaba** [jbevain/cecil#120]
## Feature:

   Customizable scope importing for SR.Type and SR.MethodBase (see MetdataImporter::ImportScope method).
## Scenario:

Augment source assembly  with a new code cooperating with types and methods from the source assembly (ex: kind of AOP). Resulting assembly should not reference source assembly but instead use identical types and methods from itself.
## Problem: 

There is no way to affect MetadataImporter.ImportScope(SR.Assembly) behavior. It will add source assembly reference to the resulting assembly anyway. 
   Importing TypeReference and MethodReference with modified scope could work but creating them from SR.Type and  SR.MethodBase is rather non trivial task (in general) and it would duplicate significant part of MetadataImporter code. 
   Also after following this approach I discovered that generated assembly has some strange runtime failures even though it's decompiled CIL code is 100% same as in correct version (correct is the one built with a native Cecil import). Runtime exceptions where: not found method and type loader exceptions.  My assumption is that wrong code generation by my importer is related to some dark corners of Cecil like internal field TypeReference.etype and code around it (just guess!). Note that I was forced to simplify my importer to avoid using internal etype field.
## Proposal:

Introduce public IScopeResolver concept

``` c#
   interface IScopeResolver
   {
          IMetadataScope Resolve(ModuleDefinition module, AssemblyNameReference assemblyRef);
   }
```

 which can be used during import as following:

``` c#
ModuleDefinition myModule = ...;
myModule.ScopeResolver = new MyScopeResolver()
myModule.Import(typeof(MyType)); // referenced assembly may be changed
```

Custom scope resolver can return either 
- Module itself. In this case assembly reference is not added
- Original AssemlbyNameReference (current behavior)
- Modified AssemblyNameReference (with version or other attribute changed)

**Comment by jbevain** [comment]
See also https://github.com/jbevain/cecil/pull/184
