### ISSUE TITLE
Would be nice to have a portable library

### ISSUE THREAD

**Issue by lostmsu** [jbevain/cecil#146]
Otherwise any client of Cecil has to stick to compile-time directives to implement portability

**Comment by rprouse** [comment]
@jbevian, we are considering using Cecil in NUnit 3 to help with exploring and executing tests. We were hoping for a PCL version to help target Xamarin and other platforms with a single codebase. 

I haven't gone very deeply down this track, but I wanted to let you know of our intentions so we can coordinate if you decide to look at this again. I have forked the repo over to the nunit org and will play with it there. I will report back once I know more.

**Comment by jbevain** [comment]
@rprouse there's the [pcl branch](https://github.com/jbevain/cecil/tree/pcl).

**Comment by rprouse** [comment]
@jbevain, thanks. I pulled it last night and merged latest from master. I will experiment with it in nunit tonight.

**Comment by jbevain** [comment]
Moving this discussion in #220.
