### ISSUE TITLE
PdbReader does not handle custom debug info for dynamic locals

### ISSUE THREAD

**Issue by KevinH-MS** [jbevain/cecil#153]
I have opened a bug for Cci to support this type of custom debug metadata (https://ccimetadata.codeplex.com/workitem/7742).  When the Roslyn version of the Microsoft C# compiler is released, this will be necessary to enable loading pdbs for code that contains dynamic locals.  Once this bug is fixed in CCI, it would be good to port to Cecil.

**Comment by jbevain** [comment]
Closing this as it's a dup of #90.
