### ISSUE TITLE
A few FIXMEs/TODOs from ilasm

### ISSUE THREAD

**Issue by alexrp** [jbevain/cecil#161]
Opening this as a sort of meta-bug for various things that I ran into while working on the managed `ilasm`.

FIXMEs:
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L2331
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L3144

TODOs:
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L498
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L518
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L521
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L2341
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L3820
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L3839
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L3981
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L4187
- https://github.com/alexrp/mono/blob/ilasm-cecil/mcs/ilasm/parser/ILParser.jay#L4310

**Comment by jbevain** [comment]
Closing this as nobody is driving this effort. Thanks!
