### ISSUE TITLE
Rewritten PDB does not match the assembly

### ISSUE THREAD

**Issue by krk** [jbevain/cecil#162]
Some symbols cannot be inspected while debugging async-await methods and throw the following error in the immediate window:

The name 'a' does not exist in the current context

Ref: https://github.com/Fody/Fody/issues/120

**Comment by xen2** [comment]
Any update and/or way to help on this issue?

This is quite critical for us, as it makes debugging most async functions almost impossible.

**Comment by jogibear9988** [comment]
Why do the rewritten PDBs not mach the Code? Are the internals of the PDBs not known, or are there issues in the Code? Can't we use roslyn in any way to generate the PDBs?

**Comment by jbevain** [comment]
Closing as it's a dup of #90 where we're tracking the issue.
