### ISSUE TITLE
DelegateConverter

### ISSUE THREAD

**Issue by XoseLluis** [jbevain/cecil#193]
This comes more out of curiosity than due to a real need. The thing is that I was wondering about the feasibility of converting a delegate to an Expression Tree (just the reverse procedure of Expression.Compile).
Some StackOverflow discussion led me to this old post:

http://evain.net/blog/articles/2009/04/22/converting-delegates-to-expression-trees/

that mentions an experimental DelegateConverter class. 
I've been searching the last sources and can't find such a class anywhere, so I was wondering if this funcionality somehow exists under a different name?

Many Thanks and Best Regards (and sorry if this is not the right place for this question)

**Comment by jbevain** [comment]
Yeah that's not quite the place. Issues are for, well, Cecil issues/bugs.

To answer your question though, yes it's possible, but no, DelegateConverter is not what you're after, it was just a prototype. I suggest you use ILSpy's engine to decompile method bodies.

Happy new year!

**Comment by jogibear9988** [comment]
Is it possible to get your Experimental Code ?
