### ISSUE TITLE
Default assembly resolver can't resolve WinRT metadata

### ISSUE THREAD

**Issue by artcodex** [jbevain/cecil#195]
The default assembly resolver looks in well know locations and gac for assemblies, but when type requires loading of Windows.winmd Assembly resolver doesn't look in Windows kits and also doesn't look for winmd files. This isn't a huge problem during reading as a custom resolver can be supplied, but this problem is hit during writing as well at it doesn't seem like a custom resolver can be supplied there.

I'm looking to fix this as my team needs this functionality, looking at both adding this as default behavior of default assembly resolver (since this is a system binary, and also resolver needs functionality to look for winmd files), but also looking at adding a option for custom resolver during writing binaries. 

@jbevain Like to get your thoughts on this and whether it would be something the project would want to take.

**Comment by jbevain** [comment]
Hi,

Can you detail what the issue is for writing?

**Comment by artcodex** [comment]
The issue is that we are working with a Windows/Windows Phone 8.1 Modern universal application. We have used Mono.Cecil to insert a call into the application so it loads some extra binaries and functionality on startup. It was working fine, but once certain namespaces were included in the application the Mono.Cecil libraries were failing on Writing them out. They were failing because they needed to resolve certain WinRT types that are included in the Windows.winmd. After debugging we found the issue was that the DefaultAssemblyResolver did not know how to lookup winmd file references and also didn't know anything about the general location of these files (since they are system wide references found in the program files / windows kit folders).

My fix so far was to add the windows kit folders as search folder into the default assembly resolver, and rebuild Mono.Cecil with this in mind. This kind of approach works fine, but we could have avoided modifying Mono.Cecil if there was a way to override the default assembly resolver on write, which doesn't appear to be the case. So I figured the system references for Windows.winmd should probably be a baked in part of the default assembly resolver, since most winrt applications would probably need this, but at the same time it would be useful to override this functionality on write in case any custom resolution may be needed.

P.S. We hit a similar issue while reading the applications binaries, but were able to resolve this by overriding the default assembly resolver for reading and adding this to readsettings for assembly resolution.

Let me know if you have any further questions

Thanks
Avi

**Comment by jbevain** [comment]
Hi Avi,

Thanks for the details. There's one thing I don't quite get: why don't you set your own resolver to your assemblies ? You can pass your own resolver when reading with:

```csharp
ModuleDefinition.ReadModule ("foo.exe", new ReaderParameters { AssemblyResolver = myCustomResolver });
```

Then your custom resolver will be used whenever there's a need to resolve a type, when reading and writing an assembly.

**Comment by artcodex** [comment]
Hi,

Sorry I thought I had tried that with no success (thought my custom reader only worked during reading), but seems to fix the issue. Sorry for confusion.

On the flip side however do you think at least it would be useful for the DefaultAssembly resolver to look for winmd files, so simple custom resolvers only need to add the directories they want to search, instead of recreating the search logic?

**Comment by jbevain** [comment]
The DefaultAssemblyResolver resolves .NET framework assemblies with an implementation.

I think it's better to compose specific needs on top of the default resolver.
