### ISSUE TITLE
Update Mono.CompilerServices.SymbolWriter

### ISSUE THREAD

**Issue by DavidKarlas** [jbevain/cecil#196]
Upstream Mono.CompilerServices.SymbolWriter supports [Column, EndLine and EndColumn](https://github.com/mono/mono/blob/97dc571fe2481ec429c1ab537dd7bf6b9316f5aa/mcs/class/Mono.CompilerServices.SymbolWriter/MonoSymbolTable.cs#L186-L187).

**Comment by jbevain** [comment]
That looks sweet, thanks! All the tests are passing?

**Comment by DavidKarlas** [comment]
Yes. Tests are passing.

**Comment by jbevain** [comment]
Fixed. Thanks!
