### ISSUE TITLE
Table EncLog size bug

### ISSUE THREAD

**Issue by Anna-Budkina** [jbevain/cecil#199]
If an assembly contains EncLog table, there is an exception while parsing nested types. The reason is ImageReader.cs contains the wrong size of table EncLog:
<pre><code>
case Table.EncLog:
case Table.EncMap:
</code>
</pre>
Its size should be changed to 8 bytes:
<pre><code>
case Table.EncLog:
                    size = 8;
                    break;
case Table.EncMap:
</code>
</pre>

**Comment by jbevain** [comment]
Good catch, thanks!
