### ISSUE TITLE
InsertBefore puts instructions into the preceeding catch scope

### ISSUE THREAD

**Issue by bawr** [jbevain/cecil#200]
With IL like:
```
.try
{
    ...
}
catch [mscorlib]System.Object
{
    ...
    IL_0efe: leave.s IL_0f00
}

IL_0f00: nop
```

Inserting instructions before `IL_0f00` actually puts them in the catch scope, which is unexpected.

I had to resort to a hack which duplicated the instruction, inserted the copy after the target, then inserted my code before the copy, and finally removed the copy or the original instruction.

Still, is this by design? This is a corner case where I would expect `InsertAfter(IL_0efe, x)` to actually have different result than `InsertBefore(IL_0f00, x)`.

If the current behaviour isn't what we want, I wouldn't mind taking a look at writing a patch for this.

**Comment by jbevain** [comment]
Hey!

Yeah that's the expected behavior: the user is responsible for maintaining the exception handlers up to his/her wishes. Plus it would be quite a horrible breaking change :)

Jb

**Comment by bawr** [comment]
Now that you mention it, yeah, it would.

Oh, well, another reason for me to finally go ahead and write my small library on top of Cecil and put it up somewhere. ;)
