### ISSUE TITLE
Line ending issues in the repo

### ISSUE THREAD

**Issue by alexrp** [jbevain/cecil#202]
In a clean clone of the repo:

    $ git status
    ...snip...
    #       modified:   LICENSE.md
    #       modified:   Mono.Cecil.csproj
    #       modified:   Mono.Cecil.settings
    #       modified:   Mono.Cecil.sln
    ...snip...

This is on a Linux system with default Git line ending settings (`core.autocrlf` and `core.safecrlf`).

**Comment by jbevain** [comment]
Nice. Note sure what more I'm supposed to do, we're currently configured as:

https://github.com/jbevain/cecil/blob/master/.gitattributes

**Comment by alexrp** [comment]
Hmm, I think adding `.gitattributes` by itself is not enough, the files also need to have their line endings fixed up. I've opened PR #203 for this.

**Comment by jbevain** [comment]
Sure it's not enough, that's why I did this https://help.github.com/articles/dealing-with-line-endings/#platform-windows a while ago. But let see with your PR.
