### ISSUE TITLE
Mono Cecil generates invalid strong names on x64 assemblies

### ISSUE THREAD

**Issue by RehGina** [jbevain/cecil#206]
AnyCPU and x86 assemblies work fine. X64 assemblies strong names are invalid after re-writing

**Comment by RehGina** [comment]
I am not able to updload a zip here and did not find an alternative to add a zip to this issue. Hopefully this works:


![testproject](https://cloud.githubusercontent.com/assets/11296178/6500646/ba5100aa-c30e-11e4-951e-f2ad3137573b.png)

**Comment by RehGina** [comment]
![cmd](https://cloud.githubusercontent.com/assets/11296178/6592563/53da9c98-c7d0-11e4-861e-24e90be3cbf2.png)

**Comment by RehGina** [comment]
Output of PEVerify and SN tool. 
As I already wrote. Reading and writing of signed 64 bit assembly is enough. I do not inject any code in this test project

**Comment by leppie** [comment]
The problem is that you still refer to SampleAssembly.dll in the module name, so the loader will load that file if available or throw FileNotFound if not. Either way, it is not desired behavior IMO.

**Comment by RehGina** [comment]
I do not really understand your post. I start the test project via command line arguments in VS and I do not see why I should rename the sample assembly to something else. Did you download the test project and compiled it?

**Comment by leppie** [comment]
Yes I did. If you rename TracedAssembly.dll to SampleAssembly.dll, everything will work too.

**Comment by RehGina** [comment]
No, it will not. Thats exactly, what I did before. I only saved it under a different name to not need to recompile the assembly every time you start injector. In productive code we replace the assembly with the injected one. I tried both. After writing the signed 64 bit assembly the strong name is invalid!

**Comment by RehGina** [comment]
As you can see: Renaming does not change anything
![cmd2](https://cloud.githubusercontent.com/assets/11296178/6595664/b33f1832-c7ec-11e4-8385-9e771ba46331.png)

**Comment by leppie** [comment]
Ahh, that last screenshot says it all. I get the same.

**Comment by leppie** [comment]
If you compare the IL, everything seems to be the same except for `.imagebase` (and MVID). Not sure if that has something to do with it.

**Comment by RehGina** [comment]
It works on x86 assemblies and AnyCPU assemblies. Independent on how the tool itself has been compiled. I debugged already into the code and found the code which does the strong naming, but without spending a lot of time to understand whats going on there with byte arrays and such stuff, I do not feel self enabled to fix this bug. Thats why I would appreciate the help of the author very much.

**Comment by leppie** [comment]
I agree, something is fishy here. Try build Mono.Cecil from source and see if it was not fixed. The versions on Nuget are pretty old!

**Comment by RehGina** [comment]
I already did this. I downloaded the master branch and compiled it myself in AnyCPU and x64. No change.

**Comment by leppie** [comment]
:+1:

**Comment by RehGina** [comment]
@jbevain Did you already have a look at this issue. My tool is lying on ice until this bug is fixed. I spend so much time on it and it is so frustrating I cannot complete it :-(

**Comment by jbevain** [comment]
I have not: I'm just back home after a two weeks business trip abroad.

That being said:

* Cecil is open source and you can investigate and fix the issue.
* You can always contact me privately to discuss commercial support otherwise.

**Comment by jbevain** [comment]
Workaround while I investigate this: you can re-sign your assembly using the sn tool.

It goes like this:

* Inject code and sign with Cecil
* resign with sn -R Assembly.dll KeyPair.snk

**Comment by RehGina** [comment]
Thank you very, very much for this fix. I would have never found it. (y)(y)(y)
