### ISSUE TITLE
Mono.Cecil corrupts assemblies

### ISSUE THREAD

**Issue by Skyppid** [jbevain/cecil#207]
I'm not 100% certain whether this is an issue of Cecil or anything else. But I can't explain it other than this being an issue of Cecil.

I'm using Cecil to inject code into classes' constructor when members are tagged with a certain attribute. This worked absolutely fine for my WPF application. The code calls methods from a static class in a library that is shared among all injected assemblies.

Now I've been trying to add support for multi-assembly applications which are split up. The changes were fast done and it injects perfectly fine in all other assemblies, except for the startup-code (that one is only injected into executable entry-assemblies).

Now the WPF app still works fine. It references another assembly and uses the one class contained in it. But once I inject code into that assembly, it cannot be loaded anymore.

I always get a BadImageFormatException when trying to load it. Reflector still does open it and the Code both C# and IL does look normal and correct. If I try to read the AssemblyName of it, I get the same exception. And once I click "Build solution" in VS, I get that error in the error box:
> Error	1	Unknown build error, 'Could not load file or assembly 'file:///D:\Sicherung\Visual Studio\Workspace\Injection\build\Debug\Injection.Satellite.dll' or one of its dependencies. The module was expected to contain an assembly manifest.'

How comes? I really don't get what part of the assembly gets destroyed by that process. It's the same as with the application. The only difference is one being an .exe and one a .dll.

I can't figure it out. I already thought that I would need to update the references, but that doesn't even work.

What is this? I have absolutely no clue and no information what could be the reason. I can't find any solutions...

This is the fusion log I get:
> === Pre-bind state information ===
> LOG: DisplayName = Injection.Satellite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
> LOG: Appbase = file:///D:/Sicherung/Visual Studio/Workspace/Injection/build/Debug/
> LOG: Initial PrivatePath = NULL
> Calling assembly : Injection.Lab, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
> ===
> LOG: This bind starts in default load context.
> LOG: Using application configuration file: D:\Sicherung\Visual Studio\Workspace\Injection\build\Debug\Injection.Lab.vshost.exe.Config
> LOG: Using host configuration file: 
> LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
> LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
> LOG: Attempting download of new URL file:///D:/Sicherung/Visual Studio/Workspace/Injection/build/Debug/Injection.Satellite.DLL.
> ERR: Failed to complete setup of assembly (hr = 0x80131018). Probing terminated.

ADDITION: I tried this on another, real application. This time it's the executable itself which is broken. Same problem: BadImageFormatException caused by an broken manifest or something like that.

I tried everything and the injected code is perfectly fine (used more than 3 disassembler to check). Moreover it crashes not because of any injected code, else it'd be probably a different exception. So could this be a problem of Cecil?

**Comment by jbevain** [comment]
Are you sure you're not breaking strong names?
What does peverify say on the assembly?

**Comment by RehGina** [comment]
Yes I am quite sure, in test project I only read the assembly and write it again. Nothing else. I do not inject anything.

 

Regards Regina

 

Von: Jb Evain [mailto:notifications@github.com] 
Gesendet: Dienstag, 10. März 2015 17:07
An: jbevain/cecil
Betreff: Re: [cecil] Mono.Cecil corrupts assemblies (#207)

 

Are you sure you're not breaking strong names?
What does peverify say on the assembly?

**Comment by jbevain** [comment]
Reading and writing again is enough to break a strong name if the assembly is signed.

I'm afraid there's not much I can do without a self-contained repro showing what the issue is.

**Comment by Skyppid** [comment]
I do not yet use strong names. I once signed all assemblies until I noticed that this causes troubles and that I need to first implement some additional code for my injector, so that Cecil signs them again.

Has it to do with the fact, that I do change assemblies which are referenced by each other? Could this break anything and do I therefore need to fix the references after each assembly I changed?

**Comment by leppie** [comment]
@Skyppid What does PEVerify say before and after writing the assembly?

**Comment by RehGina** [comment]
Sorry I believe I added my comment to the wrong issue...

**Comment by Skyppid** [comment]
The entry-assembly (executable) gets first validated successfully without any errors or issues. The DLL I inject has 138 errors in the first place due to PostSharp and obviously the async-methods. But the whole application works fine, just tokens that cannot be found.

Once I inject, the executable is corrupt and PEVerify says just:
> [MD] An attempt was made to load a program with an incorrect format.

That's all I get. Even with verbose I don't see any more information. Okay with /IL attatched I get the following:
> Unverifiable PE Header/native stub.
> The module 'D:\Sicherung\Visual Studio\Workspace\App\build\x86\Debug\App.exe
> ' was expected to contain an assembly manifest.
> 2 Error(s) Verifying D:\Sicherung\Visual Studio\Workspace\App\build\x86\Debug\
> App.exe

I can't explain it other than that this is some kind of issue of Cecil...

I get the same error message for the DLL as well after Injection.

**Comment by jbevain** [comment]
@Skyppid any chance you could upload the binary (or send it to me privately) so I can investigate. This indeed looks like an issue on Cecil's side.

Thanks!

**Comment by Skyppid** [comment]
I just sent you an e-mail containing both the pre-injected and injected assemblies and detailed information. Thank you!

**Comment by jbevain** [comment]
@Skyppid, thanks! I've had a look at the assemblies, and I'm not sure the issue is on Cecil's side.

Let's take Pre-Injection/VisualBug.Satellite.dll

After injection you get a:

> [MD] An attempt was made to load a program with an incorrect format.

But if I only Read and Write the assembly with Cecil it verifies just fine.

Which leads me to think that stuff you're injecting is incorrect, and triggers invalid metadata.

Another example, when verifying VisualBug.Lab.exe after injection, I get:

> [IL]: Error: [C:\tmp\cecil\207\Injected\VisualBug.Lab.exe : VisualBug.Lab.TestClass1::Track01124][offset 0x0000002E] initlocals must be set for verifiable methods with one or more local variables.

For instance you're not settings InitLocals = true to methods to add.
