### ISSUE TITLE
Nuget package (0.9.6.0) wrong folder.

### ISSUE THREAD

**Issue by matthid** [jbevain/cecil#210]
Currently Mono.Cecil is build for TargetFramework 4.5.1 but it is packaged in the "net45" folder. This just caused a bit of havoc while updating (had to update the project to 4.5.1).
Please either move to "net451" or build for "net45"...

**Comment by jbevain** [comment]
Good catch! I'll push an updated package.

**Comment by jbevain** [comment]
Push a 0.9.6.1 nuget which builds on v4.5. Thanks!

**Comment by matthid** [comment]
Nice, thanks for the quick fix!
