### ISSUE TITLE
AssemblyWriter throws NullReference exception when version part of the AssemblyNameReference is null

### ISSUE THREAD

**Issue by csnemes** [jbevain/cecil#212]
During module Write the AssemblyWriter.AddAssemblyReferences method throws NullReference exception when tries to access version components (e.g. version.Major) if the version is null. I use a handcrafted reference and the constructor of the AssemblyNameReference class allows null as version argument, so I thought I can get away with null version. This issue is a bit similar to #51 but in a different place.

**Comment by jbevain** [comment]
That's a good catch, thanks!
