### ISSUE TITLE
Calling System.Reflection.Assembly.GetName() on resulting assembly fails

### ISSUE THREAD

**Issue by Zenexer** [jbevain/cecil#225]
Worked with an older version of Cecil; no longer working.

After loading an assembly, making some minor modifications, and writing it to a file, the result appears to be unusable.  Calling `Assembly.LoadFrom(path).GetName()` throws a `System.Globalization.CultureNotFoundException`.  The "problematic" culture is `neutral`.  There isn't any specific culture info associated with the assembly.  Does the same thing for both EXEs and DLLs.  Not seeing any culture attribute on the assembly in Cecil or anything else.  Current thread culture in en-US, and executing assembly is neutral.

The changes made to the assembly with Cecil only involve method body manipulation; no types are added/removed, etc.  Just downloaded the latest version of Cecil from GitHub and compiled in Visual Studio 2013 for .NET 4.0.

**Comment by jbevain** [comment]
Ah good catch. That's probably due to today's 0acff1c6966071e1fac9fa70983c75f27542c4cc, so we're lacking a test here.

Thanks for the heads up!

**Comment by Zenexer** [comment]
Thanks, I'll give the fix a test run later tonight.
