### ISSUE TITLE
Deferred reading of mscorlib fails

### ISSUE THREAD

**Issue by erik-kallen** [jbevain/cecil#232]
Of these tests, the first one fails:

	[Test]
	public void TestThatFails() {
		var asm = AssemblyDefinition.ReadAssembly (typeof(object).Assembly.Location, new ReaderParameters(ReadingMode.Deferred));
		var obj = asm.MainModule.TypeSystem.Object;
		Assert.IsInstanceOf <TypeDefinition>(obj);
	}

	[Test]
	public void TestThatPasses() {
		var asm = AssemblyDefinition.ReadAssembly (typeof(object).Assembly.Location, new ReaderParameters(ReadingMode.Immediate));
		var obj = asm.MainModule.TypeSystem.Object;
		Assert.IsInstanceOf <TypeDefinition>(obj);
	}

My investigations show that this is becase the property ```ModuleDefinition.TypeSystem``` uses a method ```TypeSystem.CreateTypeSystem```, which uses a helper method ```IsCoreLibrary```, which checks ```module.MetadataSystem.HasSystemObject```, but the ```HasSystemObject``` property is not set until the module is not read (and getting the type system does not force a read), hence the AssemblyDefinition representing mscorlib ends up with a ```CommonTypeSystem``` instead of a ```CoreTypeSystem```.

**Comment by jbevain** [comment]
Good catch, thanks!
