### ISSUE TITLE
Can't access extension methods

### ISSUE THREAD

**Issue by LiangChow** [jbevain/cecil#239]
Hi,
I Can't access extension methods (e.g : IsVarArg, GetSentinelPosition) 
Please see the following error.

Severity	Code	Description	Project	File	Line
Error	CS0122	'Mixin.IsVarArg(IMethodSignature)' is inaccessible due to its protection level	ConsoleApplication1	C:\Users\Liang\Downloads\Compressed\cecil-master\ConsoleApplication1\Program.cs	19

**Comment by jbevain** [comment]
Hi!

Yeah that's pretty much expected :) I don't feel comfortable making those public.

Thanks!
