### ISSUE TITLE
PortablePdb support(Roslyn cross-platform debugging symbols file format)

### ISSUE THREAD

**Issue by DavidKarlas** [jbevain/cecil#252]
Hi all,

PortablePdb format seems pretty final at this point...

@jbevain I assume you don't have any short term plans to add support for this?

@tmat Since Mono.Cecil is major library in .Net world & used by many projects involved in IL manipulation which also need debug symbols manipulation to be there, are you or anyone else from Roslyn team considering contributing this to Mono.Cecil?

@tmat is there some minimalistic NuGet package that has portable format reader/writer?

@jbevain would you prefer copying source code files from https://github.com/dotnet/roslyn/tree/master/src/Debugging/Microsoft.DiaSymReader.PortablePdb to Mono.Cecil repo or NuGet package?

Regards,
David

**Comment by tmat** [comment]
Re reader/writer: System.Reflection.Metadata. Currently has just reader, we are working on moving a writer there from Roslyn (see https://github.com/dotnet/roslyn/pull/6634).

**Comment by tmat** [comment]
Re Microsoft.DiaSymReader.PortablePdb -- this is just a bridge to support legacy apps that use ISymUnmanagedReader interfaces. I'd rather see Cecil reading the data directly or even better using System.Reflection.Metadata to do so.

**Comment by tmat** [comment]
Re contribution to Cecil -- not currently mainly due to lack of resources. If @jbevain would be ok with porting Cecil "backend" to System.Reflection.Metadata then, among other benefits, adding support for Portable PDB would be trivial.

**Comment by manu-silicon** [comment]
Any status on this? Is this planned?

**Comment by jbevain** [comment]
That's definitely planned and on-going. I should have a PR out in a couple weeks.

**Comment by manu-silicon** [comment]
Great. Glad to hear this. Thanks!

**Comment by jbevain** [comment]
Merged in master.
