### ISSUE TITLE
PCL is still not supported

### ISSUE THREAD

**Issue by Licshee** [jbevain/cecil#262]
no news since #220 ?

**Comment by jbevain** [comment]
@Licshee it's supported in master, it hasn't been released as a nuget though.

**Comment by Licshee** [comment]
just to make sure: does that mean it's still not guaranteed to run for PCL/cross-platform?

**Comment by Licshee** [comment]
I mean, is using Cecil in PCL as safe as running on .NET Framework ATM?

**Comment by jbevain** [comment]
It should work, yes. Let us know if it doesn't :).
