### ISSUE TITLE
System.InvalidCastException in Mono.Cecil.MetadataBuilder.GetConstantSignature

### ISSUE THREAD

**Issue by mrexodia** [jbevain/cecil#264]
```
System.InvalidCastException: Unable to cast object of type 'System.Byte' to type 'System.String'.

   at Mono.Cecil.MetadataBuilder.GetConstantSignature(ElementType type, Object value)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypeDefs()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName)

  --- removed ---
```

Built with the latest commit.

I believe the offending line is https://github.com/jbevain/cecil/blob/master/Mono.Cecil/AssemblyWriter.cs#L1915 (AssemblyWriter.cs:1915), however I have no clue about the codebase so I don't really know what this line is supposed to do or how to debug it. Unfortunately I cannot share the assembly, but please tell me if I can do something to assist.

**Comment by mrexodia** [comment]
Here is a screenshot of the field that causes this exception (the binary in question is obfuscated):

![img](http://i.imgur.com/d1Ujgck.png)

**Comment by jbevain** [comment]
Obfuscators  ¯\_(ツ)_/¯

Thanks for the report.

**Comment by mrexodia** [comment]
I switched to dnlib in the meantime, there it works fine. I'm not sure but
maybe the casting shouldn't depend on the type of the field? I saw that
right after it converts it back to a byte array so maybe this can be done
in a more direct way?

**Comment by apwillies** [comment]
Anybody know if this got fixed? I'm hitting this error at the LinkAssemblies step using Dotfuscator on my Android Xamarin project...

**Comment by mrexodia** [comment]
@apwillies if you can, switch to dbLib: https://github.com/0xd4d/dnlib

**Comment by ruhanijeb** [comment]
i am also facing the same issue. Is there any time line this issue will be resolved or there any thing that i can do to resolve this in mean time.Temporary fix??

**Comment by SimonCropp** [comment]
@ruhanijeb work around seem to be "disable obfuscation "

**Comment by ruhanijeb** [comment]
@SimonCropp from where i can do that?

**Comment by ruhanijeb** [comment]
@SimonCropp thank you very much for helping me out

**Comment by ruhanijeb** [comment]
Here is my visual studio details:
Microsoft Visual Studio Professional 2019
Version 16.1.5
VisualStudio.16.Release/16.1.5+29025.244
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Professional


VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.


Attaching my detailed log:
[detailedlog.txt](https://github.com/jbevain/cecil/files/3375664/detailedlog.txt)

**Comment by ruhanijeb** [comment]
hey guys any progress in this or any solutions. i am not using obfuscation here

**Comment by jbevain** [comment]
@ruhanijeb hello,

Looking at the logs you provided, the error seems to arise in the Xamarin.Android Linker. Disabling the linker should unlock you.

In the meantime, I can't do anything unless you provide a DLL that is not obfuscated and that I can look at.

**Comment by ruhanijeb** [comment]
[2.18.3.zip](https://github.com/jbevain/cecil/files/3404720/2.18.3.zip)
Hi ,

As per the logs i thin this is the dll that is causing the problem.Because in logs when trying to skip this dll its giving me error.

**Comment by jbevain** [comment]
That `Oracle` assembly is obfuscated and designed to crash Cecil.

I suggest you skip linking of that one assembly:

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#linkskip

**Comment by PeterPolacek** [comment]
I edited Mono.Cecil.dll because of this error. So you can try it .. 
[Mono.Cecil.zip](https://github.com/jbevain/cecil/files/10558895/Mono.Cecil.zip)

**Comment by sparkybg** [comment]
> I found the problematic code for Mono.Cecil.dll, so i edited because of this error. So you can try it .. [Mono.Cecil.zip](https://github.com/jbevain/cecil/files/10558895/Mono.Cecil.zip)

Could you share any details?

I need it built for .net 2.0 in order to use it with RebelDotNet, so I must rebuild it myself.
