### ISSUE TITLE
Not injecting a OpCOdes.Ret

### ISSUE THREAD

**Issue by ElementalVenom** [jbevain/cecil#265]
So I am injecting a thing that in c# would be 
`if(!MethodThatReturnsABool()){
        return;
}
`
the actual list of IL instructions is
`
                    Instruction SCIL1 = updateMethod.Body.GetILProcessor().Create(OpCodes.Ldarg_0);
                    Instruction SCIL2 = updateMethod.Body.GetILProcessor().Create(OpCodes.Ldstr, "SteamChannel");
                    Instruction SCIL3 = updateMethod.Body.GetILProcessor().Create(OpCodes.Call, asm.MainModule.Import((typeof(UnityEngine.Component).GetMethod("GetComponent", new Type[] { typeof(System.String) }))));
                    Instruction SCIL4 = updateMethod.Body.GetILProcessor().Create(OpCodes.Castclass, asm.MainModule.Import(typeof(SDG.Unturned.SteamChannel)));
                    Instruction SCIL5 = updateMethod.Body.GetILProcessor().Create(OpCodes.Ldfld, asm.MainModule.Import((typeof(SDG.Unturned.SteamChannel).GetField("isOwner"))));
                    Instruction SCIL6 = updateMethod.Body.GetILProcessor().Create(OpCodes.Brtrue_S, I2L1);
                    Instruction SCIL7 = updateMethod.Body.GetILProcessor().Create(OpCodes.Ret);`

Everything works but when it compiles to c# it doesn't put the ret in. It skips it and adds the rest of the il code. So the re-compiled c# looks like
`if(!MethodThatReturnsABool()){
        
}
//Rest of code
`

**Comment by jbevain** [comment]
Hi,

I'm afraid it's impossible to tell from this if this is an actual issue in Cecil or in your code. Please use the mono-cecil Google Group for questions / discussions, and the GitHub issues for actual bug with repros.

Thanks!
Jb
