### ISSUE TITLE
NotSupportedException in TypeSystem.cs

### ISSUE THREAD

**Issue by jogibear9988** [jbevain/cecil#267]
When opening MahApps.Metro with SharpDevelop, I get a Exception in 

     LookupType (string @namespace, string name)

see:
<img width="733" alt="bildschirmfoto 2016-04-18 um 00 02 58" src="https://cloud.githubusercontent.com/assets/364896/14590377/ea45e276-04f8-11e6-8e43-0ed58c8a3c5f.png">

you see here where I'm comming from:

<img width="708" alt="bildschirmfoto 2016-04-18 um 00 01 17" src="https://cloud.githubusercontent.com/assets/364896/14590363/ae4d47e6-04f8-11e6-83d5-4c315a772cdd.png">

<img width="709" alt="bildschirmfoto 2016-04-18 um 00 01 50" src="https://cloud.githubusercontent.com/assets/364896/14590368/bc2c4060-04f8-11e6-9d09-303aa78d4e5c.png">

full stacktrace:

<img width="1322" alt="bildschirmfoto 2016-04-18 um 00 04 28" src="https://cloud.githubusercontent.com/assets/364896/14590382/20ddcccc-04f9-11e6-87cb-e47e3f1d29a1.png">

**Comment by jbevain** [comment]
Thansk for reporting this!

Any chance you could upload a DLL somewhere that reproduces this? Or send me the link directly by email?

**Comment by jogibear9988** [comment]
I look that I create a small Example Project if possible!

**Comment by jogibear9988** [comment]
Problem:

SD is trying to load Assembly "System.Runtime.dll" out of "Microsoft.Bcl v1.0.19"

I created a small example project where I referenced this Nuget, and there it works.

      var q = ModuleDefinition.ReadModule("System.Runtime.dll", new ReaderParameters());
			if (q.Assembly.HasCustomAttributes)
			{
				var c = q.Assembly.CustomAttributes;
			}

but when running in SD I get here a Exception:

![unbenannt](https://cloud.githubusercontent.com/assets/364896/14595344/c6433afe-053e-11e6-9837-f2e675a36dd0.png)

**Comment by jogibear9988** [comment]
Ok, I'm wrong! Current Version of Cecil raises the error with my Example Project!

I works if I use the cecil nuget Version!

**Comment by jogibear9988** [comment]
[TestCecilError.zip](https://github.com/jbevain/cecil/files/223228/TestCecilError.zip)

**Comment by jbevain** [comment]
Thanks! I'll look into it.

**Comment by jbevain** [comment]
Out of curiosity, where did you get this version of System.Runtime.dll ?

**Comment by jbevain** [comment]
Fixed in 95b7b86c5e8646ff684443ac4aab3c037659b7f9. Thanks for the repro!

**Comment by jogibear9988** [comment]
Microsoft.Bcl v1.0.19", MahappsMetro has it in its packages.json, wich is already unlisted!
