### ISSUE TITLE
Failed to resolve assembly issue

### ISSUE THREAD

**Issue by zhangyang01123** [jbevain/cecil#274]
Hi,

I just use mono.cecil to edit existing resource strings in .net dll. Almost all the localized resource files work fine. But only the English original resource file does not work. 

The English project contains core logic code and references other dlls (OtherDLL.dll), this may cause exceptions when using mono.cecil, the test code and exception is below.

`AssemblyDefinition assemblyDefinition = AssemblyDefinition.ReadAssembly(resourceFileName);`
`// Some code`
`assemblyDefinition.Write(newFileName); // This will cause exception: "Failed to resolve assembly: 'OtherDLL, Version=10.1.1.1, Culture=neutral, PublicKeyToken=null'`

> `AssemblyDefinition assemblyDefinition = AssemblyDefinition.ReadAssembly(resourceFileName);`
> `// Some code`
> `assemblyDefinition.Write(newFileName); // This will cause exception: "Failed to resolve assembly: 'OtherDLL,  Version=10.1.1.1, Culture=neutral, PublicKeyToken=null'`

The english dll is TestDll.dll under deployment directory, and other localized resource dlls are TestDll.resources.dll under localized directory, like /de/TestDll.resources.dll and /zh-CN/TestDll.resources.dll.

So is it a bug or limitation? If so, could I use a walk around method to achieve goal?

Thanks.

**Comment by jbevain** [comment]
https://groups.google.com/forum/#!topic/mono-cecil/2YrccvV3dpY
