### ISSUE TITLE
Eta for a new nuget?

### ISSUE THREAD

**Issue by SimonCropp** [jbevain/cecil#280]

**Comment by jbevain** [comment]
Soon. I'm in the process of merging the feature branches for 0.10.

**Comment by jbevain** [comment]
@SimonCropp there's a fair amount on changes in master; All tests are green, could you run your tests with green light the version bump?

**Comment by dsplaisted** [comment]
I'd love to see a new NuGet too.  The master branch appears to fix dsplaisted/strongnamer#4.

Since Strong Namer ships the Cecil assemblies directly in its NuGet package, I may resort to just using the Cecil assemblies I build myself.

**Comment by jbevain** [comment]
@SimonCropp @dsplaisted you guys can consume the new beta nuget http://cecil.pe/post/149243207656/mono-cecil-010-beta-1
