### ISSUE TITLE
Why this project is named "Mono.Cecil"? Any relation with Mono?

### ISSUE THREAD

**Issue by CreateAndInject** [jbevain/cecil#285]
Why this project is named "Mono.Cecil"? Any relation with Mono?

What's the meaning of "Cecil"? abbreviation?

**Comment by jbevain** [comment]
Yes, Mono.Cecil has a long relation with the [Mono project](http://www.mono-project.com/docs/tools+libraries/libraries/Mono.Cecil/)

Cecil is a nice name that ends with CIL.
