### ISSUE TITLE
Some questions about the upcoming release

### ISSUE THREAD

**Issue by matthid** [jbevain/cecil#287]
I read #282 and have some questions about the upcoming 0.10 release:

- Will it be the first `netstandard` compatible release?
- Will it still work with non-portable pdbs and detect automatically?
- When will the first version be available (such that I can remove the self build version [here](https://github.com/fsprojects/Paket/pull/1785) and [here](https://github.com/fsharp/FAKE/pull/1281))

Thank you!

**Comment by jbevain** [comment]
@matthid hey,

We're very close to 0.10, I'm waiting to hear from a particular downstream that is kicking the tires, and then we should be good to go.

* 0.10 works is netstandard 1.3 compatible.
* The desktop version will work with native pdbs, the netstandard version only understands portable pdbs.
* Hopefully this week.

In theory, we could make the reading side of the native pdb support work on netstandard if that's a requirement for you guys.

**Comment by matthid** [comment]
> In theory, we could make the reading side of the native pdb support work on netstandard if that's a requirement for you guys.

I think there is no need more curiosity (and knowledge if weird things happen), lets just see how it goes :). Looking forward to the release. Thank you for the fast info! 

Just to clarify the desktop version will not support portable pdbs or both?

**Comment by jbevain** [comment]
The desktop version supports portable pdbs native pdb and Mono's mdb.
