### ISSUE TITLE
Mono.Cecil causes ILSpy to crash when reading a specific assembly

### ISSUE THREAD

**Issue by ElementalVenom** [jbevain/cecil#289]
ILSpy crashes when I try to read one specific assembly(It doesnt do it for all assemblies). The stacktrace it pointing back to Mono.Cecil though so im posting the error here. Theres a screenshot of the error [HERE](https://s21.postimg.io/8mfh5zeyf/Cecil_Crash_Error_Report.png)

**Comment by jbevain** [comment]
Thanks for reporting this @ElementalVenom. I'll need a repro though. Could you please upload one or email it to me privately? Thanks!

**Comment by ElementalVenom** [comment]
I'd rather do it privately, Whats your email?

**Comment by jbevain** [comment]
It's on my github profile.

**Comment by jbevain** [comment]
Fixed in 8e65ef5f5259ad590127f281dbe8cd378f8ca801. Thanks again for reporting this.

**Comment by ElementalVenom** [comment]
Thanks for fixing it so quickly, I'm used to waiting weeks
