### ISSUE TITLE
netstandard support?

### ISSUE THREAD

**Issue by kdawg1406** [jbevain/cecil#290]
Hi,

Does cecil support reflecting netstandard assemblies?  

I have a tool that uses the latest NuGet package for cecil mono, users are reporting cecil errors when reflecting netstandard assemblies.

Wondering if you have tested this scenario and if I need to do something different.

Thank you!!!

Karl

**Comment by jbevain** [comment]
I can't think of a reason t see why Cecil couldn't read or write .net standard assemblies, but who knows :)

Could you get more details? The errors/exceptions they're running into?

**Comment by kdawg1406** [comment]
Will do.  Thank you.

**Comment by kdawg1406** [comment]
@jbevain I just did a test with WPF and netstandard and it worked perfectly.

I customer of mine reported a problem with Xamarin Forms and netstandard.  However, his scenario was bizarre.  

I know that Xamarin is moving forward with netstandard.  I'll close this for now until I have a real concrete example.  

Apology for randomizing.

Good to know that this is the first you've heard of this, this makes me feel better.

Best,

Karl

**Comment by jbevain** [comment]
No worries! Thanks for investigating!
