### ISSUE TITLE
Small fix in info

### ISSUE THREAD

**Issue by li0nsar3c00l** [jbevain/cecil#292]
[Here](https://github.com/jbevain/cecil/wiki/Users) you wrote, [dnSpy](https://github.com/0xd4d/dnSpy) uses cecil. This is currently not correct. It's based on 0xd4d's own [library](https://github.com/0xd4d/dnlib).

Just to let you know

**Comment by jbevain** [comment]
Thanks for the heads-up! I haven't touched the page for a while, so it may or may not be completely accurate or up to date. I'll remove this entry.
