### ISSUE TITLE
Missing namespaces, methods, and properties after upgrading to 0.10.0

### ISSUE THREAD

**Issue by plioi** [jbevain/cecil#296]
I'm attempting to upgrade my project to work with .NET Core, and I make use of Mono.Cecil to detect line numbers of methods. When I reference 0.10.0-beta1-v2 from a netcoreapp1.0 project, a few things I've depended on in recent versions disappear. I'm no longer able to say `using Mono.Cecil.Rocks;`, which keeps me from being able to call `GetMethods()` on a `TypeDefinition`. Also, I've been making use of `Instruction.SequencePoint`, which is no longer available.

Is there upgrade advice for these prerelease packages?

This is the code file I'm hoping to upgrade: https://github.com/fixie/fixie/blob/daf79dc7d749db85667732600bad137e05be233c/src/Fixie.Runner/SourceLocationProvider.cs

It's part of a test framework that needs to report method line numbers to `dotnet test`.

Here's the relevant part of project.json I'm experimenting with.

```cs
"netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.1",
          "type": "platform"
        },
        "Mono.Cecil": "0.10.0-beta1-v2"
      }
    }
```

**Comment by jbevain** [comment]
Please have a look at [the change log for 0.10](http://cecil.pe/post/149243207656/mono-cecil-010-beta-1).

It explains why Instruction.SequencePoint was removed and what you should replace it with.

Mono.Cecil.Rocks is not compiled for the .netstandard 1.3, I suggest you just include the files that you need in your project: https://github.com/jbevain/cecil/blob/master/rocks/Mono.Cecil.Rocks/TypeDefinitionRocks.cs

**Comment by plioi** [comment]
Thanks for the quick response!

**Comment by plioi** [comment]
I'm having some trouble with the disposability of ModuleDefinition.

Here I have a using block that processes an assembly:

https://github.com/fixie/fixie/blob/5c68d9cf90ac2fc5c103ac6f93469db941acf678/src/Fixie.Runner/SourceLocationProvider.cs#L46

I haven't been able to nail down when, but this occasionally throws an IOException because "The process cannot access the file '....pdb' because it is being used by another process."

Would the Dispose() called at the end of the using block ever not close the file?

**Comment by plioi** [comment]
FWIW, when this fails it's it's failing on the very first attempt to ReadModule. My project is a test framework, and I'm trying to test my ability to determine line numbers for a dll, namely the dll of self-tests. I haven't had trouble reading from that file in previous versions, but this may be a red herring outside of Cecil's control.

**Comment by jbevain** [comment]
It looks like that something is preventing Cecil to read the pdb then. Would be interesting to see if another process holds an exclusive handle on the pdb.

**Comment by jbevain** [comment]
Here's where the pdb is read:

https://github.com/jbevain/cecil/blob/master/symbols/pdb/Mono.Cecil.Pdb/PdbHelper.cs#L25

That could throw an IOException if the file is already opened and locked.

You could try to add code to create a file handle on the pdb yourself before reading with Cecil, and error out if you can't read it. In that case it would be interesting to determine who owns the lock.
