### ISSUE TITLE
Problems with debug symbols API

### ISSUE THREAD

**Issue by marek-safar** [jbevain/cecil#299]
The current design has few issues when dealing with debug symbols as it still relies on hardcoded platform specific values.
- No simple way to read and write to same portable PDB file (similar to ReadWrite in ReaderParameters class) 
- No debug symbols auto-detection, which requires quite complex logic to be copied everywhere when dealing with ppdb/pdb/mdb support.
- No support for embedded portable pdb

**Comment by spardathementor** [comment]
same here!

**Comment by jbevain** [comment]
> * No simple way to read and write to same portable PDB file (similar to ReadWrite in ReaderParameters class)

I'm not sure I understand the issue here. Just pass a PortablePdbReader and PortablePdbWriter as parameters to Read and Write, and it will read and write from the same portable pdb. Could you detail what doesn't work for you here?

> * No debug symbols auto-detection, which requires quite complex logic to be copied everywhere when dealing with ppdb/pdb/mdb support.

The problem is that having one "auto" detection logic will work for someone and not for someone else. Example : what happens if there's a pdb and a mdb for the same assembly?

 * No support for embedded portable pdb

The current design which treats the embedded portable pdb info as part of the assembly, and will automatically read and write as part of the assembly. What more or less would you like?

**Comment by marek-safar** [comment]
> #1 issue

ReadWrite is not available for debug symbols. If you use filename you hit https://github.com/jbevain/cecil/blob/68bcb750b898f4882a5af44299bb322aaa531f93/symbols/pdb/Mono.Cecil.Pdb/PdbHelper.cs#L25 so the file is open for reading only.

> #2 issue

if there is pdb and mdb for same assembly and they are both valid (MVID matching, etc) then it'd be fine to throw AmbiguousSymbolFileException or something like that. Similarly this could be implementation as some DetectionLogic class which could have the preferences set/adjusted by public API and the result then passed via existing API. I think any of this is better than today's approach of writing quite complex logic of headers decoding, files/streams matching

> #3 issue

How do I configure Cecil to read **only** embedded portable pdb?

**Comment by jbevain** [comment]
> ReadWrite is not available for debug symbols. If you use filename you hit https://github.com/jbevain/cecil/blob/68bcb750b898f4882a5af44299bb322aaa531f93/symbols/pdb/Mono.Cecil.Pdb/PdbHelper.cs#L25 so the file is open for reading only.

Please provide a repro, I'll look into it.

> How do I configure Cecil to read only embedded portable pdb?

You don't pass a ISymbolReaderProvider. Cecil will read the debug tables just like any other table.

**Comment by marek-safar** [comment]
I'll make a repro.

If I don't pass ISymbolReaderProvider will it also write "automatically"? Basically the flow is to rewrite dlls with embedded pdbs only

**Comment by marek-safar** [comment]
Filled the issue for missing ReadWrite as https://github.com/jbevain/cecil/issues/304

**Comment by jbevain** [comment]
Thanks Marek, this one is fixed.

One thing we don't have an API for is a way to turn an external debug symbol into embedded ppdb data. Is this what you mean?

**Comment by marek-safar** [comment]
yes, you can look at it this was. I was thinking more in terms of mdb, ppdb, embedded-ppdb options
Same goes the other way turn embedded ppdb into external ppdb

**Comment by jbevain** [comment]
So looking back at this issue.

> No simple way to read and write to same portable PDB file (similar to ReadWrite in ReaderParameters class)

This has been fixed long ago.

> No debug symbols auto-detection, which requires quite complex logic to be copied everywhere when dealing with ppdb/pdb/mdb support.

This is being worked on in #322.

> No support for embedded portable pdb

Current master supports reading and writing embedded portable pdb. But it does treat them as tables that are part of the metadata, so you can not read from external and write to embedded, or opt-out of reading embedded symbols.

**Comment by jbevain** [comment]
All other items are closed, we still need to address

> Current master supports reading and writing embedded portable pdb. But it does treat them as tables that are part of the metadata, so you can not read from external and write to embedded, or opt-out of reading embedded symbols.

For 0.10.

**Comment by jbevain** [comment]
Visual Studio 2017 has a completely different implementation of embedded debug information. It's implemented in #348.
