### ISSUE TITLE
System.IO.IOException: Sharing violation on path when debug symbols exist

### ISSUE THREAD

**Issue by marek-safar** [jbevain/cecil#304]
Simple sample

```
		var readerParameters = new ReaderParameters {
			ReadWrite = true,
		};

		readerParameters.ReadSymbols = true;
		readerParameters.SymbolReaderProvider = new PortablePdbReaderProvider ();

		using (var assembly = AssemblyDefinition.ReadAssembly (assemblyLocation, readerParameters)) {

			// Modify the assembly

			var writerParameters = new WriterParameters ();

			writerParameters.WriteSymbols = true;
			writerParameters.SymbolWriterProvider = new PortablePdbWriterProvider ();

			assembly.Write (writerParameters);
		}
	}
```

Crashes on writing with https://gist.github.com/marek-safar/cd9099593f9d607c2cae4e11c081f91d because AssemblyReader opens files always in read-only mode https://github.com/jbevain/cecil/blob/68bcb750b898f4882a5af44299bb322aaa531f93/symbols/pdb/Mono.Cecil.Pdb/PdbHelper.cs#L25

**Comment by StephaneDelcroix** [comment]
I started getting this error after upgrading to 0.10-beta, and the error stills exists after upgrading to master. Investigating some more before reopening the issue
