### ISSUE TITLE
cecil vs using System.Reflection;

### ISSUE THREAD

**Issue by inderpal58** [jbevain/cecil#305]
Steps to get issue:

Created a exe with AssemblyInfo.cs.
run  exe through https://github.com/yck1509/ConfuserEx.

_Mono.Cecil says no Custom Attribute thus assembly.HasCustomAttributes is false.
Assembly.LoadFile using System.Reflection returns Custome Attributes._

**Comment by jbevain** [comment]
Hi, thanks for reporting this. Please upload a binary somewhere.

**Comment by inderpal58** [comment]
Hi, Sorry, I can not share exe (comfidential). I will try to fix issue and if not able to fix will generate dummy exe. Thank you.

**Comment by jbevain** [comment]
A dummy exe works. I need something to work with :)

**Comment by jbevain** [comment]
I'm closing this as this is inactive. Please provide a binary to test if you want to re-open this. Thanks!
