### ISSUE TITLE
Non beta release

### ISSUE THREAD

**Issue by sawilde** [jbevain/cecil#308]
Do we have a timescale on when the release will become non-beta?

**Comment by jbevain** [comment]
No ETA right now. We'll publish a beta 2 shortly, and then we have some more work to do to properly support the embedded portable pdb information. So Q1 next year?

**Comment by sawilde** [comment]
I see :( - I was hoping for a release as I am not keen on releasing a new version of OpenCover with a beta package. 

What does beta mean to you? Is it "beware, here be dragons" or just missing a few features?

**Comment by jbevain** [comment]
The portable pdb support is definitely beta in the sense that it's not battle tested. The rest of Cecil is the battle tested code that runs in 0.9, I wouldn't worry if you only depend on it. What's missing to leave the beta status now is a bit more testing of the ppdb support (we're kicking the tires with our friends in Mono on that) and some additions to the API to support reading from any symbol and write to embedded portable pdb and vice versa.

**Comment by sawilde** [comment]
It is mainly the .net core (portable?) pdb support my users are clamouring for. I have a beta release that includes your beta that seems to work but don't want to create a release with a beta mono.cecil if I can help it.

**Comment by jbevain** [comment]
We're in the final stages of integrating 0.10 into Mono, MonoDevelop, and Xamarin products. The number of issues we're hitting is getting smaller and smaller, we should have the final 0.10 in a few short weeks.

**Comment by onovotny** [comment]
@jbevain are embedded ppdb's supported by Mono.Cecil now?

**Comment by jbevain** [comment]
@onovotny, since 0.10-beta5 they are, yes.

**Comment by SimonCropp** [comment]
@jbevain i know u r still working on the changes in .net (net standard, portable pdbs etc). but given for the vast majority of use cases ("desktop" .net, pcls, normal pdb/mdb etc) cecil is rock solid, i would be happy with a stable release as is.
