### ISSUE TITLE
AssemblyResolutionException When Writing Unmodified Module

### ISSUE THREAD

**Issue by marko-vasic** [jbevain/cecil#311]
ModuleDefinition.Read followed by ModuleDefinition.Write 
(without any changes in between to the read module) causes AssemblyResolutionException.

The dll under test is RequestReduce.Facts\\bin\\Debug\\RequestReduce.Facts.dll
from project: https://github.com/mwrock/RequestReduce
commit SHA: 2d6fec822ff0a16ac155047bc475048e513d439d
Stack Trace:
[AssemblyResolutionException1.txt](https://github.com/jbevain/cecil/files/675476/AssemblyResolutionException1.txt)

Another dll with the same problem is Src\\Newtonsoft.Json.Tests\\bin\\Debug\\Net40\\Newtonsoft.Json.Tests.dll 
from project: https://github.com/JamesNK/Newtonsoft.Json
commit SHA: be8ca7a8707de8be80db91e06e51537cd603b69f
Stack Trace:
[AssemblyResolutionException2.txt](https://github.com/jbevain/cecil/files/675478/AssemblyResolutionException2.txt)

Does anyone have idea why is this occuring?

**Comment by jbevain** [comment]
The ResolutionException should tell you which assembly is required.

This happens when the assembly has a construct that needs resolving (retrieving the type definition in its defining assembly) to now the size of some metadata element to properly write it back.

**Comment by jbevain** [comment]
I'm closing this as this can be an expected behavior.

**Comment by marko-vasic** [comment]
Thank you. 

As you mentioned the problem is that another assembly is referenced.
The referenced assembly is on the same path as the read one.
In some cases module.AssemblyResolver can resolve an assembly on the same path,
in the cases I provided it cannot.
The fix to my problem is shown hereunder:

ModuleDefinition module = ModuleDefiniton.ReadModule(path);
...
// fix
if (module.AssemblyResolver is DefaultAssemblyResolver)
{
  DefaultAssemblyResolver resolver = module.AssemblyResolver as DefaultAssemblyResolver;
  resolver.AddSearchDirectory(System.IO.Path.GetDirectoryName(module.FullyQualifiedName));
}
...
// now this does not cause ResolutionException
module.Write(module.FullyQualifiedName)

Do you think this is a design bug or not?

**Comment by jbevain** [comment]
I think all applications should provide their own Assembly Resolvers and control how references are resolved.

The fact that it sometimes work and sometimes not sound problematic though. Do you have more details on this?

**Comment by marko-vasic** [comment]
You can reproduce this behaviour following next steps:

RequestReduce
-git clone https://github.com/mwrock/RequestReduce
-git checkout 2d6fec822ff0a16ac155047bc475048e513d439d
-msbuild RequestReduce.sln
-write c# application that reads RequestReduce.Facts\bin\Debug\RequestReduce.Facts.dll
and writes to the same location

NewtonsoftJson
-git clone https://github.com/JamesNK/Newtonsoft.Json
-git checkout be8ca7a8707de8be80db91e06e51537cd603b69f
-msbuild Src\\Newtonsoft.Json.Net40.sln
-read and write Src\Newtonsoft.Json.Tests\bin\Debug\Net40\Newtonsoft.Json.Tests.dll

Error does not occur in following project for example:
DynamicExpresso
-git clone https://github.com/davideicardi/DynamicExpresso.git
-git checkout 186219674dae44278b9ed6c662400fbdbeb65951
-msbuild DynamicExpresso.sln
-read and write test\\DynamicExpresso.UnitTest\\bin\\Debug\\DynamicExpresso.UnitTest.dll

Note that error in RequestReduce and NewtonsoftJson can be quick fixed
using code snippet I provided in one of previous emails.
In all 3 cases test module is read and written, each test module references
program module that is located within the same directory as the test module,
in first 2 cases Exception is thrown, in the 3rd one it is not.

**Comment by jbevain** [comment]
Ah right. The differences comes from the fact that only some metadata constructs require resolving before writing them back. They're all related to enums (in custom attributes or in constant fields), as there's no way to know what the size of an enum is without resolving its type definition.

**Comment by marko-vasic** [comment]
Should a module directory be included in the module's AssemblyResolver Search Directories by default?

Is following way a good way to work around the Resolution exception?
if (module.AssemblyResolver is DefaultAssemblyResolver)
{
  DefaultAssemblyResolver resolver = module.AssemblyResolver as DefaultAssemblyResolver;
  resolver.AddSearchDirectory(System.IO.Path.GetDirectoryName(module.FullyQualifiedName));
}

Thank you,
Marko
