### ISSUE TITLE
Using Cecil on .NET Core results in corrupted (?) assemblies

### ISSUE THREAD

**Issue by mellinoe** [jbevain/cecil#312]
I am using the latest beta version on .NET Core and seeing that very simple code is not working, while the same code works fine on .NET Framework. I have a very simple repro linked below, but I was originally trying to track this down as part of a more complicated application. All the project below does is load an assembly and save it back out unmodified.

Repro steps:
* Clone https://github.com/mellinoe/CecilRepro
* Build both projects
* Run `dotnet run ..\testapp\bin\Debug\netcoreapp1.0\testapp.dll ..\testapp\bin\Debug\netcoreapp1.0\testapp2.dll` in the "rewriter" directory
* `move ..\testapp\bin\Debug\netcoreapp1.0\testapp2.dll ..\testapp\bin\Debug\netcoreapp1.0\testapp.dll`
* `dotnet ..\testapp\bin\Debug\netcoreapp1.0\testapp.dll`

Expected: The program still prints out "Hello World!" as it has not been changed.
Actual:
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'testapp.dll'. An attempt was made to load a program with an incorrect format.
```

When I run the "rewriter" program under .NET Framework, everything works as expected.

Also to note: after running the rewriter on .NET Core, I get this message from peverify checking the rewritten assembly:
```
The module 'testapp.dll' was expected to contain an assembly manifest.
```

**Comment by jbevain** [comment]
Interesting. Thanks for the great repro & steps, I'll look into it!

**Comment by jbevain** [comment]
@mellinoe first things first, do you see a difference if you change:

```csharp
    AssemblyDefinition.ReadAssembly(args[0]).Write(args[1]);
```

into:

```csharp
    using (var assembly = AssemblyDefinition.ReadAssembly(args[0]))
        assembly.Write(args[1]);
```

?

**Comment by mellinoe** [comment]
Trying that now...

**Comment by jbevain** [comment]
Yeah that was a tricky one. I didn't spend too much time investigating the root cause, but there's a difference between .NET Desktop and .NET Core in either FileStream or BinaryWriter. To fix it, I had to flush the BinaryWriter used to write the assembly.

**Comment by mellinoe** [comment]
> but there's a difference between .NET Desktop and .NET Core in either FileStream or BinaryWriter

Interesting. If you know what the difference is exactly, we would love a bug report over at https://github.com/dotnet/corefx.

Will there be a new beta nuget package that I could use to test out the fix?

**Comment by jbevain** [comment]
Feel free to create a bug using your repro with a reference to 0.10 beta 1 on corefx, but I'm afraid I won't have time to extract a smaller repro myself in the coming days.

I'll push a beta 2 shortly.
