### ISSUE TITLE
Optimize StringHeap size

### ISSUE THREAD

**Issue by erozenfeld** [jbevain/cecil#314]
String suffixes can be used to optimize the size of StringHeap. For example if `foobar` and `bar` are needed, only `foobar` has to be emitted, its suffix can be used for `bar`. Here is how this is implemented in Roslyn: https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/Core/Portable/System/Reflection/Metadata/Ecma335/MetadataBuilder.Heaps.cs#L287

**Comment by jbevain** [comment]
@erozenfeld cool, are you working on adding support for this to Cecil?

**Comment by erozenfeld** [comment]
@jbevain Not yet but I can probably get to this later this week.

**Comment by jbevain** [comment]
Sounds great, looking forward to reviewing the PR :)

**Comment by erozenfeld** [comment]
This was implemented in #326.
