### ISSUE TITLE
Deterministic output?

### ISSUE THREAD

**Issue by plynkus** [jbevain/cecil#316]
Greetings!

(Looking at the source presently, but firing off an issue due to observations in local testing in case someone has some quick insight.)

Roslyn has seen the introduction of one or more opt-in fixes for assembly/PDB determinism.  E.g., /deterministic via command line, <Deterministic>true</Deterministic> in a .csproj property group driving the former.  There looks to be at least one unsupported fix (/feature:pdb-path-determinism) for eliminating absolute path differences from being an issue as well.  There may be others.

I find that I do get deterministic assemblies with the .csproj property added.   Unfortunately, by performing some minor IL weaving in a post-build step via Cecil, this determinism is destroyed on rewrite.

Are there plans for a mechanism (an option on WriteParameters, for instance) that tracks the opt-in determinism behaviors of the primary toolchain?

Many thanks!

**Comment by jbevain** [comment]
There's definitely a plan! I love the idea of having deterministic output. It will likely be an argument to pass to WriterParameters. There's a few things that are not deterministic, mainly the module ID if we regen it, and the timestamps in the PE file.

**Comment by plynkus** [comment]
Thanks for the heads up.  I've locally introduced a determinism opt-in bool to honor the original image timestamp (enough for my initial purposes).  Haven't run into module ID, path or other issues as of yet.

**Comment by jbevain** [comment]
Let's track that in #76 which predates this.
