### ISSUE TITLE
Cannot edit a PPDB's timestamp

### ISSUE THREAD

**Issue by 6A** [jbevain/cecil#318]
When writing symbols with the [`PortablePdbWriter`](https://github.com/jbevain/cecil/blob/master/Mono.Cecil.Cil/PortablePdb.cs#L167), it would be nice to control the [time stamp that is written](https://github.com/jbevain/cecil/blob/master/Mono.Cecil.Cil/PortablePdb.cs#L267), in order to please Visual Studio and other debugging tools.

I can take care of it, I'd just like to know if you'd like me to, or if there is an important design choice behind using the [current time](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/AssemblyWriter.cs#L869).

**Comment by jbevain** [comment]
That makes sense. This is also tied to #76. I'll track the work there. Thanks!

**Comment by jbevain** [comment]
@6A we've just added a way to control the module's timestamp. Do you need a way to control the portable pdb timestamp independently?

**Comment by 6A** [comment]
@jbevain Thanks! No, I think controlling the module's timestamp as a whole is enough.
