### ISSUE TITLE
What is "Rock"?

### ISSUE THREAD

**Issue by CreateAndInject** [jbevain/cecil#319]
1.There is a namespace "Mono.Cecil.Rocks", and so many types named ....Rocks

But what's the meaning of rock? I am from China.

rock = stone ?

2.Why not move these extensions to the original types?
I usually use SimplifyMacros/FindOrCreateStaticConstructor/MakePointerType... in dnlib, but I don't know cecil has these functions so many years! That's because most of people just use these two namespace:
Mono.Cecil/Mono.Cecil.Cil. If moving these functions to the original types, I can fint it long long ago.

**Comment by lextm** [comment]
https://github.com/jbevain/cecil/wiki/Mono.Cecil.Rocks

It is already answered why a separate namespace.

About why the term "rocks" is chosen, @jbevain might shed some light. My personal understanding is that it means “Mono Cecil rocks” (Mono Cecil is cool), similar to https://answers.yahoo.com/question/index?qid=20081104200051AAsoS89.
