### ISSUE TITLE
Locked Target Assembly with Mono.Cecil and PCL Code Injection

### ISSUE THREAD

**Issue by ameyasubhedar** [jbevain/cecil#321]
I have a solution structure as follows:

**CoreSolution**
|
+---- Core.dll (PCL)
 This contains CodeInjectionLogic (Inserts IL instruction on each type using Mono.Cecil for PCL)

**BuildSolution**
|
+---- Core.dll  (For Project Reference)
|     
+---- CustomMSBuildTask.dll  (Injects the code into the target.dll)
 This contains CodeInjectionTask which applies CodeInjectionLogic on each target Type to weave IL instruction

 **TargetSolution**
 |
 +---- Core.dll  (For Project Reference)
 |
 +---- Target.dll (PCL)
Defines  using Task CodeInjectionTask in the csproj file

The locking issue for CustomMSBuildTask.dll is solved by copying all dlls on a temporary director as a BeforeBuild event.

Building TargetSolution which contains the Target assembly and using Mono.Cecil I am able to read the Target.dll modify the types and insert the IL instruction but when I try to write the modified stream back using Mono.Cecil.AssemblyDefiniyion.Write() I always get an error from MSBuild

**The process cannot access Target.dll because it is being used by another process. Which I assume is the MSBuild itself.**

Any pointers on how can I use Mono.Ceeil and PCL to weave a target assembly that is being built using custom MSBuild AfterBuild target.

**Comment by jbevain** [comment]
Which version of Mono.Cecil are you using?

If you're using 0.10, Cecil handles file handles differently from 0.9. If you're reading and writing to the same file, you need to use:

```csharp
// ReaderParameters { ReadWrite = true } is necessary to later write the file
using (var module = ModuleDefinition.ReadModule(file, new ReaderParameters { ReadWrite = true })) 
{
    // Modify the assembly

    module.Write (); // Write to the same file that was used to open the file
}
```

See [Cecil 0.10](http://cecil.pe/post/149243207656/mono-cecil-010-beta-1)

**Comment by ameyasubhedar** [comment]
Yes, I updated to 0.10 Cecil.

Thanks a lot. The code is now working based on your suggestions.

**Comment by jbevain** [comment]
Good to hear!

**Comment by ameyasubhedar** [comment]
@jbevain 

I need your advice on another issue with the same solution structure as above, so thought of asking in the same thread. Let me know if you need more details move this to a separate issue. I am sure I am missing something here.

The build is good now but while writing even after importing the reference I still get an error System.Argument Member ObjFactory.OnObjCreated is declared in another module and needs to be imported

Here is the pseudo code

**Core.dll**
+ static class ObjCreator
   + OnObjCreated  
+ class AdviceData : inherits object
      + Assembly CoreNetReflectionAssembly  (Property)
      + AssemblyDefinition CoreMonoAssembly (Property)   
      + TypeDefinition TargetMonoType (Property)
+   TestAttribute (System.Attribute)
+   TestAttributeAdvice  : inherits object
      + Method Inject (AdviceData d)
          + MethodReference insertMethod =  CoreMonoAssembly.MainModule.Method to insert  (e.g. ObjCreator.OnObjCreated)
          + _MethodReference importInsert = d.TargetMonoType.Module.ImportReference(OnObjCreated)_
          + MethodDefinition def = importInsert.Resolve()
          + Inject the def in constructor of d.TargetMonoType                    

**CustomMSBuildTask.dll**
+ Class AspectBasedInjectionTask
    + Get the perpetual core mono assembly
        + DefaultAssemblyResolver resolver = new DefaultAssemblyResolver();
            resolver.AddSearchDirectory(BuildPath);
        +  var CoreMonoAssem = AssemblyDefinition.ReadAssembly(CoreNET.Location, new ReaderParameters { ReadSymbols = IsDebug, AssemblyResolver = resolver });
            var TargetMono = AssemblyDefinition.ReadAssembly(TargetAssemblyPath, new ReaderParameters { AssemblyResolver = resolver, ReadWrite = true });
       + Find all the types in TargetMono that have TestAttribute applied
       + For Each Type 
           + TestAttributeAdvice.Inject (data)           

**Target.dll**
+ <usign task AspectBasedInjectionTask.... (in csproj) AfterBuild

Even after importing the method write assembly is failing with an error...

Could you provide a pointer as to what am I doing wrong?

**Comment by jbevain** [comment]
>           + MethodReference importInsert = d.TargetMonoType.Module.ImportReference(OnObjCreated)
>           + MethodDefinition def = importInsert.Resolve()
>           + Inject the def in constructor of d.TargetMonoType

This sequence looks wrong.

You import a reference to use a method into your module. Then you resolve it into its original definition (the reverse of importing), and use that definition in your module. So you are effectively using a method from another module into your module.

**Comment by ameyasubhedar** [comment]
Thanks a lot for the pointer. Fixed the issue.

So the mistake that I was doing was instead of passing the reference to the IL instruction I was resolving it and then passing the definition.

Resolve should be done at the module that consumes the reference.
