### ISSUE TITLE
Error resolving `System.Int32` on a .NET Core assembly

### ISSUE THREAD

**Issue by joelmartinez** [jbevain/cecil#329]
I'm using Mono.Cecil (via submodule, this commit currently: [272feac](https://github.com/mono/cecil/tree/272feac16778a07efc32096eea07fe6db82575f2) ), and encountering the following error when trying to resolve `System.Int32`.

```
System.NotSupportedException: Specified method is not supported.
  at Mono.Cecil.PE.ImageReader.ReadArchitecture () [0x00040] in <6f5dcfb43b83409e9bb6016a08899100>:0 
  at Mono.Cecil.PE.ImageReader.ReadImage () [0x0005c] in <6f5dcfb43b83409e9bb6016a08899100>:0 
  at Mono.Cecil.PE.ImageReader.ReadImage (Mono.Disposable`1[T] stream, System.String file_name) [0x00008] in <6f5dcfb43b83409e9bb6016a08899100>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00006] in <6f5dcfb43b83409e9bb6016a08899100>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006f] in <6f5dcfb43b83409e9bb6016a08899100>:0 
```

The assembly in question was built via `dotnet new classlib` ... so it's the default template. It was created with `1.0.0-rc4-004771`. And I'm adding `assemblyResolver.AddSearchDirectory ("/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/")`.

At this stage, mainly trying to figure out if this is an issue on my end (should I be using another, special resolver?), or an issue in Mono.Cecil's support for .net core. Any guidance would be appreciated :)

**Comment by jbevain** [comment]
Hey! Thanks for reporting this! Could you upload somewhere or email me the offending binary?

**Comment by joelmartinez** [comment]
@jbevain I've zipped up the whole project (along with obj/bin dirs) here: [core.zip](https://github.com/jbevain/cecil/files/780916/core.zip). Thanks!

**Comment by jbevain** [comment]
So core.dll isn't the problem. It's possible the assembly resolver is failing to read a native file.

**Comment by jbevain** [comment]
I don't think I have enough to help you here :)

The exception shows that Cecil fails to read an assembly, not recognizing its header. If it's core.dll, I can't repro. If it's another file from `/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/` then it could be a non managed .dll (but why would you have a dll on unix?).

**Comment by joelmartinez** [comment]
@jbevain ok, let me come up with a more concise test case. I will post again in this GH Issue when I have it (probably tomorrow, though). Thanks for looking into it :)

**Comment by jbevain** [comment]
Sounds good. Thanks!

**Comment by joelmartinez** [comment]
Hmm ... ok, so I've been unable to reproduce the issue in a standalone/targeted solution. In fact, I haven't even needed to add the search directory to the resolver ... where I get an error about being unable to resolve `System.Runtime` in my regular project.

The test I'm using is against the same core .dll (though I added a method to the class with strings and ints)

```csharp
			ModuleDefinition module = ModuleDefinition.ReadModule ("core.dll");

			foreach (var type in module.Types)
			{
				Console.WriteLine ($"type: {type.Name}");

				foreach (var meth in type.Methods)
				{
					Console.WriteLine ($"\tmethod: {meth.FullName} returns: {meth.ReturnType?.Resolve()?.FullName}");

					foreach (var p in meth.Parameters)
					{
						Console.WriteLine ($"\t\tparam: {p.Name} {p.ParameterType.FullName}");
						var p2 = p.Resolve ();
					}
				}
			}
```

Must be something about the way I'm using Mono.Cecil. For the time being I'm going to close this gh issue, until I can track down a better repro case (or otherwise fix the issue on my end). Thanks again for taking the time to look into it!

**Comment by joelmartinez** [comment]
Can confirm that the resolution to https://github.com/jbevain/cecil/commit/bb40c2108ecf303691d0536c4f9d3b9035790c5c resolves this issue (once I finally got around to creating a repro case) :)

**Comment by jbevain** [comment]
I'm like 99% sure it's this issue yes :)
