### ISSUE TITLE
Custom attribute constructor argument of type System.Type resolves with wrong MetadataType

### ISSUE THREAD

**Issue by mkacz91** [jbevain/cecil#332]
This error occurs when processing the following simple library:

    using System;
    
    namespace CecilAttribute
    {
        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        public class FooAttribute : Attribute
        {
            public Type Value { get; }
            public FooAttribute(Type value) { Value = value; }
        }
    
        public struct Bar { }
    
        [Foo(typeof(Bar))]
        [Foo(typeof(Guid))]
        public class Qux { }
    }

The `Foo` attribute's constructor has a single parameter of type `System.Type`. It is used twice on the type `Qux`: once with a local struct `Bar` and once with another struct, `System.Guid`, coming from a foreign assembly.

When those custom attributes are processed, Cecil exposes the constructor argument values as `TypeReference`. The `MetadataType` property in both cases should be `ValueType`, but the foreign type comes with value `Class`. Below is a simple program that demonstrates it.

    using System;
    using System.Linq;
    using Mono.Cecil;

    namespace CecilAttributeProgram
    {
        class Program
        {
            static void Main(string[] args)
            {
                var module = ModuleDefinition.ReadModule("CecilAttribute.dll");
                var type = module.Types.First(t => t.Name == "Qux");
                foreach (var attribute in type.CustomAttributes)
                {
                    var value = (TypeReference)attribute.ConstructorArguments[0].Value;
                    Console.WriteLine($"{value.Name}: {value.MetadataType}");
                }
                Console.ReadKey();
            }
        }
    }

The output on my machine is

    Bar: ValueType
    Guid: Class

**Comment by jbevain** [comment]
Thanks for reporting this.

Yeah I see. The problem is that the «valuetypeness» of a type isn't saved in a assembly. Cecil will try to guess it if it's used as a valuetype somewhere in the assembly, but if you want to be sure 100%, you'll need to resolve the TypeReference to a TypeDefinition and check that.

Unfortunately there's not much Cecil can do here.
