### ISSUE TITLE
ReadArchitecture() fails on .NET Core assembly

### ISSUE THREAD

**Issue by sbomer** [jbevain/cecil#337]
This looks similar to [329](https://github.com/jbevain/cecil/issues/329).

I get this stacktrace:
```
Unhandled Exception: System.NotSupportedException: Specified method is not supported.
   at Mono.Cecil.PE.ImageReader.ReadArchitecture()
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at ceciltest.Program.Main(String[] args)
```

**Repro steps**

[ceciltest.tar.gz](https://github.com/jbevain/cecil/files/800306/ceciltest.tar.gz)
`dotnet restore`
`dotnet run`

**Other info**
This version of System.Runtime.dll came from `/home/sven/bin/shared/Microsoft.NETCore.App/1.1.1/System.Runtime.dll`.

dotnet cli version info:
```
sven@sven-ubuntu-16:~/ceciltest$ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004842)

Product Information:
 Version:            1.0.0-rc4-004842
 Commit SHA-1 hash:  7238b3efa2

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/bin/sdk/1.0.0-rc4-004842

```

**Comment by jbevain** [comment]
Could you send me this particular System.Runtime.dll?

**Comment by jbevain** [comment]
@sbomer we need to find out why on earth this PE file has 0xfd1d for architecture.

**Comment by jbevain** [comment]
Well I guess this explains it:

https://github.com/dotnet/coreclr/blob/6f7aa7967c607b8c667518314ab937c0d7547025/src/inc/pedecoder.h#L94-L107

0xfd1d is IMAGE_FILE_MACHINE_ARM64 ^IMAGE_FILE_MACHINE_NATIVE_OS_OVERRIDE

Where IMAGE_FILE_MACHINE_NATIVE_OS_OVERRIDE is defined for Linux.

**Comment by sbomer** [comment]
Wow, thanks for the fast response and fix!
