### ISSUE TITLE
Cache method bodies for small methods

### ISSUE THREAD

**Issue by erozenfeld** [jbevain/cecil#341]
Roslyn has an optimization that reuses identical method bodies for small methods:
https://github.com/dotnet/roslyn/blob/91ee274439b6cbed8dbc42dccf3b737305652434/src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs#L2875

This can be ported to Cecil.

Also I noticed that all method bodies are 4-byte aligned; that's only required for method bodies with fat headers, tiny method bodies don't have to be aligned.

**Comment by erozenfeld** [comment]
I have this optimization implemented. Will PR after some cleanup.

**Comment by jbevain** [comment]
Fixed by #343.
