### ISSUE TITLE
Inserting instruction causes InvalidProgramException

### ISSUE THREAD

**Issue by marko-vasic** [jbevain/cecil#365]
When I insert instructions in a method I get InvalidProgramException,
problem is that offset of relative jumps exceeds allowed limit.

In particular, there are brtrue_s surrounding the place where I am inserting instruction,
brtrue_s is a short form of a jump that accepts 1 byte as offset.
Since Mono.Cecil already resolves problem of changing jump addresses when instrumenting,
I was thinking that it can also resolve this case, by converting short jump form to long,
e.g. brtrue_s to brtrue.
What do you think?

note: It was extremely hard to debug it.

**Comment by jbevain** [comment]
That's a fairly common issue. Basically right now Cecil will happily generate the IL stream you provide, and if it overflows, well it overflows :)

The way to fix this right now is to call:

```csharp
using Mono.Cecil.Rocks;

method.Body.SimplifyMacros ();

// do IL modifications

method.Body.OptimizeMacros ();
```

SimplifyMacros will transform all br_s into br, and OptimizeMacros will turn br into br_s if possible.

**Comment by marko-vasic** [comment]
Thanks for the prompt reply.

I was in dilemma whether this is an issue or not.
The reason why I posted it as an issue is because Cecil
is currently automatically fixing branch offsets when inserting instructions in a middle, 
so I thought it might should do the same for offset overflows.

Where should I in future send questions like this?

**Comment by jbevain** [comment]
We use the [Mono.Cecil Google Group](https://groups.google.com/forum/#!forum/mono-cecil).
