### ISSUE TITLE
Trying to run a rewritten dll comes up with fatal error about missing hostpolicy.dll

### ISSUE THREAD

**Issue by CameronAavik** [jbevain/cecil#366]
I've created a repo which I can use to reproduce the issue here https://github.com/CameronAavik/Cecil-Repro

Steps to reproduce:
1. clone, open the .sln in VS2017
2. build all
3. Run the rewriter project
4. Go to the Target's output directory
5. Run `dotnet Target2.dll`

Expected: Hello World printed to console
Actual: I get the following error printed to my console
> A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\Projects\Cecil-Repro\Target\bin\Debug\netcoreapp1.1'.

Please note that the launchSettings.json in the Rewriter specifies the default arguments used when running:
`$(SolutionDir)Target\\bin\\Debug\\netcoreapp1.1\\Target.dll $(SolutionDir)Target\\bin\\Debug\\netcoreapp1.1\\Target2.dll`

You should also see that it is using 0.10.0-beta4 which includes the fix you made for #312 that has some similarities to my issue.

**Comment by jbevain** [comment]
Thanks for providing a repro, I'll look into it.

**Comment by jbevain** [comment]
I don't think that's related to Cecil. If you copy Target.dll to Target2.dll without processing it with Cecil, and try to dotnet Target2.dll, you'll get the same error.

If I replace the freshly compiled Target.dll by a rewritten Target.dll, I get a hello world.
