### ISSUE TITLE
AssemblyDefinition.Write fails in Unity 5.6

### ISSUE THREAD

**Issue by SL1-Kabutak** [jbevain/cecil#371]
I was testing out using Cecil to modify some assemblies for a project. It was working fine in my tests, but upon importing it to Unity 5.6 it now fails.

The line in Unity is:
`assemblyDefinition.Write(ms, new Mono.Cecil.WriterParameters() { WriteSymbols = true });`

The error is different depending on if I'm using one of the 0.9 series stable builds, or the new beta releases. However it is roughly the same call stack regardless.

New versions:

> InvalidOperationException: Operation is not valid due to the current state of the object
> Mono.Cecil.Cil.DefaultSymbolWriterProvider.GetSymbolWriter (Mono.Cecil.ModuleDefinition module, System.String fileName)
> Mono.Cecil.ModuleWriter.GetSymbolWriter (Mono.Cecil.ModuleDefinition module, System.String fq_name, ISymbolWriterProvider symbol_writer_provider, Mono.Cecil.WriterParameters parameters)
> Mono.Cecil.ModuleWriter.WriteModuleTo (Mono.Cecil.ModuleDefinition module, Disposable`1 stream, Mono.Cecil.WriterParameters parameters)
> Mono.Cecil.ModuleDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
> Mono.Cecil.AssemblyDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)

Old/Stable version:

> InvalidCastException: Cannot cast from source type to destination type.
> Mono.Cecil.Cil.SymbolProvider.GetPlatformWriterProvider ()
> Mono.Cecil.ModuleWriter.WriteModuleTo (Mono.Cecil.ModuleDefinition module, System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
> Mono.Cecil.ModuleDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
> Mono.Cecil.AssemblyDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)

I am not sure what has changed in Unity 5.6 that causes this issue, but I figured it would be important to bring it up. Maybe it's an easy fix, maybe I just need to do something else now to fix it.

**Comment by jbevain** [comment]
It means that Cecil fails to load either Mono.Cecil.Pdb.dll or Mono.Cecil.Mdb.dll to handle those forms of debug symbols. Are you sure you're deploying them correctly along with Mono.Cecil.dll?

Another thing to look at is that Unity ships and loads its own Mono.Cecil, so you might be hitting a conflict here.

I don't think that's a Cecil bug here, but likely more an environmental issue.

**Comment by SL1-Kabutak** [comment]
I'll look into it tomorrow morning and reply here. Hopefully it is that simple to solve. It doesn't seem possible to access Unity's Mono.Cecil, so the external .dll is necessary. I'll double check that everything is set up properly. Just struck me as odd since it worked in previous versions of Unity.

**Comment by SL1-Kabutak** [comment]
It seems that the problem has been solved by rebuilding and adding a new copy of the main .dll, mdb.dll and pdb.dll. I'm not sure why it worked in one version and failed in the next, but it seems to be working now. 

Thanks for the insight, I'll close this off. Sorry about that!
