### ISSUE TITLE
Support not putting the full path to the pdb in assemblies

### ISSUE THREAD

**Issue by rolfbjarne** [jbevain/cecil#372]
Cecil writes the full path to the pdb here: https://github.com/jbevain/cecil/blob/7297b51/Mono.Cecil.Cil/PortablePdb.cs#L304

Supporting a way to only write the filename would fix this: https://bugzilla.xamarin.com/show_bug.cgi?id=54578

Roslyn has a similar issue: https://github.com/dotnet/roslyn/issues/9813

**Comment by jbevain** [comment]
Fixed by #380.
