### ISSUE TITLE
Wrong output of FullName property for TypeDefinitions representing nested types

### ISSUE THREAD

**Issue by ChristopherVB** [jbevain/cecil#374]
When retrieving the FullName property of a TypeDefinition for a nested type, the seperator char for parent and child class is a '/' instead of a '+'.

Reflection API uses the '+' instead.

![full-name-bugged](https://cloud.githubusercontent.com/assets/16366149/24838455/7ed4e4c4-1d48-11e7-83a9-8f6791c05561.PNG)

**Comment by ChristopherVB** [comment]
Changing separator char '/' to '+' in TypeReference.cs line 178 should fix it.

**Comment by jbevain** [comment]
See #150 :)
