### ISSUE TITLE
Expose module Timestamp

### ISSUE THREAD

**Issue by KirillOsenkov** [jbevain/cecil#376]
I see the `PE.Image` has a `Timestamp` but it's internal. Do you have plans to expose it?

**Comment by jbevain** [comment]
Maybe? No one asked for it so far.

**Comment by KirillOsenkov** [comment]
Yeah, I think MVID is better for all intents and purposes. Your call :)

**Comment by jbevain** [comment]
Closing for now until we have an actual use case :)
