### ISSUE TITLE
ModuleDefinition.FileName is empty string

### ISSUE THREAD

**Issue by jim-laberge** [jbevain/cecil#382]
On the current post on the master branch, at line 1095 of ModuleDefinition.cs, we have:

		public static ModuleDefinition ReadModule (Stream stream, ReaderParameters parameters)
		{
			Mixin.CheckStream (stream);
			Mixin.CheckReadSeek (stream);

			return ReadModule (Disposable.NotOwned (stream), "", parameters);
		}

Should not the "" be stream.Name?   It is currently filled with the value I need.

Jim

**Comment by jim-laberge** [comment]
OK, not stream.Name (which I could see in the debugger), but stream.GetFileName() extension method.  I did this and my code is working again.

**Comment by jbevain** [comment]
@jim-laberge hey Jim, thanks for reporting this.

What you describe indeed makes sense but I'm curious as to what breaks you. Ideally I'd want a failing scenario for the suite and avoid regressing here. Could you provide details of what you're doing?

**Comment by jbevain** [comment]
Will be addressed in #383.

**Comment by jbevain** [comment]
Thanks for reporting this!

**Comment by jim-laberge** [comment]
Sure.   I am doing a Microsoft "Object Browser" on steroids.   I did not know you guys were going to address the memory footprint, so I had already started some light-weight caching using SQLite.   I am using the absolute path of a module as a primary key, and I also key off of file last modified time and file size to see if I need to re-cache.


So, I need ModuleDefinition to be able to proffer a filename as a key.    I am not done yet, but I am almost seeing a 10-fold drop in memory by implementing using ( AssemblyDefinition ad = xxxxRead() ) patterns.


Cecil rocks!  [😊]   Thank you.


Jim


________________________________

**Comment by jim-laberge** [comment]
I was rushing out the door this morning to get my winter tires changed to summer (hazard of Canada mountain driving), and I realize I might not have answered your question as well as I could have.


I have made a conscious decision to use the master branch and not the stable branch, so I chase changes to Interfaces implementations, and appreciate the [Obsolete] attribute on ModuleDefinition.FullyQualifiedName.   I am a heavy user of the read-only side of your reflection, that is, the structure of types.   Later I hope to dig into method bodies.   I do not inject code or create assemblies.


I am happy to chase changes you and your colleagues make as .NET changes.   Thanks for such a fantastic .NET library.   So many people pick it over Microsoft's reflection.


Best regards,

    Jim


________________________________

**Comment by jbevain** [comment]
Hi Jim,

Enjoy the summer in the Canada mountains!

Thanks for the details, originally I was just fishing for a scenario I could extract a test case from, but managed to do that on my own in the PR.

Don't hesitate to get in touch if you face any other issue!

Jb
