### ISSUE TITLE
VariableDefinition and Name property

### ISSUE THREAD

**Issue by reflection-emit** [jbevain/cecil#386]
Can we have a Name property in the VariableDefinition type again please. This is very handy in certain situations. The names can be random initially, but it should keep the names we set while modifying the assembly. Identifying the variables by index is not possible sometimes.
<br/>
Imagine you have a program that adds different things to multiple methods. On the first run it adds a local variable named "result". In method A the index is 2, in method B the index is 6 and in method C the index is 4. On the second run of the program adds something else to these methods which also uses the "result" variable. If the VariableDefinition has a name property it would be easy to identify and reuse the variable. With only the index available it is not very straight forward. You have to have a separate dictionary for every method which you have to refresh every time you remove or insert a new variable.

**Comment by jbevain** [comment]
Unfortunately, there's no plan to add back a `string Name` property on `VariableDefinition`. The reason is that Cecil provides you with a view of the metadata, and from the metadata perspective, one VariableDefinition can have different names in different IL scopes.
