### ISSUE TITLE
Support writing pure IL for ready-to-run mixed-mode assemblies.

### ISSUE THREAD

**Issue by sbomer** [jbevain/cecil#390]
Since the netcoreapp packages are starting to ship with crossgen'd ready-to-run images, we need the [linker](https://github.com/mono/linker) to be able to work with R2R images. We'd like to be able to write back pure IL assemblies for linked R2R images.

Currently that doesn't work because of the check in [ModuleWriter.Write](https://github.com/jbevain/cecil/blob/007b6dcaaf5c52bb5b3efa658ba63b2aa5de2d2d/Mono.Cecil/AssemblyWriter.cs#L83):
```
if ((module.Attributes & ModuleAttributes.ILOnly) == 0)
	throw new NotSupportedException ("Writing mixed-mode assemblies is not supported");
```

If I work around that by setting ModuleAttributes.ILOnly from the linker, I hit the following:

```
System.NotSupportedException: Specified method is not supported.
   at Mono.Cecil.PE.ImageWriter.GetMachine()
   at Mono.Cecil.PE.ImageWriter.WritePEFileHeader()
   at Mono.Cecil.PE.ImageWriter.WriteImage()
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
```

This is because the machine field in the COFF header is set to `0xfd1d`, which isn't recognized by cecil. [GetMachine()](https://github.com/jbevain/cecil/blob/bbe18d77b98746bbc0057d91693760f76b0735d3/Mono.Cecil.PE/ImageWriter.cs#L214) doesn't recognize it as a valid [TargetArchitecture](https://github.com/jbevain/cecil/blob/bbe18d77b98746bbc0057d91693760f76b0735d3/Mono.Cecil/ModuleKind.cs#L28).

Crossgen writes this to the COFF header in [zapwriter.cpp](https://github.com/dotnet/coreclr/blob/1ff9062d235630a3a47bffa6459549c669432c4a/src/zap/zapwriter.cpp#L467) using [GetMachine()](https://github.com/dotnet/coreclr/blob/1ff9062d235630a3a47bffa6459549c669432c4a/src/zap/zapwriter.h#L322), which returns [IMAGE_FILE_MACHINE_NATIVE_NI](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/inc/pedecoder.h#L107),  an xor of the normal enum values with os-specific override values.

I can get cecil to output IL images for my R2R inputs with two hacks:
- add `AMD64R2R = 0xfd1d` to [TargetArchitecture](https://github.com/jbevain/cecil/blob/bbe18d77b98746bbc0057d91693760f76b0735d3/Mono.Cecil/ModuleKind.cs#L28)
- add the following case to [GetMachine()](https://github.com/jbevain/cecil/blob/bbe18d77b98746bbc0057d91693760f76b0735d3/Mono.Cecil.PE/ImageWriter.cs#L214):
```
case TargetArchitecture.AMD64R2R:
	return 0x8664;
```

So it seems that this is fairly easy to implement - we'd just need to make sure we cover all of the cases for [IMAGE_FILE_MACHINE_NATIVE_NI](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/inc/pedecoder.h#L107) instead of hard-coding it like I did for linux/x64, and we'd need to decide how to make this option available in cecil.

@jbevain, what do you think?

/cc @swaroop-sridhar, @russellhadley

**Comment by jbevain** [comment]
Two different things here.

1. ImageWriter.GetMachine is a relict from the time TargetArchitecture was an enum bot based in IMAGE_FILE_MACHINE_. Nowadays, the Machine field of the IMAGE_FILE_HEADER is read and cast to TargetArchitecture. We should just write the TargetArchitecture as the Machine field.

2. If you're reading a mixed mode assembly and writing it back as ILOnly, that's on you to:

  * change the module attributes to ILOnly
  * set the Module TargetArchitecture to something that makes sense based on the assembly you're reading. In your case, map the AMD64something to AMD64.

**Comment by sbomer** [comment]
I made the quick fix you suggested in 1: https://github.com/jbevain/cecil/pull/391.

Regarding 2:
Just to be clear, you're suggesting that this should be handled in the linker, and that you don't want cecil to contain knowledge of the R2R values from the COFF header, correct? If so feel free to close this and I'll try what you suggested.

**Comment by jbevain** [comment]
1. Thanks

2. The logic you suggest adding in the PR is specific to your use case, so yes, I think it's better handled on your side of thing.
