### ISSUE TITLE
Release non-beta nuget

### ISSUE THREAD

**Issue by haf** [jbevain/cecil#398]
Hi @jbevain – it would be great if you could release a non-prerelease for .Net Core, so that I can release Expecto v5 https://github.com/haf/expecto/issues/165

**Comment by jbevain** [comment]
Hey, what prevents you to release it with a reference to a 0.10 beta?

**Comment by haf** [comment]
Nuget bugs, see link.

**Comment by SimonCropp** [comment]
If expecto doesn't expose Cecil types on its API surface then I would recommend ilmerge instead

**Comment by jbevain** [comment]
That's indeed a good workaround.

**Comment by SimonCropp** [comment]
@haf if u need any help i could submit a PR

**Comment by haf** [comment]
ILMerge doesn't work cross platform in my experience.

**Comment by haf** [comment]
I should also tell you that me and Enrico have implemented a workaround that makes it possible to build nugets again.

**Comment by SimonCropp** [comment]
for the few cases that ilmerge has not worked i have found https://github.com/gluck/il-repack to work

**Comment by matthid** [comment]
What's missing for a stable release?

**Comment by haf** [comment]
Closing because I've worked around this issue.
