### ISSUE TITLE
IL Generated is incompatible with MS ILAsm

### ISSUE THREAD

**Issue by pjbgf** [jbevain/cecil#403]
Trying to reassemble an IL file using MS ILAsm leads to the error below:
` error : syntax error at token 'System.Void' in:     IL_0006: call System.Void System.Console::WriteLine(System.String)`

The IL was generated by Instruction.ToString():
```
    IL_0000: nop
    IL_0001: ldarg.0
    IL_0002: ldnull
    IL_0003: call System.Void dotnet_ildasm.Sample.Classes.PublicClass::PublicVoidMethodSingleParameter(System.String)
    IL_0008: nop
    IL_0009: ret
```

Notice that *System.Void* is an external type that is neither referenced by its CIL form *void* nor prefixed with the external assembly name *[System.Runtime]System.Void* - as supported by MS ILAsm.

Is this by design? I am assuming the format generated is to support mono's version of ILAsm, is that correct?

The same IL generated by MS ILDasm:
```
    IL_0000:  nop
    IL_0001:  ldarg.0
    IL_0002:  ldnull
    IL_0003:  call       instance void dotnet_ildasm.Sample.Classes.PublicClass::PublicVoidMethodSingleParameter(string)
    IL_0008:  nop
    IL_0009:  ret
```

**Comment by jbevain** [comment]
Hi there! .ToString() is basically a helper to get a understandable string form for an object. In that case, it's definitely not meant to be valid IL that you can assemble. You'll need to write your own object model to IL printer.

**Comment by jbevain** [comment]
There's super old bit-roted code there that you might find useful:

https://github.com/mono/cecil-old/tree/master/ildasm/Mono.Disassembler

**Comment by pjbgf** [comment]
Thanks, JB, that was really useful.
