### ISSUE TITLE
Source link and embedded source lost when rewriting portable PDB

### ISSUE THREAD

**Issue by bording** [jbevain/cecil#404]
Portable PDBs support both [Source linking](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/source_link.md) and [embedded source](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md#embedded-source-c-and-vb-compilers), however it appears that when Mono.Cecil writes a new PDB, this information is lost.

I've put together a project that reproduces the issue [here](https://github.com/bording/SourceLinkProblem). Running `repro.bat` will show that before the PDB is rewritten, it has source linked information, and that it's gone after Mono.Cecil has been used to write to the PDB.

//cc: @SimonCropp

**Comment by jbevain** [comment]
Thanks for the repro, I'll have a look!

**Comment by jbevain** [comment]
Will be fixed in #405.

**Comment by SimonCropp** [comment]
@jbevain just an FYI i smoke tested this on ~45 scenarios and everything looks good.

@bording i released Fody 2.1.0-beta0001 with this fix. can u verify?
