### ISSUE TITLE
MemoryStream.GetBuffer doesnt exist in netstandard 1.3?

### ISSUE THREAD

**Issue by SimonCropp** [jbevain/cecil#406]
I dont think MemoryStream.GetBuffer exists in 1.3? https://github.com/dotnet/corefx/issues/1897

so here https://github.com/jbevain/cecil/blob/master/Mono.Cecil/AssemblyReader.cs#L3217 i think we need the following
```
#if (NET_CORE)
	ArraySegment<byte> segment;
	if (!decompressed_stream.TryGetBuffer (out segment)) {
		throw new Exception("Could not get buffer from decompressed_stream.");
	}
	byte[] buffer = segment.Array;
#else
	buffer = decompressed_stream.GetBuffer();
#endif
	info = new EmbeddedSourceDebugInformation (buffer, compress: true);
```

or am I missing something?

**Comment by SimonCropp** [comment]
@jbevain want a PR for this?

**Comment by jbevain** [comment]
Fixed to avoid 2 code paths.
