### ISSUE TITLE
Modified release build assemblies can't load their symbols

### ISSUE THREAD

**Issue by cremor** [jbevain/cecil#408]
First let me say that I'm sorry that I can't provide a repro for this issue that just uses Cecil. I know nothing about its usage and found this problem by using [Fody](https://github.com/Fody/Fody). I was redirected here by @SimonCropp when I originally opened this issue in Fody/Fody#350. Accoring to him, Fody performs the same operations in debug and release, so it seems to be an issue in Cecil.

The Cecil version used by Fody at the time I found this issue was 84f6f781ab54820498d32e8ce6a5a5a3f9a80f94 (same as 0.10-beta6 except for the commit that increased the version number). The Cecil version used by Fody 1.29.4, which did **not** have this issue, was 68bcb750b898f4882a5af44299bb322aaa531f93 (somewhere between 0.10-beta1 and 0.10-beta2).

To have everything in one place, here is the issue I reported for Fody:

I found a problem with Fody 2.0 that didn't happen with Fody 1.29.4 and only appears in release builds. It seems like Fody 2 breaks loading PDB files for those builds.

To be more specific, just enabling "optimize code" or changing "debugging information" to "pdb-only" doesn't trigger the problem. It seems to happen when the project file doesn't specify `<DebugSymbols>true</DebugSymbols>`. If you remove this one line from the project file (I don't think there is a GUI element for it), even debug builds are affected.

This has a few effects:

1. (The big one) Exception stack traces won't have any file or line number information in them, which makes debugging exceptions from log files harder.
2. When "Just my code" is enabled, Visual Studio usually shows a dialog that informs the user that debugging optimized assemblies with "Just my code" enabled doesn't work correctly. This dialog is not shown if the assembly was modified by Fody 2.0.
3. If you continue debugging anyway, the output window usually shows "Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.". But for an assembly modified by Fody 2.0 it shows "Module was built without symbols.", which is wrong because the default release build "debugging information" setting "pdb-only" was used.

It seems like it doesn't matter which weaver is used. I reproduced the problem with PropertyChanged.Fody (2.0.1), ConfigureAwait.Fody (1.1.0) and even with BasicFodyAddin.Fody (0.4.0), always using Fody 2.0.10.

To reproduce the problem, create a new console application, paste the following code, add Fody and a weaver and start it in a release build.

```
using System;

namespace FodyReleaseSymbolsTest
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Method1();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
            Console.ReadLine();
        }

        static void Method1()
        {
            Console.WriteLine("in method 1");
            Method2();
        }

        static void Method2()
        {
            Console.WriteLine("in method 2");
            Method3();
        }

        static void Method3()
        {
            Console.WriteLine("in method 3");
            throw new Exception("Test");
        }
    }
}
```

Expected output:
```
in method 1
in method 2
in method 3
System.Exception: Test
   bei FodyReleaseSymbolsTest.Program.Method3() in C:\path\to\Program.cs:Zeile 35.
   bei FodyReleaseSymbolsTest.Program.Method2() in C:\path\to\Program.cs:Zeile 29.
   bei FodyReleaseSymbolsTest.Program.Method1() in C:\path\to\Program.cs:Zeile 23.
   bei FodyReleaseSymbolsTest.Program.Main(String[] args) in C:\path\to\Program.cs:Zeile 11.
```
   
Actual output:
```
in method 1
in method 2
in method 3
System.Exception: Test
   bei FodyReleaseSymbolsTest.Program.Method3()
   bei FodyReleaseSymbolsTest.Program.Method2()
   bei FodyReleaseSymbolsTest.Program.Method1()
   bei FodyReleaseSymbolsTest.Program.Main(String[] args)
```

**Comment by jbevain** [comment]
Hey,

Could you please upload the binary + pdb without weaving and with weaving,
so that I can take a look?

Thanks!

**Comment by cremor** [comment]
Sure. Here is an archive that contains both debug and release binaries and PDBs both with and without modifications from Fody. I've also included the source.

For some reason GitHub won't allow me to attach the zip to this issue, so I've uploaded it [here](http://s000.tinyupload.com/index.php?file_id=98331173699030250269).

**Comment by jbevain** [comment]
Thanks, I'll look into it early next week!

**Comment by SimonCropp** [comment]
@cremor sorry i actually discovered a bug in fody to do with symbols production. can u re-verify on https://www.nuget.org/packages/Fody/2.1.0-beta0002

**Comment by cremor** [comment]
@SimonCropp I've tested it with Fody 2.1.0-beta0003 and it indeed fixes the bug. Thanks!

@jbevain Since this isn't a bug in Cecil after all I'll close this issue.
