### ISSUE TITLE
New source link and embedded sources support not fully working

### ISSUE THREAD

**Issue by bording** [jbevain/cecil#412]
It appears that the source linking and embedded sources support added in #405 might have some problems.

Using the FodyCecil release that incorporates those changes (since beta7 isn't out yet), I tested that my original repro was now working correctly. However, after trying it with a more complex assembly, I'm seeing problems with the resulting PDB.

I've updated my https://github.com/bording/SourceLinkProblem repo to demonstrate what I'm seeing. I've included both embedded source and source-linked versions of the test assembly, because the behavior seems to be slightly different.

The two new batch files, `repro-rabbit-embedded.bat` and `repro-rabbit-sourcelinked.bat` can be used to run the scenarios. I've also included `output-embedded.txt` and `output-sourcelinked.txt` to show the results of running the batch files.

For the embedded assembly, it starts out with 25 embedded files, but after being run through cecil, 8 of the documents have lost their embedded source.

For the source-linked version, the source link json file is missing, so all 25 of the documents no longer have any information.

CC: @SimonCropp

**Comment by jbevain** [comment]
Thanks, I'll have a look!

**Comment by jbevain** [comment]
Hey @bording, the repro are failing for a fresh checkout as the rabbitmq pdb file is missing in the libs directory.

**Comment by bording** [comment]
Oops, sorry about that, the .gitignore file prevented them from being included in the commit and I didn't notice! They should be there now.

**Comment by bording** [comment]
@jbevain Is there anything else I can do to help investigate this?

**Comment by jbevain** [comment]
That's fixed in #432. Thanks for the repro!
