### ISSUE TITLE
nuget package target .net=4.5

### ISSUE THREAD

**Issue by Esardes** [jbevain/cecil#415]
Hope a ticket is a right place for this issue

When I download package v0.9.6 with target .net 4.5 (`Install-Package Mono.Cecil -Version 0.9.6`), I get the warning/runtime error:

> The primary reference "Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".	

Same thing for Mono.Cecil.Pdb/Mdb/Rocks

**Comment by SimonCropp** [comment]
Just an FYI, support for .net 4.5 has ended. https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by jbevain** [comment]
You need to update to 0.10 using the guides provided at http://cecil.pe, this is fixed. Thanks!
