### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by nhanqv** [jbevain/cecil#417]
I have classes as following

    public class EntityClass
    {
        public int IntValue { get; set; }
    }
    
    public class AbstractDao<T>
    {
    
    }
    
    public class DaoClass<T> : AbstractDao<T>
        where T : new()
    {
        public T GetValue()
        {
            return new T();
        }
    }
    
    public class AbstractCommandClass<T, U>
        where T : AbstractDao<U>
        where U : class, new()
    {
        [Log]
        public U GetU()
        {
            DaoClass<U> dao = new DaoClass<U>();
            return dao.GetValue();
        }
    }

    public class CommandClass : AbstractCommandClass<DaoClass<EntityClass>, EntityClass>
    {

    }

And the LogAttribute class

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class LogAttribute : InterceptorAttribute
    {
        public override void OnInvocation(Invocation invocation)
        {
            Console.WriteLine("Begin");
            invocation.Proceed();
            Console.WriteLine("End");
        }
    }

I use Mono.Cecil 0.9.6 to modify assembly.
The AbstractCommandClass after modified look like following:

	public class AbstractCommandClass<T, U> where T : AbstractDao<U> where U : class, new()
	{
		private class GetU_stub
		{
			public static readonly MethodInfo Method;

			public static readonly IInterceptor[] Interceptors;

			public static readonly MethodInvoker Invoker;

			private static object CallOriginal(object obj, object[] array)
			{
				return ((AbstractCommandClass<T, U>)obj).GetU_original();
			}

			private GetU_stub()
			{
			}

			static GetU_stub()
			{
				AbstractCommandClass<T, U>.GetU_stub.Method = methodof(AbstractCommandClass<T, U>.GetU());
				AbstractCommandClass<T, U>.GetU_stub.Interceptors = InterceptorAttribute.GetInterceptorsFor(AbstractCommandClass<T, U>.GetU_stub.Method);
				AbstractCommandClass<T, U>.GetU_stub.Invoker = new MethodInvoker(AbstractCommandClass<T, U>.GetU_stub.CallOriginal);
			}
		}

		[Log]
		public U GetU()
		{
			object[] args = new object[0];
			Invocation invocation = new Invocation(AbstractCommandClass<T, U>.GetU_stub.Interceptors, AbstractCommandClass<T, U>.GetU_stub.Method, AbstractCommandClass<T, U>.GetU_stub.Invoker, this, args);
			invocation.Proceed();
			object result = invocation.Result;
			return StubHelper.Unbox<U>(result);
		}

		public U GetU_original()
		{
			DaoClass<U> daoClass = new DaoClass<U>();
			return daoClass.GetValue();
		}
	}

	public class CommandClass : AbstractCommandClass<DaoClass<EntityClass>, EntityClass>
	{
	}

When I try to call AbstractCommandClass, the following exception has occurred

    System.TypeLoadException: GenericArguments [0] on 'Test.Me.AbstractCommandClass` 2 [T, U]', 'T' violates the constraint of type parameter 'T'.

When I export the above modified AbstractCommandClass to .cs file, build and run using Visual Studio 2015, there is no exception occurred anymore. 

Could you teach me what's going wrong?

**Comment by jbevain** [comment]
I'm afraid I can't debug for you :)

Please provide a self-contained repro.
