### ISSUE TITLE
Q: Strong Naming API on netstandard 2.0?

### ISSUE THREAD

**Issue by matthid** [jbevain/cecil#418]
I noticed that the strong naming capabilities are not available on the netstandard 1.6 build.

Will there be (once netstandard 2.0 is out) a build of mono.cecil supporting this scenario?
Or is this part considered obsolete and not maintained anymore? (Or are users redirected to the full build)

**Comment by jbevain** [comment]
I think .netstandard 2 has the API we need to provide strong naming.

**Comment by jbevain** [comment]
Down the line I don't see why we couldn't have a .netstandard 2.0 build that includes that feature.

**Comment by matthid** [comment]
Thanks
