### ISSUE TITLE
Write overload with only WriteParameters throws exception

### ISSUE THREAD

**Issue by parthopdas** [jbevain/cecil#421]
Here is the repro code:
```csharp
using Mono.Cecil;

namespace Repro1
{
    class Program
    {
        static void Main(string[] args)
        {
            var rp = new ReaderParameters { ReadSymbols = true };
            using (var asmDef = AssemblyDefinition.ReadAssembly(args[0], rp))
            {
                var wp = new WriterParameters { WriteSymbols = true };
                asmDef.Write(wp);
            }
        }
    }
}
```
args[0] can be any .net assembly. Here is the exception it throws:
>Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.
>   at Mono.Cecil.Mixin.CheckWriteSeek(Stream stream)
>   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
>   at Mono.Cecil.ModuleDefinition.Write(WriterParameters parameters)
>   at Mono.Cecil.AssemblyDefinition.Write(WriterParameters parameters)
>   at Repro1.Program.Main(String[] args) in d:\projects\Cecil\Repro1\Program.cs:line 18

**Comment by jbevain** [comment]
You need to pass ReadWrite = true in the ReaderParameters to read and write to the same stream.
Jb
		

		
	





On Sat, Jun 17, 2017 at 5:56 PM -0700, "Partho P. Das" <notifications@github.com> wrote:












Here is the repro code:
using Mono.Cecil;

namespace Repro1
{
    class Program
    {
        static void Main(string[] args)
        {
            var rp = new ReaderParameters { ReadSymbols = true };
            using (var asmDef = AssemblyDefinition.ReadAssembly(args[0], rp))
            {
                var wp = new WriterParameters { WriteSymbols = true };
                asmDef.Write(wp);
            }
        }
    }
}


args[0] can be any .net assembly. Here is the exception it throws:



Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.

at Mono.Cecil.Mixin.CheckWriteSeek(Stream stream)

at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)

at Mono.Cecil.ModuleDefinition.Write(WriterParameters parameters)

at Mono.Cecil.AssemblyDefinition.Write(WriterParameters parameters)

at Repro1.Program.Main(String[] args) in d:\projects\Cecil\Repro1\Program.cs:line 18

**Comment by jbevain** [comment]
You need to pass `ReadWrite = true` in the `ReaderParameters` to read and write to the same stream.

**Comment by parthopdas** [comment]
Spot on! Thanks for the quick response.
