### ISSUE TITLE
GetCorlib throws NotSupportedException while it should not for UWP assemblies

### ISSUE THREAD

**Issue by lextm** [jbevain/cecil#428]
I was digging into an Obfuscar user inquiry and came across this exception,

https://github.com/jbevain/cecil/blob/master/Mono.Cecil/BaseAssemblyResolver.cs#L228

I will try to prepare a small sample to illustrate the issue without Obfuscar so you might later do some debugging.

**Comment by jbevain** [comment]
Hey,

Thanks. Yes, please provide a self contained repro. If it's UWP, it makes
sense that the BaseAssemblyResolver doesn't support resolving UWP .NET Core
assemblies.

Jb

**Comment by lextm** [comment]
Some update on my progress. Different Windows 10 SDK releases seem to have some impact on this. Also VS 2015/2017 have different project structures and results. So how exactly should Mono Cecil/Obfuscar work on the assemblies is still unknown. I ran out of my spare time yesterday but no conclusion yet. I would spend some more time this weekend and get back if there is clearly something we can do about it.

**Comment by jbevain** [comment]
I'm closing this for now. Feel free to re-open with a repro! Thanks!
