### ISSUE TITLE
TypeReference.Resolve returns null on NetCore

### ISSUE THREAD

**Issue by reflection-emit** [jbevain/cecil#433]
I encountered this with the following code:
`this.moduleDefinition.ImportReference(typeof(NotImplementedException)).Resolve()`

This code works fine for UWP and .NET 4.5.2 and higher, but not for NetCore.

Honestly I am not sure if this is a bug in Cecil or I am just missing something in NetCore.

**Comment by jbevain** [comment]
Could very well be related to #306.

**Comment by reflection-emit** [comment]
I tried that solution, but DependencyContext.Default also returns null... So the whole resolver does not work.

**Comment by jbevain** [comment]
Fixed in #444.

**Comment by reflection-emit** [comment]
Yap I can confirm... It works now.
