### ISSUE TITLE
NotSupportedException with UWP Component/Library

### ISSUE THREAD

**Issue by joelmartinez** [jbevain/cecil#434]
I'm receiving a `NotSupportedException` error when I try to use mono.cecil on a universal windows component (.winmd), and it attempts to resolve `System.String`.

To reproduce the issue, I created a new uwp component library with the following simple class:

```csharp
    public sealed class Class1 {
        public string Name { get; set; }
    }
```
Then I created a simple console project, added the Mono.Cecil nuget, and implemented the following code

```csharp
using System;
using Mono.Cecil;

namespace CecilTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string path = "../../../RuntimeComponent1/bin/Debug/RuntimeComponent1.winmd";
            DefaultAssemblyResolver resolver = new DefaultAssemblyResolver();
            resolver.AddSearchDirectory(@"C:\Program Files (x86)\Windows Kits\10");
            AssemblyDefinition component = AssemblyDefinition.ReadAssembly(path, new ReaderParameters { AssemblyResolver = resolver });

            foreach(var module in component.Modules)
            {
                foreach(var type in module.Types)
                {
                    var resolvedType = type.Resolve();
                    Console.WriteLine($"type: {resolvedType.FullName}");
                    foreach(var prop in resolvedType.Properties)
                    {
                        var rprop = prop.Resolve();
                        var rtype = rprop.GetMethod.ReturnType.Resolve();
                        Console.WriteLine($"Property: {rprop.Name}, returns {rtype.FullName}");
                    }
                }
            }
        }
    }
}
```
The following exception is thrown when I try to resolve the property's get method return type (ie. `string`)
```
System.NotSupportedException: Version not supported: 255.255.255.255
   at Mono.Cecil.BaseAssemblyResolver.GetCorlib(AssemblyNameReference reference, ReaderParameters parameters)
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at CecilTest.Program.Main(String[] args) in C:\dev\test\RuntimeComponent1\CecilTest\Program.cs:line 23
```
Specifically, the assembly full name that it's trying to resolve is `mscorlib, Version=255.255.255.255, Culture=neutral, PublicKeyToken=b77a5c561934e089`. Not sure if there's some other search path I should be passing to the resolver, or maybe using something other than the `DefaultAssemblyResolver` entirely? Any advice would be greatly appreciated.

Corresponding issue on my side being tracked here: https://github.com/mono/api-doc-tools/issues/29 :)

**Comment by jbevain** [comment]
The DefaultAssemblyResolver implements a (default) resolver to resolve assemblies for the full .NET Framework. It's not aware of the Windows SDK or other forms of assemblies (.NET Core, Silverlight, etc).

So having this fail is not surprising.

There's no UWP builtin resolver, so you'll need to write your own. You can start with this one, which may be incomplete:

https://github.com/jbevain/cecil/blob/master/Test/Mono.Cecil.Tests/WindowsRuntimeAssemblyResolver.cs

Also, it doesn't look like it will support resolving from mscorlib. There's no actual mscorlib in UWP, so that your assembly resolver will need to special case this and decide what to return.

**Comment by jbevain** [comment]
@joelmartinez I'd rather not have that logic in the DefaultAssemblyResolver for now. There are multiple things at play, you could have different versions of the Windows SDK, I'm not familiar enough with those to add those directly to this relatively core type.

Right now I strongly suggest keeping things separate in another assembly resolver.

**Comment by jbevain** [comment]
I'm going to close this as I don't think this is a really a bug. Feel free to continue our email thread if you have anymore question!
