### ISSUE TITLE
Wrong method types when resolving interface 

### ISSUE THREAD

**Issue by TheNetStriker** [jbevain/cecil#436]
I'am trying to build an application that analyzes assemblies and checks if all interfaces are integrated correctly and I think I found a bug in Cecil. I've created a test assembly containing the following two classes:

```csharp
public class TestClass : IEnumerable<string>
{
	public IEnumerator GetEnumerator()
	{
		throw new NotImplementedException();
	}

	IEnumerator<string> IEnumerable<string>.GetEnumerator()
	{
		throw new NotImplementedException();
	}
}

public class TestClass2 : IEnumerable<int>,
{
	public IEnumerator<int> GetEnumerator()
	{
		throw new NotImplementedException();
	}

	IEnumerator IEnumerable.GetEnumerator()
	{
		throw new NotImplementedException();
	}
}
```

In my application I loop through all modules and Types of this assembly and check if every interface is implemented:

```csharp
AssemblyDefinition assembly = AssemblyDefinition.ReadAssembly(assemblyPath, parameters);

foreach (ModuleDefinition module in assembly.Modules)
{
	foreach (TypeDefinition type in module.Types)
	{
		foreach (InterfaceImplementation ifaceImpl in type.Interfaces)
		{
			TypeReference iface = ifaceImpl.InterfaceType;
			TypeDefinition ifaceDef = iface.Resolve();

			foreach (MethodDefinition ifaceMethod in ifaceDef.Methods)
			{
			}
		}
	}
}
```

When checking the TestClass using this code everything is fine. But when TestClass2 is checked the first ifaceMethod has still System.String as type instead of int32. (The type of the iface TypeReference is correct)

I traced the problem to the TypeDefinitionCollection class. The problem seams to be that the name_cache only contains one "System.Collections.Generic.IEnumerable`1" entry for System.String. I didn't find any entry for the System.Int32 IEnumerable in the name_cache.

Does anyone have an idea what could cause this problem?

**Comment by jbevain** [comment]
I'm not sure I understand what you're describing. In the code you show, if I add a `Console.WriteLine(ifaceMethod)`, I get:

```
System.Collections.Generic.IEnumerator`1<T> System.Collections.Generic.IEnumerable`1::GetEnumerator()
System.Collections.IEnumerator System.Collections.IEnumerable::GetEnumerator()
System.Collections.Generic.IEnumerator`1<T> System.Collections.Generic.IEnumerable`1::GetEnumerator()
System.Collections.IEnumerator System.Collections.IEnumerable::GetEnumerator()
```

Which makes sense, they're method definitions, they're not generic instances.

So what's the problem?

**Comment by TheNetStriker** [comment]
Sorry I forgot to mention a vital part of my application. I'am also using the code from the following GitHub Project to replace the GenericArguments with the effective types used by the current class:
https://gist.github.com/tomspilman/99ddac3b60f72814c6e5

The problem is that this code modifies the cached TypeDefinition itself, so it only works for the first IEnumerable that is loaded. (In this case on the line inst.GenericArguments[i] = genericParent.GenericArguments[param.Position];)

Is there a better way to get a TypeDefinition with resolved generic types without changing the cached one?

**Comment by jbevain** [comment]
Sure, just don't mutate the type. Just return the argument mapping to the position of the parameter.
