### ISSUE TITLE
StrongNameKeyPair property is missing in WriterParameters class in version 1.10.0-beta6

### ISSUE THREAD

**Issue by keeper013** [jbevain/cecil#437]
Is support to strong name going to be removed?

**Comment by SimonCropp** [comment]
isnt it only removed in the netstandard version?

**Comment by keeper013** [comment]
Indeed my project is a netstandard dll, could I ask for the reason to remove it for netstandard version?

**Comment by SimonCropp** [comment]
AFAIK the underlying APIs that the cecil StrongNameKeyPair functionality uses have not yet been ported to netstandard

**Comment by keeper013** [comment]
Thanks for the swift answer.

**Comment by SimonCropp** [comment]
this may have changed in netstandard 2. but i have into looked into it

**Comment by keeper013** [comment]
Hi @jbevain , it seems strong name key is still not supported for NET_CORE, does it mean mono.cecil has no plan to support strong naming for netstandard? Thanks.

**Comment by jbevain** [comment]
Hi @keeper013, right now that is correct.

**Comment by SimonCropp** [comment]
@jbevain is it still not possible in netstandard2?
