### ISSUE TITLE
Error resolving assembly on fileshare

### ISSUE THREAD

**Issue by asbjornu** [jbevain/cecil#438]
I have a command line program that uses Cecil to generate an assembly and when this program is invoked with file share paths (such as `\\Fileshare\Path\To\Project.exe` instead of `Y:\Path\To\Project.exe`), Cecil blows up with the following exception:

```
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'ThirdParty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
     at Mono.Cecil.TypeReference.Resolve()
```

For various reasons, I'm running Visual Studio from a file share, which causes build macros such as `$(SolutionDir)` to point to `\\Fileshare\...` instead of a mapped drive. This makes it very hard to change the UNC paths into locally mapped drives, so I really wish Cecil could work with fileshares out of the box.

After a quick scan of `Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)`, I can't tell exactly what is failing and why fileshares aren't supported, but if there's anything obvious there that will not support fileshares, I'm more than happy to submit a pull request to fix it.

**Comment by jbevain** [comment]
Hey there. Nothing obvious. Have you tried debugging this?

**Comment by jbevain** [comment]
@asbjornu closing this as it's pretty old. Feel free to re-open if you still hit this. Thanks!
