### ISSUE TITLE
Search directories don't search subfolders

### ISSUE THREAD

**Issue by joelmartinez** [jbevain/cecil#441]
The [`BaseAssemblyResolver.SearchDirectory`](https://github.com/jbevain/cecil/blob/7297b51edcb62ffbfdbf50de7006694e12c96633/Mono.Cecil/BaseAssemblyResolver.cs#L156) method only searches for assemblies in the directories explicitly added via `AddSearchDirectory`.

I was wondering if there was an explicit reason that it didn't check all subdirectories? 

The existing code could easily be modified to include all subdirectories with a bit of linq:

```csharp
var dirs = directories
    .Union(directories.SelectMany(d => 
        Directory.GetDirectories(d,".", SearchOption.AllDirectories)))
    .Distinct();
foreach (var directory in dirs) {
```

I wouldn't mind creating a PR with this addition ... but I wanted to check first to see if this wasn't this way for some particular reason. For context, this is for UWP support, to make it easy for users to add the relevant windows sdk directory ... all of the `*.winmd` assemblies are in numerous subfolders of (for example) `C:\Program Files (x86)\Windows Kits\10\References`. It would make it easier to push them into the [pit of success](https://blog.codinghorror.com/falling-into-the-pit-of-success/) if they could just add that one directory and all assemblies would resolve accordingly :)

**Comment by jbevain** [comment]
That would push everyone else in the pit of regression :)

For WinRT, the best path to success would be an assembly resolver for this scenario.

**Comment by joelmartinez** [comment]
Understandable :) I can implement this in my custom resolver
