### ISSUE TITLE
Corrupted TableHeap Reads

### ISSUE THREAD

**Issue by FGS-BMarkham** [jbevain/cecil#443]
Greetings. The bug I am attempting to describe has a lot of context, but I'll try to be succinct. (I'm happy to provide more details as needed, although without extra red tape at my organization I probably can't provide entire input Dlls.)

I have a .NET 4 (4.6.1) Dll that Cecil is failing to load correctly. If I make small code changes and recompile, sometimes Cecil can read the Dll. (It is frustratingly unpredictable.)
By "failing to read", I mean:
 - `Mono.Cecil.AssemblyDefinition.ReadAssembly(…)` populates garbage as early in the read process as `MetadataReader.ReadAssemblyNameDefinition()` (but returns without an exception occuring)
 - `Mono.Cecil.AssemblyDefinition.ReadAssembly(…).MainModule.GetTypes()` fails because because the call to `ReverseNestedTypes.Add(…)` in `SetReverseNestedTypeMapping(…)` is failing because of duplicate keys (clearly garbage data)

By "making small changes" to make it mysteriously work again, I mean generally things that are probably affecting the assembly's metadata, such as:
 - Deleting code that makes use of lambdas (in this case, calls to `Moq` library with lambdas supplied as function expressions, or calls to `AutoFixture`'s various specimen-builder helpers)
 - Deleting entire types (in this case, entire test suite classes containing code like the above)

I tried desperately to whittle the project down to a shareable example case, but at the moment if I delete any types, everything goes back to normal.

I'm encountering this problem via usage of NUnit, which uses Cecil to determine the LCD framework to run tests under. (This is a test project.) The only major recent change to our stack is that we upgraded to the C# 7 compiler. (Yes, I imagine that this could be a C# compiler bug of some kind, but `System.Reflection.Assembly.LoadFile(…)` has no problem with the "broken" variants of this assembly, so I'm stuck trying to pick you folks' brain first.)

The test comparison case I've been working with the most is one wherein I've made a bad variant of the assembly into a good variant by deleting a pair lines of code that resemble the following:
```
  _mockEntitySetA.Verify(x => x.Add(It.Is<EntityTypeA>(y => y.SomeProperty == _localFieldA && y.Property2 == _localFieldB)));
  _mockEntitySetB.Verify(x => x.Add(It.Is<EntityTypeB>(y => y.SomeProperty.SomeProperty == _localFieldA)));
```

Marking these down as my "good" (above code elided) and "bad" (above code included) variants of the assembly, I've spent most of the past 3 days doing a differential debug of Mono.Cecil reading both variants. Like I mentioned earlier, the earliest divergence from expected behavior that I've observed is when `MetadataReader.ReadAssemblyNameDefinition()` is definitely not trying to read the index number of the assembly name from the correct location. Using a hex editor, I was able to determine that the correct reference to the string occurs 3332 bytes past where it is looking. I've tried my best to figure out why it is looking the wrong place, but I'm struggling to discern what it is supposed to be different between the two assemblies versus what might be bad data.

I've got [a shoddy spreadsheet](https://ibb.co/kncw8a) of variables captured (about 25) across different parts of Cecil's code trying to read the assembly, juxtaposing the good input vs. the bad. Let me know if I need to clarify it better.

Additional information:
- Mono's `pedump` yields `* Assertion at metadata.c:886, condition `index < meta->heap_strings.size' not met`
- `pedump --verify all` yields `Error: Invalid typedef row 50 has nested visibility but no rows in the NestedClass table`

Let me know what else you might need to help me hunt this down.

Thanks in advance for any attention or help you can send my way.

**Comment by jbevain** [comment]
Hello !

Well that sounds like it's going to be a fun one.

Really the best way to move forward would be to have access to the offending DLL or a repro of it. We could look into having the DLL under NDA for instance.

One thing you can try to do is to use `dumpbin -all` to see the different parts of the PE, that might give a clue as to what confuses Cecil.

**Comment by FGS-BMarkham** [comment]
I've gotten some local traction about possibly getting you under NDA to take a look. Do you mind if I email you about it?

**Comment by jbevain** [comment]
Shoot!

**Comment by jbevain** [comment]
Closing this until we get more details.
