### ISSUE TITLE
Cli CodeWriter.cs parameter index has issue

### ISSUE THREAD

**Issue by ctemple** [jbevain/cecil#445]
code like this:
...processor.Emit(OpCodes.Ldarg_S, processor.Body.GetParameter(i));
insert code & save & read,Method.Parameters damaged

check for errors

CodeWriter.cs
int GetParameterIndex (ParameterDefinition parameter)
		{
			if (body.method.HasThis) {
				if (parameter == body.this_parameter)
					return 0;

				return parameter.Index + 1; // <<<<<<<---------------
			}

			return parameter.Index;
		}

parameter.Index It's already correct, don't need plus 1
It's not clear that there are other effects

**Comment by jbevain** [comment]
Hello! I'm not sure I understand the issue. Please provide a self-contained repro and re-open.
