### ISSUE TITLE
ILParser.Parse and CodeReader non-reentrancy

### ISSUE THREAD

**Issue by Stevie-O** [jbevain/cecil#446]
Short background: I wrote a tool that uses Cecil to load up one or more .NET assemblies and performs various types of static analysis on them. (It can also make some metadata tweaks and write out an updated version of an assembly.)

It was originally built using whatever version of Cecil was around in February 2015.  When I updated to the latest code, however, the tool failed miserably.

I was able to trace one of the issues back to 8771de6415d3fa5e34b12fd90519a5405c02e8b2 (which, while authored in 2011, was not merged until 628f58c141cdc8eaac5ed9d311ce021b8a533ac7 on 2016-07-14).  It would appear that, prior to this, method bodies were read into memory in real-time and kept there; this commit, however, causes `CodeReader` (and by extension, `ILParser.Parse`) to directly off of the source Stream object.

The result is this: If two threads are trying to use `ILParser.Parse` simultaneously, or if the `IILVisitor` passed to `ILParser.Parse` performs a recursive call into `ILParser.Parse`, the underlying (shared) stream will be positioned in the completely wrong place, causing the parsing to go absolutely haywire.

Additionally, this raises a question: If the original method body was not loaded into memory, how can Cecil save the assembly to a new file without access to the original stream?

**Comment by jbevain** [comment]
Yeah good catch, we need to address that. Thanks for reporting this.

**Comment by jbevain** [comment]
@Stevie-O could you try with the branch `fix-ilparse` that I've pushed?

Thanks!

**Comment by jbevain** [comment]
Should be fixed in #457.
