### ISSUE TITLE
InvalidCastException: Specified cast is not valid

### ISSUE THREAD

**Issue by lextm** [jbevain/cecil#447]
Attached is a small sample to reproduce this exception, which uses a certain version of Microsoft F# compiler (which should have not been obfuscated in any way).

This exception has been reported by Obfuscar users quite frequently,

https://github.com/lextm/obfuscar/issues/116

So it should happen to other assemblies (obfuscated or not).

[ConsoleApplication.zip](https://github.com/jbevain/cecil/files/1308383/ConsoleApplication.zip)

**Comment by jbevain** [comment]
Thanks for the repro, I'll look into it!

**Comment by jbevain** [comment]
Should be fixed in master. Thanks!

**Comment by lextm** [comment]
Good to know. It should help many Obfuscar users :)
