### ISSUE TITLE
Changing the IsValueType property does not do anything

### ISSUE THREAD

**Issue by mrakgr** [jbevain/cecil#452]
```
let t = TypeDefinition("test","foo",TypeAttributes.Class)
t.IsValueType <- true
t.IsValueType // false
```

This is my first time using Cecil and I am not that familiar with .NET reflection, but I think the above is a bug. This is in the latest prerelease version on Nuget.

**Comment by jbevain** [comment]
Hello,

Good catch, that is indeed a bug.

You need to set the TypeDefinition BaseType to `System.ValueType`

**Comment by mrakgr** [comment]
Does that mean that the `IsValueType` property is supposed to be read-only?

**Comment by jbevain** [comment]
For a `TypeDefinition`, yes. The BaseType of a TypeDefinition controls whether the type is a value type or not.

**Comment by jbevain** [comment]
Fixed in master. Thanks for reporting this!
