### ISSUE TITLE
How to get the methods of a GenericInstanceType?

### ISSUE THREAD

**Issue by mrakgr** [jbevain/cecil#454]
Could you take a look at [this](https://stackoverflow.com/questions/46731131/how-to-get-the-methods-of-a-genericinstancetype) SO question please?

**Comment by mrakgr** [comment]
Please ignore that referenced issue, I tend to use the commits in that repo as a work diary.

**Comment by mrakgr** [comment]
```
let dictionary_type =
    mscorlib.Modules.[0].Types
    |> Seq.find (fun x -> x.Name = "Dictionary`2")

let add_method =
    dictionary_type.Methods
    |> Seq.find (fun x -> x.Name = "Add")

let dictionary_type_params = dictionary_type.GenericParameters.[0]
let add_method_params = add_method.Parameters.[0]
// Nope, they are not even the same class
Object.ReferenceEquals(dictionary_type_params,add_method_params) // false
```

I had the idea that I might be able to use the `WeakConditionalTable` to perform the substitution explicitly, but generic parameters in the definition and the ones in the method have nothing to do with one another. I might be able to do it somehow if I knew how to establish a mapping between the two, but now I am once more unsure how to proceed.

**Comment by jbevain** [comment]
Answered on SO.
