### ISSUE TITLE
cant build netstandard from source

### ISSUE THREAD

**Issue by SimonCropp** [jbevain/cecil#456]
on master i get 

```
Assets file 'C:\Code\cecil\symbols\mdb\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Mono.Cecil.Mdb			
```
 and a restore doesnt fix it

**Comment by jbevain** [comment]
How do you build?

I do:

`
dotnet clean Mono.Cecil.sln /p:Configuration=netstandard_Release
dotnet build Mono.Cecil.sln /p:Configuration=netstandard_Release
`

Which seems to work here.

**Comment by SimonCropp** [comment]
My error was from withing VS. but u r correct command line works and will suffice for my requirements

**Comment by SimonCropp** [comment]
oh and thanks :)
