### ISSUE TITLE
/nostdlib built assembly that doesn't define version crashes Cecil

### ISSUE THREAD

**Issue by kaby76** [jbevain/cecil#458]
This is a request.

I'm using Cecil to read and decompile CIL for JITing to GPU code. Unfortunately, I have to write a NET runtime for the GPU. I have chosen to modify the DotNetAnywhere anywhere runtime to work on a GPU as it is the smallest, most useful version I can find. Unfortunately, Cecil crashes when reading the DotNetAnywhere corlib.dll library itself, in LoadModule() -> ... -> Mono.Cecil.Mixin.ParseRuntime(string self), at the "switch (self [1]) {" line. Here, "self" is the empty string. It would be nice if Cecil be more robust with this custom-crafted BCL. I modified Cecil locally to simply return a value TargetRuntime.Net_2_0, and Cecil continues and performs from then on exactly as I need. On my end, I think I need to modify the source for my BCL to set the version, although I'm not exactly sure how to do this as the source code comments out this stuff.

**Comment by jbevain** [comment]
Fixed in master. Thanks!

**Comment by kaby76** [comment]
Thanks for the update! Just in case others plan on using /nostdlib and making up their own BCL, it turns out the version can be specified in the csproj, e.g., "<RuntimeMetadataVersion>v4</RuntimeMetadataVersion>". It seems you can set it to be almost anything, albeit Cecil may not parse the string, and you get a warning during the build if you don't set it.
