### ISSUE TITLE
Portable PDB: Document API

### ISSUE THREAD

**Issue by tmat** [jbevain/cecil#463]
Currently ```Document``` is used to represent a source document parsed from both Windows and Portable PDB.

The API is following:

```C#
class Document
{
 public string Url { get; set; }
 public DocumentType Type { get; set; }
 public DocumentHashAlgorithm HashAlgorithm { get; set; }
 public DocumentLanguage Language { get; set; }
 public DocumentLanguageVendor LanguageVendor { get; set; }
 public byte [] Hash { get; set; }
}
```

A few issues with this API shape:
1) ```Type``` and ```LanguageVendor``` are only in Windows PDBs. They are not present in Portable PDBs.
2) ```Type```, ```HashAlgorithm```, ```Language```, ```LanguageVendor``` are stored as GUIDs in Windows and Portable PDBs and thus may be set to an arbitrary value not currently mapped by Cecil to specific enum. As a result Cecil is not able to round-trip PDBs containing languages, hash algorithms, etc. it doesn't recognize. This could be fixed by also adding properties named ```XxxGuid``` that hold on the GUID.
3) Windows PDBs can now embed sources. The format of the blob is the same as Portable PDB EmbeddedSource custom debug information, but in Windows PDB the blob is directly associated with the document (not a CDI). Windows PDB document representation should thus have property ```byte[] EmbeddedSource { get; set; }```.
4) Since Windows PDB and Portable PDB have different data directly associated with document it might make sense to represent them by different classes, e.g. ```Document``` for Windows PDB and ```DocumentDebugInformation``` (or ```PortableDocument```) for Portable PDB. Alternatively document could be an union of all the properties and some of them are just not allowed in one format or the other.

**Comment by jbevain** [comment]
Let's go one single Document class with different fields and each reader/writer populates takes what i can. That's what we've been doing for mdb and pdb for now.

**Comment by jbevain** [comment]
That's #491.
