### ISSUE TITLE
Getting generic arguments and the path of an assembly SO questions.

### ISSUE THREAD

**Issue by mrakgr** [jbevain/cecil#464]
Hello, could you please take a look at these two SO questions and give them your input. Sorry if opening an issue here is redundant, but last time I had to wait a while for an answer so I am not sure whether you check Mono.Cecil tags on SO regularly.

https://stackoverflow.com/questions/47121748/how-to-get-the-generic-arguments-of-a-typereference
https://stackoverflow.com/questions/47119802/how-to-just-get-the-path-of-an-assembly-rather-than-loading-it

**Comment by jbevain** [comment]
> last time I had to wait a while for an answer

It sounds like you need to purchase a Service-level agreement?

The README directs questions to the `mono-cecil` Google Group.

**Comment by mrakgr** [comment]
Noted and I'll keep it in mind if I have any follow up questions, but I feel that SO has a much better format and searchability for these kinds of questions than Google Group. Besides, I am not in a hurry - I'll be able to replace the inbuilt reflection with `Mono.Cecil` assuming I can figure out how to get the generic arguments of a type reference.
