### ISSUE TITLE
.pdb files creation on linux platforms

### ISSUE THREAD

**Issue by ArsenShnurkov** [jbevain/cecil#465]
Is it still unimplemented and what are plans on this?

<a href="https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md">Portable PDB v1.0: Format Specification</a>
<a href="https://llvm.org/docs/PDB/">The PDB File Format (llvm documentation)</a>
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/PEWriter/MetadataWriter.PortablePdb.cs
https://github.com/dotnet/roslyn/issues/19297

**Comment by jbevain** [comment]
Portable PDBs are supported accross all platforms.
Native PDBs can currently not be written on non windows platforms, and I have no immediate plan to implement that.
