### ISSUE TITLE
Question: can I clone a method (in same type)?

### ISSUE THREAD

**Issue by per-samuelsson** [jbevain/cecil#476]
Consider this:

```csharp
class Foo {
  void Bar() {
    Console.Write("Bar");
  }
}
```

Having the `TypeDefinition`, what would be recommended approach to *clone* the `Bar()` method, allowing me to use the clone as a starting point for modifying its instructions?

The most obvious approach seemed to me to be this:

```csharp
var bar = foo.Methods.Single(m => m.Name == "Bar"); 
var clone = new MethodDefinition("Bar2", bar.Attributes, bar.ReturnType);
clone.Body = bar.Body;
foo.Methods.Add(clone);
```

However, if I now *modify* the body of the clone, I also **modify the body of the original**. Since they reference the same instance. 

Tried hard to figure out by browsing API and searching old user groups / issues, but with no success.

Any one with a hint?

**Comment by per-samuelsson** [comment]
And to be clear, doing something like this:

```csharp
clone.Body = new MethodBody(clone);
bar.Instructions.All(i => clone.Body.Instructions.Add(i));
```

will not allow me to modify other stuff of the cloned body, since many properties are read-only. And I suspect I need that to satisfy a fully verifiable assembly?

**Comment by jbevain** [comment]
Yeah there's nothing builtin to clone metadata or IL I'm afraid, you'll need to fully recreate a Body method, and fully recreate Instructions, as those can be modified when writing.

**Comment by per-samuelsson** [comment]
OK, @jbevain, thanks! Just knowing that helps.

**Comment by SimonCropp** [comment]
@per-samuelsson  just a note on if u do attempt this. both `async` and `yield` result in state machines being generated. these state machines are specific to the method they are used in. so when u clone u may also need to clone the state machine, depending on your requirements.

**Comment by per-samuelsson** [comment]
> @per-samuelsson just a note on if u do attempt this. both `async` and `yield` result in state machines being generated.

@SimonCropp 

Thanks a lot for pointing that out. I'll make sure to cover those cases in tests. At this point, I think we only have need to move `.ctor` bodies, so not sure how they apply to that. But I'll sure do some research on it now you've mentioned it. 👍
