### ISSUE TITLE
Understanding the MDB loading process

### ISSUE THREAD

**Issue by mazegen** [jbevain/cecil#478]
I'm new to cecil and I'm trying to understand the MDB loading process. As far as I can tell, it goes this way (starting in `ModuleReader` class):

    CreateModule()
    - ReadSymbols()
      - new DefaultSymbolReaderProvider
      - DefaultSymbolReaderProvider.GetSymbolReader()
        - SymbolProvider.GetReaderProvider()
        - MdbReaderProvider.GetSymbolReader()
          - MonoSymbolFile.ReadSymbolFile()
            - new MonoSymbolFile
      - ModuleDefinition.ReadSymbols()   (does almost nothing in case of Deferred ReadingMode)
    - DeferredModuleReader.ReadSymbols()   (empty overriden method)

However, I doubt that this is the complete loading process. I'm confused by the `DeferredModulReader.ReadSymbols()` that is empty while `ImmediateModulReader.ReadSymbols()` does a lot of work. It seems that `Deferred` is the default reading mode and therefore `ImmediateModulReader.ReadSymbols()` is not called (unless the `Immediate` mode is specified).

I'm kind of stuck at this point because I don't understand where and when is the MDB loading finished.

**Comment by jbevain** [comment]
It goes like this:

The MdbReaderProvider creates a MdbReader.
If the module has been asked to load things Immediately, it will create the symbols for the methods.
If the module has been asked to load things when accessed (deferred), the symbols are accessed when creating the method body.
