### ISSUE TITLE
Better reporting when loading invalid debug symbols

### ISSUE THREAD

**Issue by spouliot** [jbevain/cecil#480]
It's hard to report an accurate description of what went wrong when bad symbols are loaded.

Right now we (XI/XM) workaround this with:
https://github.com/xamarin/xamarin-macios/pull/3203/files#diff-18af9c31adf82a237cb45f1284bb2b3eR89

which is _fragile_ (at best) and I'd like a better way. I'll propose a PR with an easy solution _soonish_ but I'm open to suggestions :)

More details in
* https://github.com/xamarin/xamarin-macios/issues/3200
* https://github.com/xamarin/xamarin-macios/pull/3079#issuecomment-352787934

**Comment by jbevain** [comment]
Yeah that's pretty bad. We should probably introduce a Cecil exception for mismatched symbols. @spouliot what was the PR you wanted to suggest?

**Comment by jbevain** [comment]
Fixed by #494.
