### ISSUE TITLE
Massive lack of documentation

### ISSUE THREAD

**Issue by solidDoWant** [jbevain/cecil#483]
This project lacks almost any documentation. Can somebody who knows in detail how it should be used/what each of the methods and properties do add some documentation and/or comments? I'm trying to use this on one of my projects, but I honestly have no idea what half of the code does. The three examples on the wiki don't really cut it.

**Comment by jbevain** [comment]
Well we all do what we can with the time we have. Feel free to invest in exactly what you're asking :)

**Comment by solidDoWant** [comment]
I would but without documentation I can't learn the framework - and if I cant learn the framework I can't document it.

**Comment by teo-tsirpanis** [comment]
@jbevain, this library is by far the most known library that does this job and has been downloaded millions of times. Adding documentation would embellish its quality, and make it easier to use. I think it is worth the effort.

**Comment by adrianoc** [comment]
While I agree that the project lacks docs and that having documentation would be a big improvement, I also agree with @jbevain. Documenting is never an easy task and takes time. Besides that, working on documentation is a great way to learn.

That being said you can try to use https://cecilifier.me/ to help you to learn how to use Mono.Cecil (disclaimer: I am the author of that project)

**Comment by Tyfyter** [comment]
There appears to be a total lack of documentation on `ExceptionHandlerType`, and half of its possible values use names seemingly unique to this project.
