### ISSUE TITLE
File not closed when using InMemory?

### ISSUE THREAD

**Issue by Nezz** [jbevain/cecil#490]
In this part of `ModuleDefinition`:
https://github.com/jbevain/cecil/blob/master/Mono.Cecil/ModuleDefinition.cs#L1079-L1087
I noticed that the `stream` variable gets simply overwritten with a `MemoryStream`. As a result, `FileStream` is not disposed when `InMemory` is used. Are my observations correct?

**Comment by jbevain** [comment]
This line:

https://github.com/jbevain/cecil/blob/master/Mono.Cecil/ModuleDefinition.cs#L1083

Will dispose the file stream after it has been copied in the memory stream.

**Comment by Nezz** [comment]
Of course, thanks!
