### ISSUE TITLE
ModuleDefinition.GetType(string, bool) can return a type that doesn't exist

### ISSUE THREAD

**Issue by ltrzesniewski** [jbevain/cecil#496]
The `ModuleDefinition.GetType(string fullName, bool runtimeName)` method has a discrepancy when you pass it a type name which doesn't exist:

- When `runtimeName` is false, it returns null
- When `runtimeName` is true, it returns a reference to the non-existing type

The reference is being created by `TypeParser` [here](https://github.com/jbevain/cecil/blob/f9ac40651febac1c79095d1a159e166530001b58/Mono.Cecil/TypeParser.cs#L249-L250).

It doesn't look like this behavior is intended given that there are null checks in `NativePdbReader` [here](https://github.com/jbevain/cecil/blob/f9ac40651febac1c79095d1a159e166530001b58/symbols/pdb/Mono.Cecil.Pdb/NativePdbReader.cs#L284) and [here](https://github.com/jbevain/cecil/blob/f9ac40651febac1c79095d1a159e166530001b58/symbols/pdb/Mono.Cecil.Pdb/NativePdbReader.cs#L302). If this is intended behavior, then it's a surprising one, to say the least.

Here's a workaround I've found to get a type by its runtime name if it exists:
```C#
module.GetType(module.GetType(typeName, true).FullName)
```
But this code just feels wrong 😉

**Comment by jbevain** [comment]
Yeah that looks weird.

**Comment by jbevain** [comment]
Fixed in 022b6f6a6303937452050ad7724953db2f52fd71. Thanks for reporting this!
