### ISSUE TITLE
[0.10.0 netstandard] System.MissingMethodException : Method not found: 'Int32 Mono.Cecil.MetadataReader.ReadCodeSize(Mono.Cecil.MethodDefinition)'.

### ISSUE THREAD

**Issue by SteveGilham** [jbevain/cecil#500]
This is a change of behaviour since 0.10-beta7 -- loading an assembly built with `mcs` with a `.mdb` symbol file used to work quite happily from a .net core process the same as from old-fashioned .net.  Old-fashioned .net still works with  0.10 final, but now using a .net core process to load the same assembly, a `System.MissingMethodException` with this stack trace emerges
```
Result StackTrace:	
at Mono.Cecil.Mdb.MdbReader.<>c.<ReadCodeSize>b__7_0(MethodDefinition m, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.Mdb.MdbReader.Read(MethodDefinition method)
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody()
   at Mono.Cecil.Cil.CodeReader.ReadMethodBody(MethodDefinition method)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TRet& variable, TItem item, Func`3 read)
   at Mono.Cecil.MethodDefinition.get_Body()
```

**Comment by jbevain** [comment]
How weird. Thanks for reporting this. You're using both the Mono.Cecil.dll and Mono.Cecil.Mdb.dll from the lib/netstandard1.3 nuget?

**Comment by SteveGilham** [comment]
Being a .net core app, it just says `    <PackageReference Include="Mono.Cecil" Version="0.10.0" />` in the project file, so I'm assuming that doesn't have its wires crossed.  

Here's an assembly that shows the issue : [Sample1.zip](https://github.com/jbevain/cecil/files/1834094/Sample1.zip)

**Comment by jbevain** [comment]
Thanks, I'll have a look pronto.

**Comment by jbevain** [comment]
This actually looks like #495.

**Comment by jbevain** [comment]
The reason why it changed between the beta7 and the final is b4f4571a7f45df013c32f3ccd3939b8852819b04 that introduced the call.

**Comment by jbevain** [comment]
@SteveGilham I can't seem to repro.

I created a new dotnet project:

```
dotnet new console
dotnet add package Mono.Cecil
```

Modified the csproj so that it reads:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.0;net46</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Sample1.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Sample1.exe.mdb">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.10.0" />
  </ItemGroup>

</Project>
```

Wrote:

```csharp
using System;
using System.Linq;

using Mono.Cecil;

namespace _500repro
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
			
			using (var module = ModuleDefinition.ReadModule("Sample1.exe", new ReaderParameters { ReadSymbols = true }))
			{
				Console.WriteLine($"Module has symbols: {module.HasSymbols}");

				foreach (var method in module.GetTypes().SelectMany(t => t.Methods).Where(m => m.HasBody))
				{
					Console.WriteLine($"On method: {method.FbullName}");
					Console.WriteLine(method.Body);
				}
			}
        }
    }
}
```

And when running for both frameworks it runs without crashing on getting the method body.

**Comment by SteveGilham** [comment]
I'm in the process of cutting down to a simple repro case.  Will update later.

**Comment by SteveGilham** [comment]
I've found the culprit.  It's the NUnit3TestAdapter v 3.10.0 which includes also Mono.Cecil, from beta6
```
[assembly: AssemblyInformationalVersion("0.10.0.0-beta6")]
[assembly: AssemblyTitle("Mono.Cecil")]
```
and that's going to be loaded ahead of any of my code.

**Comment by SimonCropp** [comment]
> It's the NUnit3TestAdapter v 3.10.0 which includes also Mono.Cecil, from beta6

@SteveGilham one of reasons i moved to xunit
