### ISSUE TITLE
There is no NuGet package for .NET Standard 2.0

### ISSUE THREAD

**Issue by rfvan** [jbevain/cecil#507]
I was trying to re-sign a DLL that I modified (injected a module load constructor) from a .NET Core 2.0 application. This works fine from a .NET Framework 4.5 application. Unfortunately, nothing that relies on WriterParameters.StrongNameKeyPair is available on the .NET Standard 1.3 build - it's all "ifdef"ed out using the NET_CORE tag. I believe the necessary underlying support is available in .NET Standard 2.0. Could you please provide a .NET Standard 2.0 target to bring back this feature?  Thanks.

**Comment by SimonCropp** [comment]
IMO just drop 1.3 support and move to "only 2.0"

**Comment by jbevain** [comment]
Agreed, we need to move to netstandard 2.0 only.

**Comment by rfvan** [comment]
It is also currently not possible to create a self-contained deployment of any .NET Core 2.X application that depends on Mono.Cecil because there are a whole bunch of "version downgrade" errors for dependencies like System.Collections, System.IO and others from 4.3.0 to 4.0.1 or 4.0.11 (the latter being what the current Mono.Cecil package depends upon).

**Comment by rfvan** [comment]
I wish they were only warnings. The last line of output basically says "Package restore failed" and the output directory to which the profile points is empty.

**Comment by SimonCropp** [comment]
Does this occur on a clean project with no other references?

**Comment by rfvan** [comment]
Hmm, no it does not. Clearly there are some other dependencies, direct or indirect, that are part of the issue. I'm new to .NET Core, so apparently have some learning ahead of me. Thanks for the input - at least now I know where to start looking.

**Comment by atykhyy** [comment]
Unfortunately `StrongNameKeyPair` is not implemented in .NET Core - the type is there, but its methods and properties throw `PlatformNotSupportedException`. PR #548 works around this problem.

**Comment by chkn** [comment]
Another reason to move to .NET Standard 2.0: https://github.com/mono/mono/issues/12692

**Comment by SimonCropp** [comment]
this can be closed

**Comment by jbevain** [comment]
I pushed 0.11 to nuget today with .NET Standard 2.0 support. Thanks!
