### ISSUE TITLE
Could not load file or assembly '...UnityEngine.UI...' or one of its dependencies.

### ISSUE THREAD

**Issue by shwz** [jbevain/cecil#508]
I use inject some dll  use in unity,it will bring this erro:ps(inject dll call Demo.ll )

FileNotFoundException: Could not load file or assembly 'YoukiaUnity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
FileNotFoundException: Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

any wrong operation can cause this

**Comment by jbevain** [comment]
Hello,

I'm sorry but there's not enough information here to help you.
