### ISSUE TITLE
Can not get inherited custom attributes

### ISSUE THREAD

**Issue by paxhujing** [jbevain/cecil#511]
[AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = true)]
    public class TestAttribute : Attribute{}

    public class Base
    {
        [Test("a")]
        public virtual void Test()
        {
        }
    }

    public class Derive : Base
    {
        public override void Test()
        {
            base.Test();
        }
    }
the MethodDefinition.CustomAttributes is empty,how can i get inherited custom attributes

**Comment by jbevain** [comment]
Cecil, unlike System.Reflection, provides a view of the metadata. Inherited attributes are not in the metadata, they're gathered at runtime.

To get the same results, you'd need to follow the type hierarchy to gather the custom attributes in the base types that you need.
