### ISSUE TITLE
Allow overriding the Windows subsystem version when writing an assembly

### ISSUE THREAD

**Issue by ks-jeppe** [jbevain/cecil#512]
Currently it is hardcoded to 4.0 which can cause changes in visual OS parameters for graphical programs. 

It seems like most newer tools emit 6.0 here

**Comment by jbevain** [comment]
The subsystem is computed based on the type of binary. It's 3 for a dll for instance.

In which case do you get 6?

**Comment by ks-jeppe** [comment]
I'm referring to this point: https://github.com/jbevain/cecil/blob/eea822cad4b6f320c9e1da642fcbc0c129b00a6e/Mono.Cecil.PE/ImageWriter.cs#L246

In all tools I could find to test they use 6.0 instead of 4.0

**Comment by jbevain** [comment]
Ah I see. Let me check what this means and I'll get back to the issue.

**Comment by ks-jeppe** [comment]
There's some more detailed information about it here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/subsystemversion-compiler-option#default-values 

But I think just reusing the parameters in case an assembly is read would be the most optimal solution
