### ISSUE TITLE
BadImageFormatException when reading mono.dll (Format of the executable (.exe) or library (.dll) is invalid.)

### ISSUE THREAD

**Issue by sebastientromp** [jbevain/cecil#514]
Hello,

I apologize if this is not the correct place to report this - I'm totally new at memory reading, and am struggling to get started.

I want to read memory from a game built in Unity, and am trying to read the `mono.dll` assembly.
My code is
```
public class EntryPoint
	{
	    static void Main()
		{
			var assemblyDef = AssemblyDefinition.ReadAssembly("path/to/mono.dll");
		}
	}
```
When executing it, I get the following exception:
```
Unhandled Exception: System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadOptionalHeaders(UInt16& subsystem, UInt16& dll_characteristics, UInt16& linker)
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName)
   at MindVision.New.EntryPoint.Main()
```
I can provide the `mono.dll` I'm targeting if that can help.

Is there any I'm not doing properly? Is there anything else I should know about using Cecil + mono?

Thanks for any help you can give!
Seb

**Comment by jbevain** [comment]
This means that `mono.dll` is not a managed assembly. It's likely the Mono runtime which is unmanaged code.

**Comment by sebastientromp** [comment]
Thanks. So this means I can't use Mono.Cecil to dig into the mono runtime, right?

**Comment by jbevain** [comment]
Well no, the Mono runtime is a large bunch of C functions. Cecil gives you an object model for a managed assembly.
