### ISSUE TITLE
Can Mono.Cecil be used to read a process memory?

### ISSUE THREAD

**Issue by sebastientromp** [jbevain/cecil#515]
I am trying to read the state in memory of a game built using Unity3D, and have been advised to look into Mono.Cecil.  
While reading memory is fine (or at least tolerated) by the game's ToS, writing/injecting custom code is definitely not.

From reading the docs here, I feel that Cecil's way to access information is to inject a custom piece of code in the methods you are interested in, so that you can later on retrieve this information. Is this assumption correct?  
And more generally, is there a way to get a Unity3D/Mono process memory contents without injecting custom code with Cecil? Or do I have to do everything manually and rely on `ReadProcessMemory`?

Thanks for your help!
Seb

**Comment by jbevain** [comment]
Cecil is a library to read and write the .NET representation of a program (a managed assembly).

It can not be used to modify a runtime representation of loaded code, neither for Mono nor .NET.
