### ISSUE TITLE
Cannot replace embedded resource

### ISSUE THREAD

**Issue by FailedShack** [jbevain/cecil#518]
If an embedded resource is removed from an assembly, then a new one created with different contents and added to the same assembly. The written assembly will have the contents of the original resource and not the new one. If instead, the resource is added with a different name, the resource has the contents of the new one, as expected.

I've created an example project where you can see this issue: https://github.com/FailedShack/CecilTest

**Comment by jbevain** [comment]
Thanks for the repro, I'll have a look!
