### ISSUE TITLE
Assembly obfuscated with Crypto Obfuscator fails round trip

### ISSUE THREAD

**Issue by FailedShack** [jbevain/cecil#519]
Assemblies obfuscated with Crypto Obfuscator may cause Cecil to write an executable that doesn't behave like the original, even with no changes applied. If the assembly is first deobfuscated with de4dot, the round trip goes as expected.

Stacktrace:
> System.TypeInitializationException: The type initializer for 'A' threw an exception. ---> System.ArgumentException: Type handle 'A' and method handle with declaring type 'B' are incompatible. Get RuntimeMethodHandle and declaring RuntimeTypeHandle off the same MethodBase.

In my case I was testing it with the executable of a program called Wii U USB Helper, which can be found [here](http://www.softpedia.com/get/Internet/Download-Managers/Wii-U-USB-Helper.shtml) or zip version [here](https://mega.nz/#!pNYVESxD!fxn0dS4hSihstG-OOJz9gaUJCS5UmVPimmMBED7-POs). You may run the main executable (WiiU_USB_Helper.exe), without the updater, but you must pass it a single argument to run it, it doesn't matter what it is (e.g. "a").

**Comment by jbevain** [comment]
Those obfuscators are doing everything they can to break us, I'm not really interested in running after them :)
