### ISSUE TITLE
Renaming a type in an assembly will not update its name when used with typeof in an attribute

### ISSUE THREAD

**Issue by sbergen** [jbevain/cecil#520]
Upgrading to 0.10.0, given the following program:

```
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Enter path to assembly:");
        var path = Console.ReadLine();

        using (var asm = AssemblyDefinition.ReadAssembly(path, new ReaderParameters { ReadWrite = true }))
        {
            foreach (var type in asm.MainModule.GetTypes())
            {
                type.Name += "Renamed";
            }

            asm.Write(path + "Renamed.dll");
        }
    }
}
```

and running it on the dll compiled from this source:

```
namespace TestAssembly
{
    public class TestAttribute : Attribute
    {
        public TestAttribute(Type type) {}
    }

    class ArgClass {}

    [Test(typeof(ArgClass))]
    class AttributedClass {}
}
```

Will result in the following output in the renamed assembly:
```
[TestAttributeRenamed (typeof(ArgClass))]
internal class AttributedClassRenamed
```

instead of the following, which was the behavior at least in  0.9.6.0
```
[TestAttributeRenamed (typeof(ArgClassRenamed))]
internal class AttributedClassRenamed
```

**Comment by jbevain** [comment]
Hello @sbergen,

That's counter intuitive but that's due to 2 things:

1. the way custom attributes are encoded, where `typeof` is simply a string,
2. To save memory, Cecil will not attempt to load all custom attributes.

Try passing `ReadingMode.Immediate` to ReadModule/ReadAssembly. This way Cecil will turn the string into a TypeReference, and it should get renamed.

**Comment by sbergen** [comment]
Hello @jbevain,

Thanks for the solution, this works indeed!

**Comment by Nezz** [comment]
Are there any more possible surprises when migrating to 0.10 other than this and what's detailed on the [website](http://cecil.pe/)?
