### ISSUE TITLE
Can't resolve System.Reflection.BindingFlags

### ISSUE THREAD

**Issue by SomeCatIDK** [jbevain/cecil#523]
Basically, there are a few assemblies stored inside another using Costura; however, one will not load do to this weird bug. 

I have searched through and compared the assemblies, the one that won't load doesn't appear to be an different than the other ~30, same dependencies, .NET version (4.6), ect.

Here is a link to the full issue:

https://stackoverflow.com/questions/50862877/mono-cecil-cant-resolve-system-reflection-bindingflags

**Comment by jbevain** [comment]
Thanks for reporting this.

Unfortunately I probably won't have a chance to address it unless your attach a self-contained repro to this issue that I can look into.

**Comment by ChubbyQuokka** [comment]
@jbevain Here is the link: https://github.com/RocketMod/Rocket.Eco/tree/dev

Specifically: 
https://github.com/RocketMod/Rocket.Eco/tree/dev/Rocket.Eco.Patching/PatchingService.cs
https://github.com/RocketMod/Rocket.Eco/tree/dev/Rocket.Eco.Launcher/Program.cs
https://github.com/RocketMod/Rocket.Eco/tree/dev/Rocket.Eco.Launcher/Utils/CosturaHelper.cs
https://github.com/RocketMod/Rocket.Eco/tree/dev/Rocket.Eco.Launcher/Utils/CosturaAssemblyResolver.cs

**Comment by jbevain** [comment]
@ChubbyQuokka sorry but I don't have the bandwidth to dive into your code base, try to build run it. Please extract and provide a self contained repro that I can debug.

**Comment by jbevain** [comment]
I'm afraid I have to close this for now. Feel free to re-open with a standalone repro if you're still impacted by the issue. Thanks!
