### ISSUE TITLE
make typesystem replacable

### ISSUE THREAD

**Issue by SimonCropp** [jbevain/cecil#525]
two issues atm

1. cant set the current typesystem prop for a moduledefinition
2. cant inherit from typesystem since it has internal abstract members

**Comment by jbevain** [comment]
What's the underlying issue here? Why can't you use `TypeSystem.Object`?

**Comment by SimonCropp** [comment]
@jbevain sorry i dont have the time to properly explain my reasoning here. i had a suspicion the typesystem behaviour was causing me some problems and tried to replace it.

I will close for now, and re-open when i have the capacity to better articulate my reasoning and repro. 

Sorry for the noise
