### ISSUE TITLE
TypeReference and netstandard

### ISSUE THREAD

**Issue by bhugot** [jbevain/cecil#526]
Hello,

I m trying to add a class into a netstandard2.0 assembly and when I import the reference for TypeSystem.object ctor, then System.Private.CoreLib is added to assembly reference but System.Object is included in netstandard assembly reference.

I tryed to importReference by getting it from the netstandard assembly reference and all seems to be working but when I want to use the class in code the type can't be loaded

Any Idea how to fix this?

thanks

**Comment by atykhyy** [comment]
You have to use the approach described in [this issue](https://github.com/jbevain/cecil/issues/487#issuecomment-377780250).

**Comment by Draethorian** [comment]
Well it would help if you could post your solution instead of just saying that you solved it... ;-)

**Comment by jbevain** [comment]
@bhugot are you still hitting this issue? Closing this for now, feel free to re-open if you still need help. Thanks!

**Comment by atykhyy** [comment]
I have posted the helper code that improves on my [previous approach](https://github.com/jbevain/cecil/issues/487#issuecomment-377780250) in [atykhyy/cecil-msbuild-helper](https://github.com/atykhyy/cecil-msbuild-helper).
