### ISSUE TITLE
Unable to target correctly generic parameter in nested type

### ISSUE THREAD

**Issue by Virtuoze** [jbevain/cecil#529]
Hi,

When I open an existing class 

        public class C1<T>
        {
        }

and add a nested class **MyNestedClass** that work fine. 

        public class C1<T>
        {
             private class MyNestedClass
             {
             }
        }

However when I try to add a method to **MyNestedClass** using **T** as a parameter type of any paremeter, that emit a wrong type producing non resolvable **!0** instead of **T**

        public class C1<T>
        {
             private class MyNestedClass
             {
                 public void Method1(!0 param1)
                 {
                 }
             }
        }

Expected code

        public class C1<T>
        {
             private class MyNestedClass
             {
                 public void Method1(T param1)
                 {
                 }
             }
        }

Looks like the process is trying to get the generic parameter on the nested type instead of the original type.

Note : execution dosent work and reflector can show the result when C# view is selected but throw a null reference exception when IL view is selected.

**Comment by SimonCropp** [comment]
@Virtuoze are you using cecil to manipulate an assembly?

**Comment by Virtuoze** [comment]
for sure mono.cecil **0.10.0** / **0,9.6.4**
here a sample code with this issue.

    static public class Program
    {
        static void Main(string[] args)
        {
            Program.Manage(args[0]);
        }

        static private void Manage(string assembly)
        {
            var _resolver = new DefaultAssemblyResolver();
            _resolver.AddSearchDirectory(Path.GetDirectoryName(assembly));
            var _assembly = AssemblyDefinition.ReadAssembly(assembly, new ReaderParameters() { AssemblyResolver = _resolver, ReadSymbols = true, ReadingMode = ReadingMode.Immediate });
            var _module = _assembly.MainModule;
            foreach (var _type in _module.GetTypes().ToArray()) { Program.Manage(_type); }
            _assembly.Write("test.dll", new WriterParameters { WriteSymbols = true });
        }

        static private void Manage(TypeDefinition type)
        {
            if (type.Name == "<Module>") { return; }
            var _type = new TypeDefinition(type.Namespace, "<Puresharp>", TypeAttributes.Class | TypeAttributes.Sealed | TypeAttributes.Abstract | TypeAttributes.NestedPrivate);
            type.NestedTypes.Add(_type);
            foreach (var _method in type.Methods.ToArray()) { Program.Manage(_type, _method); }
        }

        static private void Manage(TypeDefinition type, MethodDefinition method)
        {
            var _method = new MethodDefinition(method.Name, MethodAttributes.Static | MethodAttributes.Public, method.Module.ImportReference(typeof(void)));
            foreach (var _perameter in method.GenericParameters) { _method.GenericParameters.Add(new GenericParameter(_perameter.Name, _method)); }
            type.Methods.Add(_method);
            foreach (var _parameter in method.Parameters)
            {
                var _type = _parameter.ParameterType;
                if (_type.IsGenericParameter)
                {
                    if (method.GenericParameters.Contains(_parameter.ParameterType as GenericParameter))
                    {
                        _type = _method.GenericParameters[method.GenericParameters.IndexOf(_parameter.ParameterType as GenericParameter)];
                    }
                    else
                    {
                        //use original type produce !0 instead of true generic type from declaring type... bug?
                    }
                }
                _method.Parameters.Add(new ParameterDefinition(_parameter.Name, _parameter.Attributes, _type));
            }
            _method.Body.Instructions.Add(Instruction.Create(OpCodes.Ret));
            _method.DeclaringType = type;
        }
    }

**Comment by Virtuoze** [comment]
After a long search, it is not an issue, just a bad usage. 
Indeed, nested types in generic types must copy all declaring generic parameter types to work.
