### ISSUE TITLE
Is there any way not to generate `k__BackingField` auto fields?

### ISSUE THREAD

**Issue by IamSanjid** [jbevain/cecil#532]
I was thinking if it was possible not to generate `k__BackingField` auto fields. How can I do that? Please, help.

**Comment by SimonCropp** [comment]
so you want to convert fields to properties?

**Comment by IamSanjid** [comment]
No. Here check this pic: http://prntscr.com/kqx4ei I just want to replace `<Height>k__BackingField` from the method part with Height. You can understand I am not pro I am kinda a newbie to this stuff. Thanks for the reply.

**Comment by jbevain** [comment]
Hello,

Cecil doesn't generate anything by itself. It's just a library to read and write a .NET binary. If you want to modify a binary that's a fairly complex process, maybe use a UI tool like Reflexil to get started.
