### ISSUE TITLE
How do I correctly create a brtrue instruction

### ISSUE THREAD

**Issue by Hi-ImKyle** [jbevain/cecil#533]
So I have this in a method of mine that is trying to add a chat hook check to a if statement.
I checked the IL of the code I want to add and this is what that IL is but using `Instruction.Create`
```csharp
Instruction.Create(OpCodes.Ldsfld, ILUtils.GetField(Assembly.MainModule, "Terraria.Main", "chatText")), 
Instruction.Create(OpCodes.Call, Assembly.MainModule.ImportReference(typeof(MainTest).GetMethod("Chat_Hook"))), 
Instruction.Create(OpCodes.Brtrue, "")
```

The issue is, that whenever I try to create the instruction with the opcode Brtrue, an exception gets thrown with the message `opcode`. The least informative error. I've tried using `175` instead of `""` because that is what dnSpy is showing that I should put. But that still throws the `opcode` error.

This is what dnSpy shows in IL when i edit the C# directly. But in this situation I cant edit the code directly, only with Mono.Cecil.
![dnSpy IL](https://i.imgur.com/p6IzvwP.png)
As you can see, `135 01BC` shows `brtrue` with the operand `175 (024D) ldstr ""`

How would I create that opcode with that operand using `Instruction.Create`?

If it's possible anyway.

**Comment by jbevain** [comment]
If you create an Instruction from the Brtrue opcode, you need to pass the target instruction of the jump as the operand.
