### ISSUE TITLE
Renaming public classes in a set of assemblies 

### ISSUE THREAD

**Issue by Nezz** [jbevain/cecil#536]
We'd like to rename public classes in assemblies we ship with our app. How could we achieve this without breaking cross-assembly references? E.g. we compile class Foo into A.dll, which is used in the constructor of class Bar in B.dll. We want to rename Foo to Foobar, but with our current approach Bar fails to load because Foo cannot be found in B.dll.

**Comment by jbevain** [comment]
Hi @Nezz,

There are no easy solution, and I'm afraid there's nothing built in.

You'll need to rewrite the entire transitive closure of assemblies where you need to rename types, to also rename the references.
