### ISSUE TITLE
Can't build netstandard version - package restore fails, or finds nothing to do

### ISSUE THREAD

**Issue by IanOfOz** [jbevain/cecil#541]
I'm getting the same issue mentioned in #395 but with a twist

If I try dotnet restore on the command line I get:
`Nothing to do. None of the projects specified contain packages to restore.`

If I try package restore within Visual Studio 2017 I get:
`Error occurred while restoring NuGet packages: '$(NETStandardImplicitPackageVersion)' is not a valid version string.`

.Net Framework versions build fine though

**Comment by jbevain** [comment]
You need to pass the proper configuration on the command line I think:

`dotnet restore --configuration=netstandard_Debug`

**Comment by IanOfOz** [comment]
Great, thanks. The command was actually:

`dotnet restore /property:configuration=netstandard_Debug`
