### ISSUE TITLE
AssemblyResolver.Resolve return wrong version of mscorlib

### ISSUE THREAD

**Issue by KevOrr** [jbevain/cecil#549]
Thank you very much for this project.

I am using cecil v9.6.4. The application that I'm using it with is built with .NET Framework 4.5 but dynamically loads (not sure if this is the correct terminology) an assembly that is built for .NET Framework 2.0. This pulls in mscorlib 4.0.0.0 and 2.0.0.0. When trying to resolve the type `System.Runtime.Versioning.TargetFrameworkAttribute`, which is only defined in mscorlib 4.0.0.0, the scope that I pass into `MetadataResolver.AssemblyResolver.Resolve` is mscorlib 4.0.0.0, but the resolved assembly I get back is mscorlib 2.0.0.0. This obviously breaks things like `MetadataResolver.GetType`, since the type I'm looking for can't be found in that assembly.

![image](https://user-images.githubusercontent.com/2605289/48082753-638e2d80-e1c1-11e8-8401-4d7842c49f94.png)

Is there any workaround? Thanks.

**Comment by jbevain** [comment]
@KevOrr hi! Sorry it took a while to get to this.

Your screenshot indeed points at something going wrong. Any chance you could get me a repro that I could investigate? Thanks!

**Comment by newhillchan** [comment]
BaseAssemblyResolver.Resolve try to find assembly of running framework:

framework_dir = Path.GetDirectoryName (typeof (object).Module.FullyQualifiedName);

But this is not the framework of DLL to be resolved. And there is no checking if resolved dll is the dll to find. On my case, I'd like to find System.Runtime of dotnet core 2.1, but it gave me the assembly of .net framework 4.0 (I ran resolving with a .net Framework 4.0 program to resolve dll of dotnet core 2.1)

**Comment by jbevain** [comment]
Without more context it's hard to help. The suggestion is for you to pass your own custom assembly resolver to ensure it behaves as you expect.

Feel free to re-open a bug with a repro we could look at if you're stilling impacted.

Thanks!
