### ISSUE TITLE
How do i pay to use cecil?

### ISSUE THREAD

**Issue by SimonCropp** [jbevain/cecil#552]
So i am gradually moving all my projects to funded models. eg https://github.com/Fody/Fody#licensingpatron-faq

as part of that i would like to forward a % of those funds on to the tools that are used in those projects.

So how would i do that for this project?

**Comment by jbevain** [comment]
https://github.com/sponsors/jbevain

**Comment by SimonCropp** [comment]
done :)

**Comment by jbevain** [comment]
Thank you @SimonCropp. As I'm saying in the GitHub Sponsorship profil, while I'm extremely grateful to any individual that chooses to sponsor Cecil, what I would really like is for companies heavily using Cecil to sponsor the development of the project.

**Comment by SimonCropp** [comment]
@jbevain agreed. although seeing as i make some income from fody it seems right that i pass some of that on.
