### ISSUE TITLE
How do I check what method a given method is overriding?

### ISSUE THREAD

**Issue by GarfieldJiang** [jbevain/cecil#553]
For example, I want to find all the implementations of a method in a base class or an interface.

**Comment by jbevain** [comment]
I'm afraid there's nothing built-in with Cecil. You'll need to browse the type hierarchy. The Mono Linker does it like this:

https://github.com/mono/linker/blob/master/linker/Linker.Steps/TypeMapStep.cs

**Comment by GarfieldJiang** [comment]
Thanks, this is practical enough.
