### ISSUE TITLE
Attribute ordering is not preserved when rewriting

### ISSUE THREAD

**Issue by SteveGilham** [jbevain/cecil#558]
Attribute ordering can be significant in some cases e.g. Swagger based applications; rewritten assemblies change this ordering.

Example assembly
```
using System;

namespace CecilAttr
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public sealed class AAttribute : Attribute
    {
        public string Value { get; set; }
    }

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public sealed class ZAttribute : Attribute
    {
        public string Value { get; set; }
    }

    public class Class1
    {
        [Z(Value = "First"), A(Value = "Begin"), Z, A(Value = "End")]
        public static int Example2() { return 23; }
    }
}
```

Rewrite by simply 
```
            var def = AssemblyDefinition.ReadAssembly([path to above assembly]);
            def.Write([somewhere else]);
```
Decompile the rewritten assembly e.g. by ILSpy to see the reordering
```
public class Class1
{
	[Z]
	[A(Value = "End")]
	[Z(Value = "First")]
	[A(Value = "Begin")]
	public static int Example2()
	{
		return 23;
	}
}
```

It doesn't appear to be a simple reversal, nor any simple sort-by-typename -- different inputs give different re-orderings

**Comment by SteveGilham** [comment]
Root cause is that `Array.Sort` is not a stable sort, and is explicitly documented as such.

**Comment by SteveGilham** [comment]
Stripped-down examble using Swagger helpfully provided here -- [https://github.com/jedigo/SwaggerAttributes](https://github.com/jedigo/SwaggerAttributes)

**Comment by jbevain** [comment]
Good catch Steve, thanks for reporting this.
