### ISSUE TITLE
Google-Group rejecting messages

### ISSUE THREAD

**Issue by hultqvist** [jbevain/cecil#561]
Hi,

I wrote a post to the mono-cecil googlegroups.com forum.
Even though I wrote the message on the web page while logged in to my google account I got the following email back:

> Message rejected. See https://support.google.com/mail/answer/69585 for more information.

**Comment by jbevain** [comment]
Hello,

This is weird. The google group is setup to retain emails until I approve them to limit spam, but I don't see anything recent. Could you try again?
