### ISSUE TITLE
Flag test for MethodCallingConvention?

### ISSUE THREAD

**Issue by hultqvist** [jbevain/cecil#562]
`MethodCallingConvention` doesn't appear to be flag type.

https://github.com/jbevain/cecil/blob/eea822cad4b6f320c9e1da642fcbc0c129b00a6e/Mono.Cecil/MethodCallingConvention.cs#L13-L21

In that case the following test

https://github.com/jbevain/cecil/blob/232772d59e03c3f32cce5418b5ddc392fab7d994/Mono.Cecil/MethodReference.cs#L184-L187

could be simplified into

`return self.CallingConvention == MethodCallingConvention.VarArg;`

**Comment by jbevain** [comment]
Thanks for reporting this!
