### ISSUE TITLE
MemberReference.Resolve returns wrong Module.

### ISSUE THREAD

**Issue by zezba9000** [jbevain/cecil#571]
Running into a bug where MemberReference.Resolve is resolving the wrong module.

Have a custom .NET Core corelib called: IL2X.Portable.CoreLib which implements System.Int32 but MemberReference.Resolve resolves it out to be System.Private.CoreLib::System.Int32
So its trying to use the official .NET Core one instead of the one my test app is linked to.

This is being tested with: https://github.com/reignstudios/IL2X
Hitting the issue while running "IL2X.Core.Test"

**Comment by zezba9000** [comment]
Trying to see if I can fix the bug. However having a hard time building the Mono.Cecil solution for .NET Standard.

**Comment by zezba9000** [comment]
Found the bug in "Mixin.IsCoreLibrary" I need the ability to add a custom core lib.
Fixed the issue but need to do a pull request.

I can do a pull request but not sure how you would like this done...

In my hack I've modified:
* TypeSystem to have "public static string CustomCoreLibName;"
* In Mixin.IsCoreLibrary added "|| (TypeSystem.CustomCoreLibName != null && name == TypeSystem.CustomCoreLibName);"

Let me know where you would like to expose CustomCoreLibName and I would be happy to make a pull request.

**Comment by jbevain** [comment]
Hey @zezba9000,

Thanks for filing this issue, that's an interesting use case!

I think the best way to address this would be to use the same pattern we use for the metadata provider and the symbols provider. We would define a ITypeSystemProvider interface that creates a TypeSystem from a module, expose that in ReaderParameters / ModuleParameters.

**Comment by zezba9000** [comment]
Ok will fork and take a look at adding it in the fashion you suggest when I get a chance. Tnx!

**Comment by zezba9000** [comment]
Without knowing much how Mono.Cecil hooks itself up I'm a bit fuzzy on how this is expected to work.

Are you saying something other than MemberReference.Resolve() would be called?
Where would I define my custom corelib name with the approach you suggest?

**Comment by jbevain** [comment]
Hey, that's pretty old, so I'll be closing this. Feel free to re-open if that's still a problem for you. Thanks!

**Comment by zezba9000** [comment]
I had been just using a modified version for my tests but ya sounds good.
