### ISSUE TITLE
LookupToken doesn't work for Properties and Events

### ISSUE THREAD

**Issue by KirillOsenkov** [jbevain/cecil#572]
I get passed a property token and I want to look up that property from the module to read the custom attributes on that property. Unfortunately all I have is that token, I don't get the declaring type or name or anything else.

However I've found that `LookupToken` has a switch statement that doesn't support property tokens. Is this by design? Feels like if dnSpy can lookup a token, so should Cecil.

Absent that, what are the potential workarounds?

**Comment by jbevain** [comment]
Hey Kirill,

I don't think there's a technical reason preventing this. It's just that nobody cared about the scenario before :)

**Comment by KirillOsenkov** [comment]
:+1: I worked around by finding a way to pass declaring type token and then finding the property in the list, so I'm not immediately blocked. But leaving this issue open maybe someone will have time to add this at some point.

**Comment by jbevain** [comment]
FYI, the reason it's not been implemented is that properties and events are definition only and can't be referenced across modules.

But I imagine that if you have a scenario like an assembly opened with System.Reflection, and you have a PropertyInfo, you might want to lookup the PropertyDefinition from its token.

**Comment by jbevain** [comment]
Looking at how things are implemented, we don't have an optimized way to implement this unfortunately, so I'll be closing this for now.

Thanks!
