### ISSUE TITLE
Get TypeDefinition from TypeReference then the TR is array

### ISSUE THREAD

**Issue by cm4ker** [jbevain/cecil#579]
I just push small repro what I mean.

```csharp
var ad = AssemblyDefinition.CreateAssembly(
                new AssemblyNameDefinition("Debug", new Version(1, 0)), "Debug", ModuleKind.Dll);
var md = ad.MainModule;

var correct = md.TypeSystem.Int32.Resolve(); // System.Int32
var incorrect = new ArrayType(md.TypeSystem.Int32).Resolve(); // System.Int32
```

I get the System.Int32 TypeDefinition. Is this correct behaviour? 

I'm expecting the System.Int32[] type.

**Comment by jbevain** [comment]
Yes, that's the correct behavior, also I can see why it's not what you expect.

Resolve returns a `TypeDefinition`, so it can not work with any type spec, like an array. There's no such thing as an ArrayDefinition.
