### ISSUE TITLE
Resolve() not self-aware?

### ISSUE THREAD

**Issue by Draethorian** [jbevain/cecil#580]
Yeah so it seems that when I try to do a couple of module.ImportReference() and call a Resolve from those references Cecil doesn't know that the dll is already loaded. in that case its Assembly-CSharp-Editor.dll which actually is the moduleDefinition itself.

Because either it can't find it (AssemblyResolutionException: when I don't add the dir to the resolver's searchDirs) or it tries to read the file again, which causes an IOException: Sharing violation and I don't know how to fix those issues...

Stacktrace:

IOException: Sharing violation on path C:\Users\Chris\OneDrive\InDepthInspector\Library\ScriptAssemblies\Assembly-CSharp-Editor.dll
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.BaseAssemblyResolver.GetAssembly (System.String file, Mono.Cecil.ReaderParameters parameters) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.BaseAssemblyResolver.SearchDirectory (Mono.Cecil.AssemblyNameReference name, System.Collections.Generic.IEnumerable`1[T] directories, Mono.Cecil.ReaderParameters parameters) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.DefaultAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.MetadataResolver.Resolve (Mono.Cecil.TypeReference type) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.ModuleDefinition.Resolve (Mono.Cecil.TypeReference type) (at <44b9fac84fdf4d7aa793f1af5747c140>:0)
Mono.Cecil.TypeReference.Resolve () (at <44b9fac84fdf4d7aa793f1af5747c140>:0)

**Comment by Draethorian** [comment]
Alright, looks like a weird fix to me, but this actually solve self-referencing for me. I was wondering why my dll references itself as soon I started to reference dynamically (which could also include classes from the dll itself). But I guess @jbevain didn't think about that (yet). Now the only thing that could break my neck would be some irresolvable circular dependency that is based on this weaving "technique" ...

        // Guess we could use SafeResolve for any Kind of X-Reference
        // that needs to be resolved to a X-Definition
        private TypeDefinition SafeResolve(TypeReference typeRef)
        {
            foreach (TypeDefinition typeDefinition in module.GetTypes())
            {
                if (typeDefinition.Namespace == typeRef.Namespace &&
                    typeDefinition.Name == typeRef.Name)
                {
                    return typeDefinition;
                }
            }
            return typeRef.Resolve();
        }

**Comment by jbevain** [comment]
The way to fix those scenarios is to share a common Assembly resolver where your assemblies are properly registered so each assembly is loaded uniquely in the assembly resolver.
