### ISSUE TITLE
Writing Symbols

### ISSUE THREAD

**Issue by apobekiaris** [jbevain/cecil#581]
Hello,

I am using this code to write an assembly
```cs
var readerParameters = new ReaderParameters();
            readerParameters.ReadSymbols = true;
            
            var fileName = @"";
            var assemblyDefinition = ModuleDefinition.ReadModule(
                fileName,
                readerParameters);
            var writerParameters = new WriterParameters() {WriteSymbols = true};

            assemblyDefinition.Write(writerParameters);
```

the assembly is source indexed using the srctool, however after the above call the srctool reports that my assembly is not indexed anymore.

**Comment by apobekiaris** [comment]
I am not sure that this lib can do anything, although it would be nice to for this case. My solution was to query the symbols before writing them and reindex them after cecil patched them.

**Comment by jbevain** [comment]
Hi @apobekiaris,

Yeah right now I don't have plans to support talking to a debugger server. Good to hear that you're unlocked though!
