### ISSUE TITLE
Assemblies saved with DeterministicMvid and portable pdbs cannot be loaded

### ISSUE THREAD

**Issue by mrvoorhe** [jbevain/cecil#583]
I was using `DeterministicMvid` in monolinker and had an assembly with portablepdbs.  monolinker was able to strip and write the assembly without issue.  However, if anything tries to read that assembly back in `ModuleDefinition.ReadSymbols()` throws a `SymbolsNotMatchingException` exception.  See https://github.com/jbevain/cecil/issues/582 for more details.

**Comment by mrvoorhe** [comment]
Here is a PR to monolinker where I add tests that can reproduce this bug and https://github.com/jbevain/cecil/issues/582

https://github.com/mono/linker/pull/591

The tests that had to ignored were
https://github.com/mono/linker/pull/591/files#diff-9e1723272bec2ea79732459e86209708
https://github.com/mono/linker/pull/591/files#diff-69dc58f47a0fd2c82f2c55326cae2177

If you wanted to run the tests remove the `[IgnoreTestCase ("Requires cecil updated with fix for https://github.com/jbevain/cecil/issues/583")]`

**Comment by jbevain** [comment]
Fixed by #587.
