### ISSUE TITLE
"Failed to resolve" error on macOS

### ISSUE THREAD

**Issue by aalmada** [jbevain/cecil#591]
I'm using the following code to create an instance of a `CustomAttribute` to add `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to a method:

```csharp
    CustomAttribute MethodImplAttribute(MethodImplOptions options)
        => new CustomAttribute(
            ModuleDefinition.ImportReference(typeof(MethodImplAttribute).GetConstructor(new[] { typeof(MethodImplOptions) })))
            {
                ConstructorArguments = {
                    new CustomAttributeArgument(ModuleDefinition.ImportReference(typeof(MethodImplOptions)), options),
                }
            };
```

The method is created using the following:

```csharp
var newMethod = new MethodDefinition(method.Name, MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.Static, returnType)
{
    CustomAttributes = {
        GeneratedCodeAttribute(),
        MethodImplAttribute(MethodImplOptions.AggressiveInlining),
        ExtensionAttribute(),
    },
    Parameters = {
        new ParameterDefinition("source", ParameterAttributes.None, type),
    },
};
```

It works fine with _VS2019_ on _Windows 10_ but I'm getting the error "Failed to resolve System.Runtime.CompilerServices.MethodImplOptions" with _VSCode_ on _macOS 10.14.5_.

I'm referencing `<PackageReference Include="FodyHelpers" Version="5.0.6" />`.

Do you know of any workaround?

**Comment by SimonCropp** [comment]
@aalmada when writing a fody addin you should not use `ModuleDefinition.ImportReference(typeof(MethodImplOptions)),` since that imports the type from the current executing runtime (what msbuild is running in), instead of the runtime of the target assembly.

you should leverage`GetAssembliesForScanning` and `BaseModuleWeaver.FindType `  https://github.com/Fody/Home/blob/master/pages/addin-development.md#basemoduleweavergetassembliesforscanning

**Comment by aalmada** [comment]
@SimonCropp Thank you so much for replying in such a short time. I'm only replying now because yesterday I was waiting for my son to come out of surgery. His recovering well and I'm killing time coding. ;)

I had tried setting `GetAssembliesForScanning` but didn't know I had to use `FindType`. 

While looking for how to get the constructor I found that `MethodDefinition` has an `AggressiveInlining` property that can be set. I'm now using it instead of my `MethodImplAttribute` factory.

I'm still using the following code to set the `GeneratedCodeAttribute` with no issues on either platform:

```csharp
CustomAttribute GeneratedCodeAttribute()
{
    var assembly = GetType().Assembly;
    var assemblyName = assembly.GetName().Name;
    var assemblyVersion = ((System.Reflection.AssemblyFileVersionAttribute)Attribute.GetCustomAttribute(assembly, typeof(System.Reflection.AssemblyFileVersionAttribute), false)).Version;
    return new CustomAttribute(
        ModuleDefinition.ImportReference(typeof(System.CodeDom.Compiler.GeneratedCodeAttribute).GetConstructor(new[] { typeof(string), typeof(string) })))
        {
            ConstructorArguments = {
                    new CustomAttributeArgument(ModuleDefinition.TypeSystem.String, assemblyName),
                    new CustomAttributeArgument(ModuleDefinition.TypeSystem.String, assemblyVersion),
                }
        };
}
```

**Comment by aalmada** [comment]
For future reference, I'd like to clarify some thing.

`[ModuleDefinition.ImportReference(typeof(MethodImplOptions))]` is an attribute in C# but it's converted into a keyword in IL. The property `MethodDefinition.AggressiveInlining` should be used to set it.

The code I posted above works but I found that it references the wrong assembly when using `netstandard`. As suggested above by @SimonCropp, `GetAssembliesForScanning` and `BaseModuleWeaver.FindType` should be used instead.

Here's the code I now use to create singleton instances of `ExtensionAttribute` and `GeneratedCodeAttribute`.

```csharp

static CustomAttribute extensionAttribute;
static CustomAttribute generatedCodeAttribute;

public override IEnumerable<string> GetAssembliesForScanning()
{
    yield return "netstandard";
}

CustomAttribute ExtensionAttribute()
    => LazyInitializer.EnsureInitialized(ref extensionAttribute, () =>
    {
        var type = FindType(typeof(System.Runtime.CompilerServices.ExtensionAttribute).FullName);
        var constructor = type.Methods.First(method => 
            method.IsConstructor && 
            !method.HasParameters);
        return new CustomAttribute(ModuleDefinition.ImportReference(constructor));
    });

CustomAttribute GeneratedCodeAttribute()
    => LazyInitializer.EnsureInitialized(ref generatedCodeAttribute, () =>
    {
        var type = FindType(typeof(System.CodeDom.Compiler.GeneratedCodeAttribute).FullName);
        var constructor = type.Methods.First(method => 
            method.IsConstructor && 
            method.Parameters.Count == 2 &&
            method.Parameters[0].ParameterType.FullName == "System.String" &&
            method.Parameters[1].ParameterType.FullName == "System.String");
        var assemblyName = GetType().Assembly.GetName().Name;
        var assemblyVersion = ((System.Reflection.AssemblyFileVersionAttribute)Attribute.GetCustomAttribute(GetType().Assembly, typeof(System.Reflection.AssemblyFileVersionAttribute), false))?.Version ?? string.Empty;
        return new CustomAttribute(ModuleDefinition.ImportReference(constructor))
            {
                ConstructorArguments = {
                    new CustomAttributeArgument(ModuleDefinition.TypeSystem.String, assemblyName),
                    new CustomAttributeArgument(ModuleDefinition.TypeSystem.String, assemblyVersion),
                }
            };
    });
```
