### ISSUE TITLE
[Question]How do you patch at runtime ?

### ISSUE THREAD

**Issue by Nightshades1** [jbevain/cecil#592]
Hello, I would like to know if it is possible to achieve a patch at runtime.

This is a unity game that i'm hacking on, i have my own mod-hack that is injected with an injector and i can load/unload my hack, that's why i would like if it was possible to do a runtime patch on a method, of an assembly that is ALREADY EXECUTED.

Because it's nice to do a "normal" patch on the file (example: Assembly-CSharp.dll), the problem is that each time i unload my hack (which is a MonoBehavior GameObject in unity) recompile "my hack" the assembly version change as it's a new build and then my hook inside Assembly-CSharp.dll doesn't work anymore, in fact it should call MyHackedNameSpace.TheClass.TheMethod(Args) but it doesn't do anything since it was previously referencing the "older dll".

So yes, i am stuck and any directions would be welcome, thanks.

**Comment by jbevain** [comment]
I'm afraid Cecil can not be used to change an assembly after it has been loaded by a runtime. Best of luck!
