### ISSUE TITLE
VariableDefinition,Name Property and Determining VB Resumables

### ISSUE THREAD

**Issue by cropper1991** [jbevain/cecil#593]
I know this post is going to be very similar to that of #386 but there is a very specific reason why we require this. We are utilising this library to perform code weaving to aid in exception reporting by including variable names, amongst other details.

Unfortunately because of the removal of the Name property, we now need a different way of determining the following factors:

1. Is it a VB Resumable (e.g. is it a IAsyncStateMachine Field)
2. If it is we need to locate the appropriate field based on this
3. Need to ensure that we don't capture any variables that are being used within a "with" statement (names start with $w)
4. Need to exclude variables which don't have names from our code weaving process
5. We also need to be able to get the Variable Name (from the root scope of a method), and load it onto the stack during the IL Injection Phase

**Comment by jbevain** [comment]
The concept of a variable name hasn't disappeared, however as part of the breaking changes made in 0.10 I used this opportunity to fix a design issue.

In the metadata, which Cecil represents, there's no concept of a name to a variable.

The name of a variable is only present in the debug symbols. And to make matter worse, it's possible to find scenarios where a compiler uses 1 IL variable, and reuses that as a backing store for N independent variables semantically, where those would have different names depending on the scope.

You need to get the name from the debug information of the method you're working on.

**Comment by cropper1991** [comment]
Right okay, I'll utilise additional libraries to obtain this symbol information, and therefore enable it to utilise 0.10 of Mono.Cecil Library.
