### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by hbadusumilli** [jbevain/cecil#595]
I was using cecil to read over 35,000 .dll files and it was taking approx. 7 minutes to read all those files. I think that was essentially happening because Cecil was loading up all the data related to the module. However, I was wondering if there is a way in which I can load partial data associated with the module.

**Comment by bartelink** [comment]
Can you add more context as to what your objective is?

While that's of paramount importance, other questions as to what you've established and/or what your constraints and/or needs are might help. Are you doing this processing in parallel? where are the files how big are they?

**Comment by hbadusumilli** [comment]
My objective is to get the types and assembly references from each file. All these files are in a directory and each file is about 20MB.

**Comment by SimonCropp** [comment]
what do you do with each type?

**Comment by hbadusumilli** [comment]
I get types from two different packages and check if certain types from package 2 exist in package 1.

**Comment by hbadusumilli** [comment]
I ran the program without adding any further functionality besides the above for loop and it took about 7 mins. Is there a way I could make reading a module faster?

**Comment by bartelink** [comment]
7 mins doesn't sound out of bounds for reading and processing that much stuff if you're simply directly doing what you say.

Have you used a profiler and/or added instrumentation to satisfy yourself that this is definitely the bottleneck? is there any way you can cache some things to avoid some work? Are you using parallelism ? Perhaps if you can give pseudocode as to your algorithm and info regarding if/whether/why you feel such techniques can not be relevant, others may be able to offer more insight.

Have you made a benchmark.net test for what you've identified as the core cost ?

**Comment by hbadusumilli** [comment]
Yes, I have tested it.

I ran the program with just this piece of code and that itself took approx. 7 minutes which makes it clear that reading the files is what was slowing down the program.
```
foreach (var file in files)
{
    using (AssemblyDefinition assemblyDefinition = AssemblyDefinition.ReadAssembly(file))
    {
        //do nothing
    }
}
```

**Comment by SimonCropp** [comment]
try this

```
var readerParameters = new ReaderParameters
{
    AssemblyResolver = new DefaultAssemblyResolver(),
};

foreach (var file in files)
{
    using (AssemblyDefinition assemblyDefinition = AssemblyDefinition.ReadAssembly(file,readerParameters))
    {
        //do nothing
    }
}
```

**Comment by hbadusumilli** [comment]
I tried doing it the above way, but it took about the same time.

**Comment by hbadusumilli** [comment]
I tried that, but it didn't make a huge difference. Please let me know if there is anything else that could optimize this further.

**Comment by hbadusumilli** [comment]
Is there a way I could just open the file and just read the assembly references without reading everything else?

**Comment by bartelink** [comment]
Does a `Parallel.ForEach` and/or other form of concurrency offer more perf? I suspect there's a strong chance it's IO bound but additional processing beyond loading of high level tables is lazy in nature, i.e. there may not be an issue with the efficiency of the processing Cecil is doing after the data gets loaded in. The other obvious question to ask is, have you attached a profiler and ascertained what's taking the bulk of the processing time?

**Comment by jbevain** [comment]
I second what @bartelink is suggesting. By default, Cecil will read a bunch of memory blocks from assemblies but will only construct an in memory object representation upon access.

Profiling would give us a chance to look at what's actually taking a lot of time and see if there's room for improvement.

If all you're doing is reading assembly references, the library `System.Reflection.Metadata` might be a better tool for that scenario. The API is more cumbersome to use, but you'll get a faster access to the single piece of metadata you're interested in.
