### ISSUE TITLE
performance when ConstructorArguments 

### ISSUE THREAD

**Issue by apobekiaris** [jbevain/cecil#596]
I am trying to create an assembly mapper to a different interface only format. So for each type I have an interface with the same propertyinfo names and attributes. However the customAttribute.ConstructorArguments call is awfully slow. Looking at the code I see that it calls Resolve each time. Is there a way to speed this up?

**Comment by jbevain** [comment]
`Resolve` is called each time you access a property in CustomAttribute but will return early if the attribute is already resolved.

It's hard to provide meaningful insight without meaningful data, could you share profiling sessions?

**Comment by jbevain** [comment]
Feel free to re-open with data we could use to optimize this code path.
