### ISSUE TITLE
How would I insert a byte array?

### ISSUE THREAD

**Issue by binarysnake** [jbevain/cecil#597]
How would I insert a byte array into an already existing method?

**Comment by SteveGilham** [comment]
The most direct way to find out what you need to do for any IL manipulation like this is to create a before and after form of the method in an exploratory assembly, and see what changes in the IL.  In this case, to just declare an empty (default valued) array it's simply

* load the I4 length of the array
* invoke the `newarr` operation on the array type

**Comment by jbevain** [comment]
Steve is 100% correct :) Thanks!
