### ISSUE TITLE
How to convert delegate to intptr with AOT compatibility

### ISSUE THREAD

**Issue by sekkit** [jbevain/cecil#601]
```cs
        internal static IntPtr GetThunk(MethodInfo method, string funcType = null)
        {
            Type dt;
            if (funcType != null)
                dt = typeof(Interop).GetNestedType(funcType) as Type;
            else
                dt = GetPrototype(method.Name);
            if (dt != null)
            {
                Delegate d = Delegate.CreateDelegate(dt, method);
#if AOT
                IntPtr fp = Marshal.GetFunctionPointerForDelegate(d);
#else
                IntPtr tmp = Marshal.AllocHGlobal(IntPtr.Size);
                Thunk cb = new Thunk(d);
                Marshal.StructureToPtr(cb, tmp, false);
                IntPtr fp = Marshal.ReadIntPtr(tmp, 0);
                Marshal.FreeHGlobal(tmp);
#endif
                keepAlive.Add(d);
                return fp;
            }
            return IntPtr.Zero;
        }
```
inside AOT macro:
IntPtr fp = Marshal.GetFunctionPointerForDelegate(d);
when run the program this line of code will trough error:
NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.
at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegateInternal (System.Delegate d) [0x00000] in <00000000000000000000000000000000>:0 
at System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate (System.Delegate d) [0x00000] in <00000000000000000000000000000000>:0 
at Python.Runtime.Interop.GetThunk (System.Reflection.MethodInfo method, System.String funcType) [0x00000] in <00000000000000000000000000000000>:0

NOW, I need to implement this Marshal.GetFunctionPointerForDelegate() in a AOT compatible way using Mono.Cecil, any idea with that?

**Comment by jbevain** [comment]
No idea, sorry, there's not a whole lot I can do without any context or anything that relates to Cecil!
