### ISSUE TITLE
PEVerify giving coded rid out of range after adding interface

### ISSUE THREAD

**Issue by safoster88** [jbevain/cecil#609]
Hi,

I've just started using cecil so I'm sure I must be missing something. I'm attempting to static weave the INotifyPropertyChanged interface onto objects that are decorated with a custom attribute.

I can weave the IL into the properties just fine, but as soon as I try to add the interface I get the following error for PEVerify: 
```
[MD]: Error (Structural): Table=0x00000009, Col=0x00000001, Row=0x00000003, has coded rid out of range.
1 Error(s) Verifying .\StaticWeaving.exe
```

I am using the following code to implement the interface on an AfterBuild task:

```
using (var notifyPropertyChangedAssembly = AssemblyDefinition.ReadAssembly(typeof(INotifyPropertyChanged).Assembly.Location))
                {
                    using (var assembly = AssemblyDefinition.ReadAssembly(AssemblyPath, new ReaderParameters { ReadWrite = true }))
                    {
                        foreach (var type in assembly.MainModule.Types)
                        {
                            if (type.CustomAttributes.Any(x => x.Constructor.DeclaringType.FullName == typeof(NotifyPropertyChangedAttribute).FullName))
                            {
                                if (!type.Interfaces.Any(x => x.InterfaceType.FullName == typeof(INotifyPropertyChanged).FullName))
                                {
                                    Log.LogMessage($"{type.FullName} has {nameof(NotifyPropertyChangedAttribute)} but no {nameof(INotifyPropertyChanged)} implementation. Weaving...");

                                    var notifyPropertyChangedType = notifyPropertyChangedAssembly.MainModule.Types.FirstOrDefault(x => x.FullName == typeof(INotifyPropertyChanged).FullName);

                                    Log.LogMessage(notifyPropertyChangedType.FullName);

                                    type.Interfaces.Add(new InterfaceImplementation(notifyPropertyChangedType));
                                }
                            }
                        }

                        assembly.Write();
                    }
                }
```

**Comment by SimonCropp** [comment]
@safoster88 do you get any errors if you peverify the assembly prior to weaving?

**Comment by safoster88** [comment]
@SimonCropp No, the assembly is just fine prior to implementing the interface.

I have another section of code that directly weaves in IL into the properties and that works fine and can be verified after.

I tried commenting out that code to test the interface code in isolation, but i still get the peverify error.

I have a github repo for the project here if you'd like to clone and have a look: https://github.com/safoster88/static-weaving

**Comment by SimonCropp** [comment]
this is wrong

```

                using (var notifyPropertyChangedAssembly = AssemblyDefinition.ReadAssembly(typeof(INotifyPropertyChanged).Assembly.Location))
```

that will use the current runtime of msbuild to find the assembly location of INotifyPropertyChanged. u need to use the current reference assemblies in msbuild to find INotifyPropertyChanged

**Comment by safoster88** [comment]
@SimonCropp Thanks!

How could I go about doing that? I thought I'd have to reference the component model assembly in order to implement the interface (since that's where it's located).

**Comment by SimonCropp** [comment]
try using the `@(ReferencePath)` to extract the required assembly. like is done here https://github.com/Fody/Fody/blob/master/Fody/Fody.targets#L48

**Comment by SimonCropp** [comment]
>  I thought I'd have to reference the component model assembly in order to implement the interface (since that's where it's located).

u need to make the distinction between "the current msbuild runtime" and the "runtime of the target assembly". the "msbuild runtime" may not match the "runtime of the target assembly". when u call `typeof(INotifyPropertyChanged).Assembly` that gives u the assembly of the current msbuild runtime. you want the assembly that the target assembly references

**Comment by safoster88** [comment]
Sorry for all the questions, how can I get a list of the assembly references that my target assembly has?

**Comment by SimonCropp** [comment]
pass in `@(ReferencePath)` to your task. then split by ';' https://github.com/Fody/Fody/blob/master/FodyIsolated/AssemblyReferenceFinder.cs

**Comment by safoster88** [comment]
Thanks a bunch. I'll give that a try and replace the using with that path and let you know if it fixes it.

**Comment by SimonCropp** [comment]
BTW have u seen this https://github.com/Fody/PropertyChanged/  ?

**Comment by safoster88** [comment]
@SimonCropp I am both simultaneously overjoyed and dismayed.

**Comment by SimonCropp** [comment]
well it is MIT. so feel free to take the parts u need

**Comment by SimonCropp** [comment]
"dismayed" ?
