### ISSUE TITLE
Public GenericParameter constructor that takes context-free position

### ISSUE THREAD

**Issue by jnm2** [jbevain/cecil#612]
In a project using Mono.Cecil to write IL, I need to specify member references such as ``System.Collections.Generic.Dictionary`2<string, string>::.ctor(class System.Collections.Generic.IEqualityComparer`1<!0>)`` Because the corresponding reference assemblies may not be available at the time, I'm not loading mscorlib.dll/System.Collections.dll/netstandard.dll etc. Just emitting the correct assembly name reference (if needed) and the correct IL. That requires me to construct the type specification for ``System.Collections.Generic.IEqualityComparer`1<!0>`` without having a GenericParameterCollection from the reference assembly to set the generic parameter position.

The only option so that the project is not blocked is to use reflection to get the Position property set to something other than -1 which of course serialization chokes on:

```cs
var genericParameter0 = (GenericParameter)typeof(GenericParameter)
    .GetConstructor(
        BindingFlags.NonPublic | BindingFlags.Instance,
        null,
        new[] { typeof(int), typeof(GenericParameterType), typeof(ModuleDefinition) },
        null)
    .Invoke(new object[] { 0, GenericParameterType.Type, module });

// Instantiate IEqualityComparer<> with Dictionary<,>'s TKey
var equalityComparer = new TypeReference(
    "System.Collections.Generic",
    "IEqualityComparer`1",
    module,
    scope: assemblyContainingSystemCollections);

var equalityComparerInstantiation = new GenericInstanceType(equalityComparer)
{
    GenericArguments = { genericParameter0 }
};


il.Emit(OpCodes.Newobj, new MethodReference(
    ".ctor",
    returnType: dictionaryField.Module.TypeSystem.Void,
    declaringType: dictionaryField.FieldType)
{
    HasThis = true,
    Parameters =
    {
        new ParameterDefinition(module.ImportReference(equalityComparerInstantiation))
    }
});
```

Ideally, this constructor would be public:

https://github.com/jbevain/cecil/blob/12da1bf7e0e10278e05eeb23adfc72760bbb6668/Mono.Cecil/GenericParameter.cs#L188-L198

```diff
namespace Mono.Cecil
{
    public sealed class GenericParameter : TypeReference, ICustomAttributeProvider
    {
        public GenericParameter(IGenericParameterProvider owner);

        public GenericParameter(string name, IGenericParameterProvider owner);

+       public GenericParameter(
+           int position,
+           GenericParameterType type,
+           ModuleDefinition module);
    }
}
```

Does this sound good to you?

**Comment by jbevain** [comment]
It's hard to say without looking more at what you're doing, but this should not be needed. Generic contexts are working with references and definitions.

Could you show more of what you're doing? You're not using `genericParameter0` in the sample you posted. And the comment:

```
// Instantiate IEqualityComparer<> with Dictionary<,>'s TKey
var equalityComparerInstantiation = new TypeReference(
```

Feels wrong, an instantiation would be a GenericInstanceType.

**Comment by jnm2** [comment]
Oops, I left out the GenericInstanceType part. I fixed it above. Here's that along with more of what I'm doing with it:

```cs
// Instantiate IEqualityComparer<> with Dictionary<,>'s TKey
var equalityComparerInstantiation = new GenericInstanceType(equalityComparer)
{
    GenericArguments = { genericParameter0 }
};

// Emit a call to the Dictionary`2 constructor with the signature
// void (System.Collections.Generic.IEqualityComparer`1<!0>)
il.Emit(OpCodes.Newobj, new MethodReference(
    ".ctor",
    returnType: dictionaryField.Module.TypeSystem.Void,
    declaringType: dictionaryField.FieldType)
{
    HasThis = true,
    Parameters = { new ParameterDefinition(equalityComparerInstantiation ) }
});
```

All the type references and method references I'm constructing are not from loaded assemblies. I don't have the assemblies available to load, and if I did, that would be a lot of complexity.

All I'm interested in doing is emitting this IL:

```
newobj instance void class [System.Private.CoreLib]System.Collections.Generic.Dictionary`2<string, string>::.ctor(class [System.Private.CoreLib]System.Collections.Generic.IEqualityComparer`1<!0>)
```

and anything more than that is getting in the way.

**Comment by jbevain** [comment]
I understand how that could be not convenient for your particular use case but right now Cecil pretty much guarantees the coherence of the object model, which that change would break, so I'll be closing this.

Thanks!

**Comment by jnm2** [comment]
@jbevain Would it break the coherence of the object model though? .NET Core 2.1 added Type.MakeGenericMethodParameter(int index) etc. (API review link and PR links: https://github.com/dotnet/corefx/issues/16567#issuecomment-325830190)

Is the System.Type object model now broken? It must be a matter of perspective somehow.

Obviously I find this disappointing since I have 20% more work to do on an already-large project as a result, versus a keyword change in Cecil. But that's something you have to be prepared for, of course.

**Comment by jbevain** [comment]
Cecil has no ties to System / System.Reflection, and right now enforces a contract where you can compare definitions, including type parameters, by object identity. So yes, providing this API to create new instance of GenericParameter breaks that.

If Cecil doesn't work for your scenario it's perfectly fine, I suggest looking at the variety of managed reader and writers.
