### ISSUE TITLE
MethodReference.Resolve returns different objects

### ISSUE THREAD

**Issue by tom-englert** [jbevain/cecil#613]
After updating cecil via fody (https://github.com/Fody/Fody/issues/734) I have experienced the following:

`MethodReference.Resolve()` (im my case only on PInvoke methods) returned a different `MethodDefinition` object than enumerating the methods on the type.

Since I had used the `MethodDefinition` as dictionary key, those methods now got processed twice.

Is it expected to have two different `MethodDefinition` objects for the same method? Or is this a bug in cecil?

**Comment by SimonCropp** [comment]
@tom-englert i just debugged into a weaver and cant seem to replicate 

![image](https://user-images.githubusercontent.com/122666/63636796-a4572480-c6b7-11e9-9609-9b4062c1ca31.png)

**Comment by tom-englert** [comment]
@SimonCropp as i wrote it only happened with a bunch of PInvoke stubs, not all methods. If this is considered a bug, I will prepare something to reproduce it.

**Comment by SimonCropp** [comment]
> it only happened with a bunch of PInvoke stubs, not all methods

sorry i missed that

**Comment by tom-englert** [comment]
@SimonCropp IMO this is a bug, since it has been working in older versions of cecil. Would you agree with this?

**Comment by SimonCropp** [comment]
> is a bug, since it has been working in older versions of cecil

that was my assumption. hence i was trying to debug into it :)

**Comment by jbevain** [comment]
That does feel like a bug. I'd love a repro that doesn't depend on Fody to investigate.

**Comment by tom-englert** [comment]
OK, I will prepare this.

**Comment by tom-englert** [comment]
https://github.com/tom-englert/FodyTools
Branch: cecil#613
Failing tests: ILMerge and ILMerge2

Branch: cecil#613_a
This is the previous version using an older cecil that works fine.

**Comment by tom-englert** [comment]
OK, this was only introduced to handle NetFramework/NetStandard differences. 
I have removed all custom assembly resolvers, what fixes ILMerge.
Without assembly resolver it's expected that ILMerge2 fails on netcoreapp, but it still fails for net472 with the described issue.

**Comment by tom-englert** [comment]
@jbevain And now both method definitions are from the same module
![image](https://user-images.githubusercontent.com/10229954/63833733-093ea300-c974-11e9-87e8-0ea318ab83c3.png)

**Comment by tom-englert** [comment]
@jbevain using the FullName as the key was the workaround. 
The original code (cecil#613_a) used the `MethodDefinition` as the key, but after upgrading Cecil it failed in PEVerify that complaint about duplicate methods, because the ImportMethod had processed the same method twice.
I'll try to reproduce exactly this case, and then come back...

**Comment by tom-englert** [comment]
No longer reproducible, I really must have confused myself with the two conflicting changes in assembly  resolving and method caching.

Sorry for bothering.

**Comment by jbevain** [comment]
No worries, glad you're unstuck!
