### ISSUE TITLE
Directly add to UserString heap?

### ISSUE THREAD

**Issue by Numbers11** [jbevain/cecil#619]
That's the question, I would need to directly add a value to the UserString heap. 

Of course I could add the strings I need as a static field to a class or something, but that seems unnecessary since from what I see the StringHeap writer already supports what I want to do, it just not seems to be exposed.

Is there maybe a hack to still implement that functionality without edititing the cecil code?

And maybe a suggestion, would it be within the scope of this module to expose more of the "under the hood" functionality already present?

**Comment by jbevain** [comment]
I'm afraid there's no API to do this. Maybe see if that's something you can do with dnlib?
