### ISSUE TITLE
How to tell if a TypeDefinition is a delegate?

### ISSUE THREAD

**Issue by m7nu3l** [jbevain/cecil#621]
Hi!

I previously searched for any other issue like this one and I did not have luck. My bad if this is already answered.

I would like to know how to determine if a given TypeDefinition is a delegate type. In the past, I used CCI and there is a property available for it. As far as I know, there is no such field in Cecil.

The CCI property is computed more or less in the following way:

`return TypeHelper.TypesAreEquivalent(typeDef.BaseTypeReference, typeDef.PEFileToObjectModel.SystemMulticastDelegate);`

I guess that the rationale is to check if the current TypeDefinition derives SystemMulticastDelegate. How would you do that in Cecil?

My intuition is that first I should have a TypeReference to SystemMulticastDelegate. Then, retrieve the base type of the TypeDefinition. If it is a delegate, I would expect it to be equal to SystemMulticastDelegate. Do you think this is correct? Is it safe to directly compare TypeReferences in Cecil? Is there any shortcut to a SystemMulticastDelegate type reference? How would you check if one type derives another one?

Thanks in advance.
Manuel.

**Comment by jbevain** [comment]
Hey,

Yeah a delegate is not really special from the metadata point of view. Just checking that the `.BaseType` of the `TypeDefinition` has a full name of `System.MulticastDelegate` should be good enough.
