### ISSUE TITLE
How to get declared interfaces

### ISSUE THREAD

**Issue by sungam3r** [jbevain/cecil#625]
I have 3 classes:
```c#
        public class StringList : List<string>
        {

        }

        public class StringListWithInterface1 : List<string>, IEnumerable<string>
        {

        }

        public class StringListWithInterface2 : List<string>, System.Collections.IEnumerable
        {

        }
```
For each `TypeDefinition` for those classes I want to get **only declared** interfaces on type, `publicType` is a `TypeDefinition` obtained from assembly:
```c#
 var arr = publicType.Interfaces.Select(i => i.InterfaceType.FullName).ToArray();
```
My results:

StringList:  empty array
StringListWithInterface1: `System.Collections.Generic.IEnumerable<System.String>`, `System.Collections.IEnumerable`
StringListWithInterface2: `System.Collections.IEnumerable`

Question is why does StringListWithInterface1 have `System.Collections.IEnumerable` interface?

```xml
   <PackageReference Include="Mono.Cecil" Version="0.11.0" />
```

**Comment by ltrzesniewski** [comment]
The short answer is that it's [what Roslyn generates](https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYAYAEMEBYDcqqMAzNnJgMrABOYAdgOYAyYAzsJiJqxwDw50APlQBvVAF8iaMvCq0GLdsADqYYAAsAkvWABTGgDMAhgGM9CLj2UCEwgDTYEJW8LGTppcvLpNeq9W1dAxNzCm5/VyFHHAA6AGEAewgIPVNgMET6NlicEncUCSA), and Cecil just exposes the metadata in the assembly.

The longer answer is that it doesn't seem to be mandated by ECMA-335, e.g. from II.12.1 (emphasis mine):

> Interfaces shall declare that they require the implementation of zero or more other interfaces. If one interface, A, declares that it requires the implementation of another interface, B, then A implicitly declares that it requires the implementation of all interfaces required by B. If a class or value type declares that it implements A, then all concrete instances shall provide implementations of the virtual methods declared in A and all of the interfaces A requires. **[Note: The class need not explicitly declare that it implements the interfaces required by A. end note]**

**BUT** it's necessary to list the interface in the `InterfaceImpl` metadata table (what Cecil uses to list the implemented interfaces) in order for implicit interface method implementations to work (II.12.2):

> - For the type T implements I1,…,In, n ≥ 0 the Ix are termed the **explicit interfaces** of the type and form an ordered list; the Ix are the interfaces listed in the `InterfaceImpl` (§22.23) table entries for T, ordered by row top-to-bottom. 
>
>  *[...]*
>
> - If the interface is an **explicit interface** of this class:
>   - If the class defines any **public virtual** methods whose name and signature match a virtual method on the interface, then add these to the list for that method, in **type declaration order** (see above). [Note: For an example where the order is relevant, see Case 6 in §12.2.1. end Note]

**Comment by jbevain** [comment]
Hello @sungam3r,

As @ltrzesniewski said, Cecil is simply returning what is generated by the C# compiler here.
If you need the exact set of interfaces used on the class, you'll need source access and something like Roslyn to look at the source code.
