### ISSUE TITLE
Main module being specified explicitly ?

### ISSUE THREAD

**Issue by virtyvoid** [jbevain/cecil#626]
Greetings.
I have been modding a dotnet assembly with help of Cecil (still learning it) and everything was fine until I loaded the modded assembly into the decompiler (dnSpy) and noticed one strange thing.
Main assembly module is getting specified explicitly in the type's generic arguments (enclosed with brackets). Injected method sig looks like this:
_(TestAssembly is the main assembly)_
```cs
instance void Testing (class [TestAssemblyTwo]TestAssemblyTwo.Class2`2<int32, class [TestAssembly]TestAssembly.Class1> dummy)
```
I have tried to recompile method right in the dnSpy and module in the second argument was gone:
```cs
instance void Testing (class [TestAssemblyTwo]TestAssemblyTwo.Class2`2<int32, class TestAssembly.Class1> dummy)
```

My test case code.
TestAssembly:
```cs
public class Class1{}
```
TestAssemblyTwo:
```cs
public class Class2<T1,T2>{}
```
And my method injector:
```cs
public static void Main(string[] args)
{
	// Main assembly (that i inject to)
	var asm1 = AssemblyDefinition.ReadAssembly(@"TestAssembly.dll");
	// Third-party assembly
	var asm2 = AssemblyDefinition.ReadAssembly(@"TestAssemblyTwo.dll");
	
	var clsOne = asm1.MainModule.GetType("TestAssembly.Class1"); // an empty type from main asm.
	var clsTwo = asm2.MainModule.GetType("TestAssemblyTwo.Class2`2"); // an empty generic type from third-party asm.
	var clsTwoGeneric = new GenericInstanceType(clsTwo);
	clsTwoGeneric.GenericArguments.Add(asm1.MainModule.TypeSystem.Int32);
	clsTwoGeneric.GenericArguments.Add(clsOne); // type from main asm
	
	var method = new MethodDefinition("Testing", MethodAttributes.Public|MethodAttributes.HideBySig, asm1.MainModule.TypeSystem.Void);
	method.Parameters.Add(new ParameterDefinition("dummy", ParameterAttributes.None, asm1.MainModule.Import(clsTwoGeneric)));
	method.Body.Instructions.Add(Instruction.Create(OpCodes.Ret));
	clsOne.Methods.Add(method);
	asm1.Write(@"TestAssembly_Result.dll");
}
```
I am doubt that it could be a bug since the produced code works fine, but i am a little worried if i am doing something wrong here.
Is this the intended behavior or i generate the code in a wrong way?

**Comment by jbevain** [comment]
Hello,

I just quickly went through the code, and noticed something weird:

```csharp
	var clsOne = asm1.MainModule.GetType("TestAssembly.Class1"); // an empty type from main asm.
	var clsTwo = asm2.MainModule.GetType("TestAssemblyTwo.Class2`2"); // an empty generic type from third-party asm.
	var clsTwoGeneric = new GenericInstanceType(clsTwo);
	clsTwoGeneric.GenericArguments.Add(asm1.MainModule.TypeSystem.Int32);
	clsTwoGeneric.GenericArguments.Add(clsOne); // type from main asm
```

You're mixing types from different modules, which sounds like a bug. Here, you're creating a `GenericInstanceType` based on `clsTwo`, which is defined in `asm2`. But then you add an argument `Int32` from `asm1`, and an argument `clsOne` from `asm1` also.

Given that you want to use the result in `asm1`, I suggest you do:

```csharp
	var clsTwoGeneric = new GenericInstanceType(asm1.MainModule.Import(clsTwo));
	clsTwoGeneric.GenericArguments.Add(asm1.MainModule.TypeSystem.Int32);
	clsTwoGeneric.GenericArguments.Add(clsOne); // type from main asm
```

And then you can use clsTwoGeneric whithout having to import it, as everything is scoped for `asm1`.

**Comment by virtyvoid** [comment]
Thanks for replying back.
Actually this thing with mixing types i did intentionally, because this is just a test case and in my real task (which is modifying a Unity game) i have to import various types from supplied mscorlib (TestAssemblyTwo as a dummy).

Your fix looks just fine and it helped. I just didn't think that way i could use Import in other ways like this.
Now i realize more. It was just a misuse of Import and I have to be more attentive when and where to use Import.

Thanks for pointing me at my problem, much appreciated.
