### ISSUE TITLE
After AssemblyDefinition.ReadAssembly + Write, PEVerify fails

### ISSUE THREAD

**Issue by kg** [jbevain/cecil#627]
I took mscorlib.dll from a current source build of mono and then ran it through an ```AssemblyDefinition.ReadAssembly``` + ```.Write``` pair, and after that the new output dll produces new errors when ```PEVerify.exe``` is run:

```
[token  0x02000606] Type load failed.
[token  0x02000607] Type load failed.
[token  0x02000609] Type load failed.
[token  0x0200060A] Type load failed.
[token  0x0200060B] Type load failed.
1345 Error(s) Verifying mscorlib.rewritten.dll
```

Is this expected? Does it just indicate a configuration issue? Running PEVerify on the original dll produces some errors but they seem harmless in comparison:

```
[MD]: Error: Method marked Abstract, Runtime, InternalCall or Imported must have zero RVA, and vice versa. [token:0x06003221]
[MD]: Error: Method marked Abstract, Runtime, InternalCall or Imported must have zero RVA, and vice versa. [token:0x06003223]
[MD]: Error: Method marked Abstract, Runtime, InternalCall or Imported must have zero RVA, and vice versa. [token:0x06003225]
145 Error(s) Verifying mscorlib.dll
```

The code:
```csharp

                var assemblyResolver = new DefaultAssemblyResolver();
                assemblyResolver.AddSearchDirectory(Path.GetDirectoryName(argv[0]));

                using (var def = AssemblyDefinition.ReadAssembly(argv[0], new ReaderParameters {
                    ReadWrite = true,
                    ReadingMode = ReadingMode.Immediate,
                    AssemblyResolver = assemblyResolver
                })) {
                    def.Write(argv[1] + ".tmp");
                }

                File.Copy(argv[1] + ".tmp", argv[1], true);
```

**Comment by leppie** [comment]
I am pretty sure mscorlib is a very special case. 

Try emit the 'rewritten' version to another directory, and keep the filename/modulename as mscorlib.

**Comment by kg** [comment]
You're right, thanks.

**Comment by kg** [comment]
Sorry, hit send too quick. Does this mean the verification error is misleading? I'm not sure if it's a bad thing that cecil is changing the assembly on a round-trip, though it sounds like in this case maybe it might be okay.

I'm specifically looking to round-trip system assemblies (think IL linker style) so I need to be sure that I'm not going to corrupt them due to using Cecil incorrectly or hitting a bug.

**Comment by leppie** [comment]
Surely you wont be roundtripping mscorlib or any runtime libs.

**Comment by kg** [comment]
I am

**Comment by jbevain** [comment]
Hey @kg!

As @leppie said, the runtime (and verifier) special cases `mscorlib.dll`, which is why you're seeing errors if your module is not exactly named `mscorlib.dll`.

When writing files, Cecil may write assemblies differently  on round-trip, but should represent the metadata in a way that is compatible with the input assembly.

Last time I checked, the result of a round-tripped `mscorlib.dll` was equivalent. I think you should be safe, the linker for instance has the ability to rewrite `mscorlib.dll` in full link mode.
