### ISSUE TITLE
Renaming TypeReference does not update attribute ctor par type

### ISSUE THREAD

**Issue by sajagi** [jbevain/cecil#630]
Hi Jb,

When you rename a TypeReference (reference to a type defined in different assembly), any constants of such type used as attribute constructor parameters are not renamed (their type is not renamed) in exported assembly. 

Example:

```csharp
// LibA
public enum Foo { A }

// LibB
public class CustomAttribute : Attribute {
    public CustomAttribute(Foo f) {}
}

[Custom(Foo.A)]
public class Cat {}

// When you rename TypeReference Foo to e.g. Bar in LibB, exported dll still uses type Foo for the attribute ctor parameter constant, resulting in type not found exception in runtime. 
```

At first glance it seems to me that the type name in blob heap is not updated properly.

**Comment by jbevain** [comment]
Yes that's a by product of how custom attributes serialize data. To avoid this issue you can pass use the Immediate ReadingMode that will deconstruct the custom attributes arguments upon reading the assembly.

**Comment by sajagi** [comment]
This only causes Cecil to throw an exception when you load the module but does not actually fix the renaming issue, am I correct? Is there a (non-reflection based) workaround for that? Thanks!

**Comment by jbevain** [comment]
What exception are you getting? Is that an obfuscated assembly?

**Comment by sajagi** [comment]
`System.TypeLoadException: Could not load type 'Xxx' from assembly 'Yyy=5.0.7263.2, Culture=neutral, PublicKeyToken=8398b1a3f55c132c'.` - this happens in runtime in the obfuscated assembly. Note that the 'Xxx' is the type name before renaming.

**Comment by jbevain** [comment]
It's an obfuscated assembly, it's possible that renaming a type is simply not going to work as the binary may contain obfuscated type data, and by changing the name you're breaking that.

I'm going to close this, the issue in deferred mode is not easily fixable, and if the workaround of using the immediate reader doesn't work because the assembly is obfuscated, there's not much I can do I'm afraid. Thanks!

**Comment by sajagi** [comment]
Alright is there a way to rename references to enum types which are used as constants in attributes? If you don't plan to fix this then it would be nice to at least throw a NotSupportedException when trying to do so.

**Comment by jbevain** [comment]
It works in the general case where you use the Immediate reader mode and the assembly is not obfuscated. As long as you're using obfuscated assemblies, there's no guarantee anything will work.

**Comment by sajagi** [comment]
Just to be sure... By obfuscated assembly I mean modified by Cecil in the way I described, not some extra 3rd party obfuscator

**Comment by jbevain** [comment]
Ah my bad! Let's re-open then.

**Comment by jbevain** [comment]
Now I finally understand. The custom attribute reader creates new instances for type references, while it looks up type definitions. So yeah, right now Cecil is not going to look up type references, you'll have to fixup the custom attributes.

**Comment by jbevain** [comment]
Closing this, it's unlikely to be fixed in the near future.
