### ISSUE TITLE
How can I get a list of class fields (recursively)?

### ISSUE THREAD

**Issue by josesimoes** [jbevain/cecil#637]
Hi,

What's the best way to get a list of all the fields in a class, including the ones from the classes it derives from?

Thanks,

**Comment by jbevain** [comment]
Hello,

There's no built-in way as this has many implications.

The easy way is to recursively walk the hierarchy of the type, and return the fields for each type.

You might need to resolve the BaseType which is a `TypeReference` into a `TypeDefinition`, which might require loading the assembly it's defined in. It's recommended that you control the assembly resolving process by providing your own assembly resolver.
