### ISSUE TITLE
SymWriter can not work on macos.

### ISSUE THREAD

**Issue by watsonsong** [jbevain/cecil#647]
I am try to use the cecil on mac but when I use the SymWriter, it can not find ole32.dll.
Is it possible to make it work on macos?
https://github.com/jbevain/cecil/blob/b632818fd4b4488956f12fe065fa8573c1982eb4/symbols/pdb/Mono.Cecil.Pdb/SymWriter.cs

**Comment by jbevain** [comment]
Hello,

Unfortunately that's not possible, we have no native PDB writer that is fully unmanaged.

We encourage everybody to switch to portable PDBs that are cross-platform.
