### ISSUE TITLE
Extra metadata tokens perservation

### ISSUE THREAD

**Issue by MxGrv** [jbevain/cecil#649]
Currently working on a protector. Faced a task to encrypt a method's body. If some reference (to a type, a method, a field) is only mentioned in the encrypted method(s), it is skipped upon assembly writing, and the modified assembly no more contains such a reference. Upon method decryption everything naturally goes awry. Is there any functionality in Mono.Cecil for perserving (or at least 'forcibly adding') the missing references? Are there any plans for such functionality in the Mono.Cecil itself or it's forks or extensions (like Rocks)?

Kinda similar issue: https://github.com/jbevain/cecil/issues/426

**Comment by jbevain** [comment]
That seems like a much broader issue than #426. There's no plan right now to track metadata across modules I'm afraid.
