### ISSUE TITLE
ModuleDefinition.FullyQualifiedName deprecated and broken since 0.10-beta1

### ISSUE THREAD

**Issue by avengerx** [jbevain/cecil#651]
In this commit 869669c574caa078e1b513c74e683fa43def1323, a change was introduced to fix something (I couldn't look up the related github issue if there were any) that will render the option unusable in cases the assembly is read off memory streams.

In other words, if the assembly is read from something like:

```csharp
var assemblyDefinition = AssemblyDefinition.ReadAssembly(
    new MemoryStream(System.IO.File.ReadAllBytes(path_to_dll)),
    new ReaderParameters()
    {
        ReadingMode = ReadingMode.Deferred,
        AssemblyResolver = myAssemblyResolver
    }
);
```

Then we would always get a `assemblyDefinition.MainModule.FileName` (or the obsolete `FullyQualifiedName`) as null, thus we won't be able to retrieve the file (for instance) even if the information would otherwise be available via `Mono.Cecil.ModuleDefinition.Image.Stream.GetFullyQualifiedName()`.

To me this was a handy option that should at least be kept for whom could rely on it. Or am I just insisting in a vicious issue I couldn't see with `Stream.GetFullyQualifiedName()`?

**Comment by jbevain** [comment]
Hello!

If you create a ModuleDefinition from a byte[], there's no way you could get a filename from it, so I'm not sure I understand the issue here?

**Comment by avengerx** [comment]
What  you say makes sense when I check the implementation of [current](https://github.com/jbevain/cecil/blob/master/Mono.Cecil/ModuleDefinition.cs#L1274-L1281) and [old GetFullyQualifiedName()](https://github.com/jbevain/cecil/blob/eff0a6985cbfbec52136e3555db6cff5441afd13/Mono.Cecil/ModuleDefinition.cs#L1142-L1153). Something else must be playing around here.

If I find further evidence how that scenario used to work I'll try to reopen this.
