### ISSUE TITLE
PortablePdb debugging symbols don't work in some cases

### ISSUE THREAD

**Issue by Irrialite** [jbevain/cecil#654]
I've been toying around with dotnet 3.1 and trying to get Cecil to work with it.
Normally everything works great with debugging set to `DebugInformationFormat.PortablePdb`, however, debugging stops working when I do any changes to Roslyn's syntax tree.

I compile the assembly with Roslyn and modify its syntax tree and add new files to the compilation, then I pass the compiled dll & pdb streams to Cecil and let Cecil write them. If I set debug information to `DebugInformationFormat.Pdb` everything still works great but that's not the case with `DebugInformationFormat.PortablePdb`. I am unable to set breakpoints anywhere in the generated dll.

After investigating, it seems that adding newly generated files to the compilation is the thing that breaks debugging. Seems like modifying the syntax tree in Roslyn is not the cause (in particular I remove properties from classes and then generate a new file with the same properties but different code and attributes). Just writing the streams directly without Cecil works fine.

**Comment by jbevain** [comment]
Thanks for reporting this. It's going to be hard to fix. If debugging still works with the Native PDBs after round-tripping the DLLs and PDBs with Cecil, it does seem to point at an issue with the Portable PDB support.

I'd need a self-contained repro to work on this though, that would be your bests chance at getting a quick fix.

**Comment by jbevain** [comment]
I'm going to close this as we don't have much to go on. If you have a repro I could look at, feel free to re-open. Thanks!
