### ISSUE TITLE
Nested types have no namespace?

### ISSUE THREAD

**Issue by jamesford42** [jbevain/cecil#655]
https://github.com/jbevain/cecil/blob/96026325ee1cb6627a3e4a32b924ab2905f02553/Mono.Cecil/Import.cs#L181-L184

Should this if/else be just an if? Nested types have a namespace too, why isn't it being assigned?

**Comment by jbevain** [comment]
Nested types in the metadata have no namespace. Their full name is the parent namespace + name + nested type's name.
