### ISSUE TITLE
SInce Visual studio 16.5 :

### ISSUE THREAD

**Issue by Maleaume** [jbevain/cecil#657]
`MSBUILD : error : Fody: An unhandled exception occurred: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Exception: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Could not load file or assembly 'Mono.Cecil, Version=0.11.0.0, Culture=neutral, PublicKeyToken=1ca091877d12ca03'. The system cannot find the file specified. [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Type: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : System.IO.FileNotFoundException [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : StackTrace: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at InnerWeaver.Execute() [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at Processor.ExecuteInOwnAssemblyLoadContext() in C:\projects\fody\Fody\Processor.cs:line 150 [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at Processor.Inner() in C:\projects\fody\Fody\Processor.cs:line 122 [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at Processor.Execute() in C:\projects\fody\Fody\Processor.cs:line 51 [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Source: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : FodyIsolated [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : TargetSite: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Void Execute() [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :  [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
`

**Comment by jbevain** [comment]
@Maleaume thanks for reaching out but there's nothing actionable for me to do on Cecil here. Please feel free to re-open if you find a Cecil issue that is self contained and easy to reproduce.
