### ISSUE TITLE
NullReferenceException accessing out of bounds gac_paths

### ISSUE THREAD

**Issue by vvuk** [jbevain/cecil#658]
https://github.com/jbevain/cecil/blob/master/Mono.Cecil/BaseAssemblyResolver.cs#L369 hardcodes "2" as the number of entries in `gac_paths`, but if you're doing something as dumb as I'm doing, in `GetGacPaths` here https://github.com/jbevain/cecil/blob/master/Mono.Cecil/BaseAssemblyResolver.cs#L291 if you're not on mono AND you don't have the `WINDIR` env var, you'll end up with an empty gac paths collection and blow up in the lookup.

**Comment by jbevain** [comment]
SHAME. SHAME. SHAME.

**Comment by vvuk** [comment]
I know you don't mean that for _me_, but if you knew what I was doing, you _would_
