### ISSUE TITLE
Probe AssemblyNameReference without actually loading it

### ISSUE THREAD

**Issue by fandrei** [jbevain/cecil#661]
I'm trying to check whether a specified assembly name/version exists and find out it's path without actually loading the AssemblyDefinition (as it takes a lot of time). It seems that BaseAssemblyResolver doesn't currently allow that, and I wonder if it's possible to tweak it to enable such functionality?

**Comment by jbevain** [comment]
Right now there's nothing built-in to that effect. At this point your best bet is to simply take the code from the resolver and tweak it manually for your use case.

**Comment by fandrei** [comment]
@jbevain this sounds like an awful solution to me. Is it absolutely impossible to do anything better?

**Comment by jbevain** [comment]
The API right now around resolving assemblies is not setup to probe. It's also not something that has been commonly requested.

Given this, it's unlikely I'm going to add to the public API something that I'll need to support just for this use case, so your best bet is to handle the probing yourself before loading assemblies with Cecil.

**Comment by fandrei** [comment]
@jbevain why not expose the list of GAC paths that BaseAssemblyResolver tries to load from, at least?
