### ISSUE TITLE
calli with [out] struct containing byvalarray fields leave fields uninitialized

### ISSUE THREAD

**Issue by jpbruyere** [jbevain/cecil#664]
Having a struct with byvalarray:
```csharp
public struct testData {
	public int x;
	public int y;
	[MarshalAs (UnmanagedType.ByValArray, SizeConst = 256)]
	public byte[] data;
	public int z;
	public int w;
}
```
Creating a DynamicMethod with indirect call to c library automatically initialize the array fields.
The c func signature is: `void getData (struct testData* pData){}`.
```csharp
DynamicMethod method = new DynamicMethod ("test", null, new Type[] { typeof (testData).MakeByRefType () });
ILGenerator gen = method.GetILGenerator ();
gen.Emit (OpCodes.Ldarg_0);
gen.Emit (OpCodes.Ldc_I8, funcPtr.ToInt64 ());
gen.Emit (OpCodes.Conv_I);
gen.EmitCalli (OpCodes.Calli, CallingConvention.StdCall, null, new Type[] { typeof (testData).MakeByRefType () });
gen.Emit (OpCodes.Ret);
```
I call the dynamic method delegate with `(out testData data)` inline declaration, and arrays are initialized.
Trying to do the same with Cecil using the `CallSite` class to make the call, arrays are Null.
Am I missing something to have arrays initialized?

**Comment by jbevain** [comment]
Hi. I don't know :)

From a first read, I don't know if that's a Cecil issue. Maybe show the code using Cecil to generate the code to see if there's something that stands out?

**Comment by jpbruyere** [comment]
its part of a dll rewriter inspired by OpenTK: (https://github.com/jpbruyere/vk.net/blob/master/vk.rewrite/Program.cs)
```csharp
static void RewriteMethod (MethodDefinition method) {
  ILProcessor il = method.Body.GetILProcessor();
  il.Body.Instructions.Clear();
  List<VariableDefinition> stringParams = new List<VariableDefinition>();
  for (int i = 0; i < method.Parameters.Count; i++)  {
    EmitLoadArgument (il, i, method.Parameters);
    TypeReference parameterType = method.Parameters[i].ParameterType;
     if (parameterType.FullName == "System.String") {
       VariableDefinition variableDef = new VariableDefinition(s_stringHandleRef);
       method.Body.Variables.Add(variableDef);
       il.Emit(OpCodes.Call, s_stringToHGlobalUtf8Ref);
       il.Emit(OpCodes.Stloc, variableDef);
       il.Emit(OpCodes.Ldloc, variableDef);
       stringParams.Add(variableDef);
    }
  }
  FieldDefinition field = method.DeclaringType.Fields.SingleOrDefault(fd => fd.Name == method.Name + "_ptr");
  if (field == null)            
    throw new InvalidOperationException("Can't find function pointer field for " + method.Name);
  il.Emit(OpCodes.Ldsfld, field);
  CallSite callSite = new CallSite(method.ReturnType) {CallingConvention = MethodCallingConvention.StdCall};
  Foreach (ParameterDefinition pd in method.Parameters) {
    if (pd.ParameterType.FullName == "System.String")
      callSite.Parameters.Add (new ParameterDefinition (pd.Name, pd.Attributes, s_stringHandleRef));
    else
      callSite.Parameters.Add (pd);
  }
  il.Emit(OpCodes.Calli, callSite);
  foreach (VariableDefinition stringVar in stringParams)  {
    il.Emit(OpCodes.Ldloc, stringVar);
    il.Emit(OpCodes.Call, s_freeHGlobalRef);
  }
  il.Emit(OpCodes.Ret);
```

EmitLoadArg is a case on arg index `il.Emit(OpCodes.Ldarg_X);`

I can't understand why ilgenerator from the Dynamic namespace is initializing the arrays and not the MSIL generated with cecil.

**Comment by jbevain** [comment]
Once the IL is generated it's very much outside of the Cecil responsibility, so I'm not sure we'll be of much help and that doesn't look like a Cecil issue

Have you run peverify on the resulting binary? Are the methods declaring the data being set to `InitLocals = true` to zero the locals that are going to be set from native?

**Comment by jpbruyere** [comment]
I'm on linux, but with localinit on/off, nothing change and also I don't use local with this [out] parameter. byvalArrays must be initialized by some piece of code in Marshaling, default ctor of such structs leave arrays to null, and trying to init them manually (with new byte[256]) destabilize the runtime. but PtrToStruct (hGlobHnd), classic PInvoke, and calli through a dynamic method initialize the arrays. My intuition is that there is a flag somewhere (assembly, module, method) that enable or not such fixed array init, but I may be completely wrong. I should handle more tests on my side, I was asking here hoping someone already know something about this problem.

**Comment by jbevain** [comment]
No clue sorry. I'm going to close this, feel free to re-open with a self-contained if you end up finding out that Cecil generates something wrong.
