### ISSUE TITLE
[Q] Is it true that StringHeap must always be present in a portable PDB metadata?

### ISSUE THREAD

**Issue by ivanpovazan** [jbevain/cecil#665]
In the following section of the code, StringHeap is treated as it will always be present in the metadata, while for Guid and Blob heaps that is not the case:

https://github.com/jbevain/cecil/blob/f74703c36e9a7626ef435399c45d27a84b246864/Mono.Cecil.PE/ImageReader.cs#L480#L486

I am working on a tool for creating portable PDB metadata (and verifying it with Cecil library), and in some cases when StringHeap is not present in the portable PDB metadata, Cecil library throws null exception at:
https://github.com/jbevain/cecil/blob/f74703c36e9a7626ef435399c45d27a84b246864/Mono.Cecil.PE/ImageReader.cs#L484 

Does StringHeap have to be present in portable PDB metadata in all cases? 
And if so, is this requirement documented anywhere?

Thank you

**Comment by jbevain** [comment]
No that's a bug :)

**Comment by ivanpovazan** [comment]
Alright :) thank you for the quick answer.

Shall I do the fix?

**Comment by jbevain** [comment]
@ivanpovazan that would be great! Thank you!

**Comment by ivanpovazan** [comment]
You're welcome :)
It is a pleasure to read/work with the code that is clean like this library
