### ISSUE TITLE
[Q] Is it required for PDB file always to be in the same directory with associated assembly? 

### ISSUE THREAD

**Issue by ivanpovazan** [jbevain/cecil#667]
The following section of the source code expects the PDB file to be in the same location as the associated assembly (and to have specific extension: _.pdb_):

https://github.com/jbevain/cecil/blob/ce1ae875d32a4d303afbdfbf1564fe2da4d12b84/Mono.Cecil.Cil/Symbols.cs#L870#L872

Shouldn't the PDB path come from debug header entry or there is another reason for this assumption?

Any clarification is appreciated. Thanks in advance.

**Comment by jbevain** [comment]
The pdb path only makes sense when you're actually debugging something that you compiled on your computer.

More often than not, Cecil will read DLL+PDBs that have been compiled elsewhere, and the pdb path burned into the header doesn't make a whole lot of sense.

**Comment by ivanpovazan** [comment]
Makes sense. 

Thanks for your response
