### ISSUE TITLE
Processing of msvsmon.exe file failed.

### ISSUE THREAD

**Issue by sj6219** [jbevain/cecil#671]
When you execute the following statement:
`var assembly1 = AssemblyDefinition.ReadAssembly (@"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Remote Debugger\x86\msvsmon.exe");
`

Errors occur in this position.
C:\Users\sjpark\Documents\cecil\Mono.Cecil.PE\ImageReader.cs:196

`			// CLIHeader			8`
`			cli = ReadDataDirectory ();`

`			if (cli.IsZero)`
`				throw new BadImageFormatException ();`

The files are here.

[msvsmon.zip](https://github.com/jbevain/cecil/files/4693553/msvsmon.zip)

**Comment by SimonCropp** [comment]
i dont think that is a dotnet assembly

**Comment by sj6219** [comment]
I thought I could handle it even if it wasn't a dotnet file.
Anyway, thanks for your help.
