### ISSUE TITLE
Sequence points for multiline conditional operator

### ISSUE THREAD

**Issue by daveMueller** [jbevain/cecil#678]
I usually get multiple sequence points for conditional branching. E.g. for
```
1  if (result == "hello")
2     text = "Hello";
3  else
4     text = "Goodbye";
```
I get sequence points for the lines 1,2,4 and one hidden sequence point.
With a multiline conditional operator like
```
1   text = result == "hello" 
2       ? "Hello"
3       : "Goodbye"
```
I only get one sequence point for the range 1-3. Is this on purpose?

I want to instrument the lines 2-3 for multiline conditional operators.
Currently I can't find a solution on how to identify instructions in line 
2 and 3 when there is only one sequence point.

I'm thankful for any feedback.

**Comment by jbevain** [comment]
Hi @daveMueller, sorry it took a while to get to this.

Unfortunately, Cecil is simply reading the debug symbols created by compilers to create sequence points.

I guess you could still identify the branching pattern in IL to determine that you're looking at a ternary operator, but it's not an easy one. It would be interesting to check with Roslyn why they don't create multiple sequence points for ternary operators.

Not much Cecil can do here I'm afraid :)

**Comment by daveMueller** [comment]
Yes after digging through Cecil source I figured out that it's the the symbols that miss the information. Thanks for detailed clarification and confirmation.
