### ISSUE TITLE
MdbWriter doesn't write the correct MVID when using deterministic MVID

### ISSUE THREAD

**Issue by vitek-karas** [jbevain/cecil#680]
MdbWriter caches the MVID to write upon construction of the writer from the module's Mvid property. But in case of deterministic MVID the actual MVID is computed after the MdbWriter is constructed. So the symbols end up using the wrong (Typically all zeroes) MVID.

I looked at how PortablePdb does this, and the writer in this case holds on to the ModuleDefinition and reads its Mvid property only when actually writing the symbols (which is after it was populated with the right value).

**Comment by jbevain** [comment]
@vitek-karas good catch, could up send your PR upstream? Thanks!

**Comment by vitek-karas** [comment]
@jbevain ported to upstream in https://github.com/jbevain/cecil/pull/681
