### ISSUE TITLE
Fix up short branch instructions

### ISSUE THREAD

**Issue by lovettchris** [jbevain/cecil#688]
If I load an assembly, modify it by inserting some code, and write it back out it is possible to get brtrue.s and brfalse.s short branches that are now out of range.  And show up in the IL as a negative number like this:
```
IL_0066: brfalse.s IL_ffffffea
```
which creates all kind of havoc.  So it would be nice if the Mono assembly writer checked the branch was in range and automatically switched the instruction to a long branch when necessary.

**Comment by jbevain** [comment]
Hey!

While this is not done automatically, you can use the helpers in the `Mono.Cecil.Rocks` assembly and do:

```csharp
using Mono.Cecil.Rocks;

// ...

method.Body. SimplifyMacros();

// modify IL

method.Body. OptimizeMacros();
```

`SimplifyMacros` will turn all short forms like `brfalse.s` into their long form like `brfalse`, `OptimizeMacros` will do the same if possible.

**Comment by lovettchris** [comment]
Cool, that works, thanks!
