### ISSUE TITLE
NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. (Minor issue)

### ISSUE THREAD

**Issue by gdynamics** [jbevain/cecil#699]
When building and then packing a NuGet package with `nuget pack Mono.Cecil.nuspec`, you get a warning, stating:
```
WARNING: NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
```

This should be easy to fix. I will look into the best way to fix it and submit a PR which links to this.

**Comment by jbevain** [comment]
Fixed by #700.
