### ISSUE TITLE
Problem modifying a .NET Framework assembly using Mono.Cecil running on .NET Core

### ISSUE THREAD

**Issue by Zastai** [jbevain/cecil#703]
I have C# projects that target .NET Framework (net472).
It's in SDK project format, so that it can easily be built using either `msbuild` or `dotnet build` (with the latter being important because it allows for easy CI builds (the .NET Core SDKs are easy to deploy).

One of the solutions includes an MSBuild build task that uses Mono.Cecil to modify some of the built assemblies.

When building using `msbuild` this works fine, and the modified assemblies work.
However, when building using `dotnet build`, the modification itself seems to work (no errors produced), but attempting to use the modified assembly produces a load error like:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
  at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
  at System.Reflection.RuntimeAssembly.GetExportedTypes()
  ...
```

Looking at the assembly with ILSpy, there are indeed two (unresolved) references present in the modified assembly that are not present in the unmodified assembly:
- System.Diagnostics.Tools, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
- System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

Both assemblies are part of the .NET Core runtime, which should not be relevant to a .NET Framework assembly.

The ILDASM output for the unmodified assemblies in both build scenarios are identical (barring timestamps/checksums/MVID), so this seems to come from the way Mono.Cecil is run. It looks like it's pulling in references to system assemblies relevant to the executing assembly, not the assembly being modified.

I'll try to set up a minimal test case (base project + console executable using Mono.Cecil); I just wanted to report it first, in case it was already a known issue with a fix or workaround.

**Comment by jbevain** [comment]
Hi!

This is usually a symptom of using the `ImportReference` overloads that are taking System.Type and System.Reflection types. I recommend using the Cecil based overloads to avoid this.

**Comment by Zastai** [comment]
Aha, I shall have a look. If adjusting those fixes the problem, I'll close the issue; otherwise I'll attach a test case.

**Comment by Zastai** [comment]
Yes, the assembly references are indeed from ImportReference using `typeof(<dotnetframeworktype>)`. Now I'll just have to figure out how to set up `TypeReference`s for those instead.

**Comment by Zastai** [comment]
@jbevain Is there anything in Mono.Cecil to help with types from standard-reference-but-not-core-library types, and/or detecting the target runtime?

I assume I can use `md.TypeSystem.CoreLibrary` for anything that's in `mscorlib` on .NET Framework and `System.Private.CoreLib` on .NET Core.

But something like `GeneratedCodeAttribute` is in either `System` (netfmw) or `System.Diagnostics.Tools` (netcore).

Currently, it looks like I would have to hardcode those references; I can't rely on anything returned by `typeof(GeneratedCodeAttribute)` other than the name and namespace, because the assembly name for the type during the build task execution is not guaranteed to be the same that would apply for the assembly being modified.

**Comment by jbevain** [comment]
@Zastai unfortunately there's nothing really built-in. Your best bet is indeed to look at which “core assembly” the assembly you're working on is referencing.
