### ISSUE TITLE
Cecil fails to load portable pdb files for crossgen'd assemblies

### ISSUE THREAD

**Issue by eerhardt** [jbevain/cecil#704]
See https://github.com/mono/linker/issues/1620#issuecomment-726012522 for more context.

Using the following code:

```C#
				ISymbolReaderProvider _symbolReaderProvider = ...;
				AssemblyDefinition assembly = ...;

				var symbolReader = _symbolReaderProvider.GetSymbolReader (
					assembly.MainModule,
					fileName);

				assembly.MainModule.ReadSymbols (symbolReader);
```

When the `AssemblyDefinition assembly` points to a crossgen'd assembly, fails to load the symbols in a portable pdb file.

The reason it fails is because a cross gen'd assembly's Debug Directories has two entries:

```
>dumpbin /headers C:\Users\eerhardt\.nuget\packages\microsoft.netcore.app.runtime.win-x64\5.0.0-rtm.20508.7\runtimes\win-x64\lib\net5.0\System.Private.Xml.dll

Debug Directories

        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    8B4C3C7E cv           11C 00801444   800044    Format: RSDS, {2E2D2AB8-5EC5-3956-8E87-3741A2D79E30}, 1, System.Private.Xml.ni.pdb
    8B4C3C7E cv            77 00801560   800160    Format: RSDS, {62DF6790-3B25-4522-8E89-99FB491C298D}, 1, F:\git\runtime2\artifacts\obj\System.Private.Xml\net6.0-windows-Release\System.Private.Xml.pdb
    00000000 repro          0 00000000        0
```

And the 2nd entry is the portable pdb entry.

However, `ModuleDefinition.ReadSymbols` appears to only look at the first entry in the `Debug Directories` and it throws an exception when the first entry doesn't match the portable pdb's Guid. See the following code:

https://github.com/jbevain/cecil/blob/0a2f2944638c13987d8a2318bc34bd64fdac55fd/Mono.Cecil/ModuleDefinition.cs#L1060-L1064

and

https://github.com/jbevain/cecil/blob/ab5075b3a885ffd5bee5d347b79ce71aabeb32d1/Mono.Cecil.Cil/PortablePdb.cs#L68-L100

Cecil should continue iterating the list and discover the 2nd entry and match it.

**Comment by jbevain** [comment]
Good catch. Any chance you could attach a dll here that reproduces the issue?

**Comment by eerhardt** [comment]
No problem. You can use any dll that is in the [.NET Core's runtimepack for win-x64](https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.win-x64/5.0.0). I found it using System.Private.Xml, so I've attached that assembly and its corresponding  portable pdb in the following .zip:

[System.Private.Xml.zip](https://github.com/jbevain/cecil/files/5538351/System.Private.Xml.zip)
