### ISSUE TITLE
Type name in generic instance full name

### ISSUE THREAD

**Issue by josesimoes** [jbevain/cecil#715]
The current output for a generic instance produces something like this:
```csharp
TestNFApp.GenericClass`1<System.Int32>
TestNFApp.GenericClass`1<System.String>
```

The corresponding ILDASM output looks like this:
```csharp
TestNFApp.GenericClass`1<int32>
TestNFApp.GenericClass`1<string>
```

I believe the latter is based on ECMA-335 "II.23.2.16 Short form signatures" on which is stated that short forms are to be used in this case.
Nothing really terrible or that's breaking anything but it could be improved. 

Would you accept a PR with this improvement?

**Comment by jbevain** [comment]
Hi @josesimoes,

I agree it would be nice, unfortunately by now changing this would be quite a breaking change for anybody depending on string forms so I don't think I'd take a PR. Thank you for asking!

**Comment by josesimoes** [comment]
> Hi @josesimoes,
> 
> I agree it would be nice, unfortunately by now changing this would be quite a breaking change for anybody depending on string forms so I don't think I'd take a PR. Thank you for asking!

Understood... Any chance a property or setting can be exposed to configure how this behaves?
I understand that it can be a breaking change, but that shouldn't prevent the project from improving, right? 😉 
Plus this would allow a smooth transition.
