### ISSUE TITLE
will Cecil ever support writing mixed-mode assemblies?

### ISSUE THREAD

**Issue by neeraj9** [jbevain/cecil#723]
I am using Mono.Cecil to patch existing assemblies for function entry/exit traces. This is just one of the usecase but you should get a picture of what I intend to do. In general my application will support other patching use-cases but it is a good first start. I am new to the .net world and it is interesting the number of tools and functionalities it supports.
I am not sure if I understand https://github.com/jbevain/cecil/issues/390 completely and whether I can read/patch/write-back mixed-mode assemblies while adding those IL commands with Mono.Cecil. Any help / pointers will be a appreciated.

**Comment by jbevain** [comment]
Hi!

The short answer is I don't know :)

So far we never had to implement support for writing mixed-mode assemblies, but if somebody want to sponsor developing that we can look into it.
