### ISSUE TITLE
Mismatch in branch locations

### ISSUE THREAD

**Issue by kornelijepetak** [jbevain/cecil#724]
### Background
I'm trying to inject some code into some methods.

Basic processing code is as follows:
```cs
private void processMethod(MethodDefinition method)
{
    method.Body.SimplifyMacros();
    
    // Injection code here:
    
    // somewhere here, this happens:
    il.InsertBefore(insertionPoint, Instruction.Create(OpCodes.Brtrue, nextBlockInstruction));

    // ...

    method.Body.OptimizeMacros();

    File.WriteAllText(file, method.Debug());  // instruction set output to some file.
}
```

`Debug` extension method is defines as follows: 

```cs
public static string Debug(this MethodDefinition method)
    => string.Join("\r\n", method.Body.Instructions.Select(x => x.ToString()));
```

### The issue

After I execute the code (in Release mode) via Fody add-in, the debug file (output as the last step of the above method) contains a different branch address than what I can see when I open the actual DLL in a dotPeek/ILSpy. 

🖼 **`LEFT:`** Debug output, **`RIGHT:`** Actual DLL IL.

![image](https://user-images.githubusercontent.com/7033216/109921611-6c716a00-7cbc-11eb-9566-cb9a65aa025e.png)

As can be seen from the picture, the branch addresses don't match. The desired address is what it says in the Debug output: `IL_0031`, and is what was correctly set up in the code. Note also that the address the DLL version tries to jump to is `IL_005C`, which corresponds to the same address for another jump further down. That one down there is correct, but the jump marked in diff is not.

Why does this change occur and what can be done about it?

When run, the program also crashes with:
```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at TestProject.Program.function(String a, Object b, Int32 c, Int32 d, List`1 e)
   at TestProject.Program.Main() in 
```

**Comment by jbevain** [comment]
Hi,

Sorry I didn't get to this sooner. Unfortunately it's hard to know what's going wrong exactly here.

You seem to be properly expanding all short forms before instrumentation and then optimizing them back, I'm afraid you're going to have to debug this.

I'm going to close this, feel free to re-open this if you can find a repro that we can turn into a bug.

Thanks!
