### ISSUE TITLE
Mono.Cecil does not set the HasFieldRVA field on a FieldDefinition when the InitialData property is set to non-null

### ISSUE THREAD

**Issue by jkoritzinsky** [jbevain/cecil#728]
I'm trying to use the `FieldDefinition.InitialData` property to emit a static array into an image using the `.data` declaration feature in ECMA-335.

However, it seems that any data assigned to this field is dropped and not emitted as a `.data` declaration in the image.

I know that Mono.Cecil supports round-tripping the `InitialData` field from a loaded assembly back to disk if it hasn't been modified, but it seems that modifying it or assigning it on a new field is unsupported.

**Comment by jbevain** [comment]
Hi @jkoritzinsky,

Thank you for filing this. That definitely sounds like a bug, which might be annoying because from a quick look that should not happen:

https://github.com/jbevain/cecil/blob/master/Mono.Cecil/FieldDefinition.cs#L114
https://github.com/jbevain/cecil/blob/master/Mono.Cecil/AssemblyWriter.cs#L1595

Any chance you could start a PR with a failing test?

**Comment by jkoritzinsky** [comment]
I'll work on putting together a failing unit test for this.

**Comment by jkoritzinsky** [comment]
While putting together a unit test, I found the issue.

When a new field is created in Mono.Cecil and an array is assigned to the `InitialValue` field, Mono.Cecil correctly emits the value and will read it back in. However, Mono.Cecil does not set the `HasFieldRVA` flag, so other tools like ILDasm and ILSpy do not correctly recognize that an RVA has been assigned.

When I manually set the `HasFieldRVA` flag, the other tools recognize the RVA. So thankfully I have a workaround.

It would be nice if the `FieldDefinition` class would add that flag when the `InitialData` property is set. I'll update the issue title.

**Comment by jbevain** [comment]
Ah! That makes sense. Yes we should do that, should be has simple as:

```
		public byte [] InitialValue {
			// get
			set {
				initial_value = value;
				rva = 0;
				HasFieldRVA = !value.IsNullOrEmpty();
			}
		}
```

@jkoritzinsky want to send a PR with the test & the fix?

**Comment by jkoritzinsky** [comment]
Yes, I'll send a PR with a targeted test and fix.
