### ISSUE TITLE
Script won't update after first successful weaving with Mono.Cecil

### ISSUE THREAD

**Issue by Catchawink** [jbevain/cecil#738]
This may not be an issue with Mono.Cecil, but I'm using it to modify assemblies post compilation within Unity (I'm using [this ](https://github.com/ByronMayne/Weaver)implementation of Mono.Cecil). For some reason, if I add a field to a type in an assembly, and the type of the field is a delegate type that I've defined, scripts in the assembly don't appear to update after the first successful modification/weaving.

The following code runs correctly every time I recompile, but if I attempt to replace PropertyChangedEventHandler with a custom delegate type, the assembly compiles and weaves correctly only once, then refuses to compile/update with newer script changes. It only works again if I restart Unity. I'm not receiving any error messages:

```
var handlerReference = typeDefinition.Module.ImportReference(typeof(System.ComponentModel.PropertyChangedEventHandler));
 
var fieldDef = new FieldDefinition(nameof(INotifyMethodCalled.MethodCalled), FieldAttributes.Private | FieldAttributes.NotSerialized, handlerReference);

typeDefinition.Fields.Add(fieldDef);
```
Any help would be greatly appreciated.

**Comment by jbevain** [comment]
Hi,

Unfortunately and as you suspected, this looks a lot more related to the interactions between the weaver you're using and Unity.

I'm not sure I can help, sorry!

**Comment by Catchawink** [comment]
No worries! Thank you for the feedback!
