### ISSUE TITLE
Setting Corflags appears to behave differently on Mono and .Net

### ISSUE THREAD

**Issue by leezer3** [jbevain/cecil#753]
So, I've tried investigating this and have confused myself.
I'm using Mono.Cecil to create an x32 bit copy of an AnyCpu exectuable.

The salient code is this:
```
ModuleDefinition modDef = ModuleDefinition.ReadModule(fileToProcess);
if (modDef == null)
{
	Console.WriteLine("An unexpected error occured whilst attempting to apply Corflags to executable " + fileToProcess);
	return;
}
modDef.Attributes |= ModuleAttributes.Required32Bit;
try
{
	modDef.Write(finalFileName);
}
catch
{
	Console.WriteLine("Failed to write 32-bit executable to " + finalFileName);
	throw;
}
```

https://github.com/leezer3/OpenBVE/blob/master/source/DevTools/LBAHeader/Program.cs#L68

I'm seeing the following results, depending on execution runtime of the tool:

|   |  Windows (tool execution), latest .Net  | Linux (tool execution), Mono 6.12  |
|---|---|---|
| Windows  | Program runs as 32-bit  | Program runs as 32-bit  |
| Linux  | Program runs as 32-bit  | Program runs as 64-bit  |
| Apple | Program runs as 32-bit | Program runs as 32-bit |

There's a binary difference between the .Net and the Mono modified copies, but further than that I'm heading out my depth.....
I haven't yet tried running the tool under Mono / Windows, but I can do so if you're interested.

**Comment by jbevain** [comment]
Hi,

This looks unrelated to Cecil which is probably setting the value correctly. Maybe Mono on Linux doesn't honor the 32bit preferred flag for some reason?

**Comment by leezer3** [comment]
Not sure :)
What's throwing me is that the a copy of the executable (compiled under Mono) and then modified on a Win32 machine with the Mono compiled tool works as x32 on Linux.
This suggests to me that there's something (optional?) in the PE header not quite right.

I'll open a Mono issue too and see if they've got any ideas.

Worst case scenario I can probably change my CI so the upload worker is Windows.
