### ISSUE TITLE
A few changes to stabilize output binaries proposal

### ISSUE THREAD

**Issue by ghost** [jbevain/cecil#76]
I want to propose a few minor changes to allow user to control all assembly properties such as build date/time, debug sources guids, etc...
1. Allow to control PE build timestamp through exposing _time_stamp_ property of the _ImageWriter_. For instance, it can be an optional (nullable) property of the _ModuleDefinition_ - and _UtcNow_ can be used only as fallback in case if a user hasn't provided a value. Also it could be useful to read this value from an original assembly, but it's optional though.
2. Modify MDB provider code so user could control all _SourceFileEntry_ guids or generate them in a stable way - for instance from the source code and source file name (not full path) MD5 check summs.
3. I'm not sure if PDB provider has similar problems, but if it has, they could be solved similarly.

That changes allow to create a tool that can cleanup all compilation dependent data, so developers can create stable binaries that depend only on compiler settings and source code, but not compilation date or some random numbers.

Thanks in advance!

**Comment by rolfbjarne** [comment]
This is becoming more important now that compilers support deterministic output (see csc's `/deterministic` command-line parameter).

Cecil is currently not able to round-trip such assemblies, since a new timestamp will be created.

**Comment by jbevain** [comment]
Timestamp preserving is in #333.

**Comment by jbevain** [comment]
We now support deterministic generation of dlls and portable pdbs, so I'll be closing this. Thanks!
