### ISSUE TITLE
Assemply.Write damage my dll

### ISSUE THREAD

**Issue by HPXCoder** [jbevain/cecil#830]
hi, iam working on a program that edit a dll but 
i tried to only read and write the dll but its changing the size 
examble in this pics

the code :
![sse](https://user-images.githubusercontent.com/31288493/152700839-5c0800e6-e25e-4cf0-aae1-651ff4b21a6f.PNG)

the input dll size and the output dll size changed in this pic 
![aa](https://user-images.githubusercontent.com/31288493/152700907-5799da4e-4d16-4378-b0ee-b2c74df9d870.PNG)
dll1 is the input dll
new2 is the output

after write, the dll is no working

**Comment by ThumbGen** [comment]
I get the same, attempting to patch a regular .Net 4.8 WPF executable. Writing a .NET 5/6 executable crashes.

**Comment by jbevain** [comment]
Without any form of repro or actionable information I can't do much to help.

**Comment by ThumbGen** [comment]
Sorry, I forgot to come back: I found the root of my problem: I was trying to 'touch' a .NET 4.8 executable by running the Cecil code in a .NET6 command line tool. After migrating the tool from .NET6 back to .NET 4.8, everything works perfectly.
