### ISSUE TITLE
Add support for newer runtimes

### ISSUE THREAD

**Issue by deeprobin** [jbevain/cecil#835]
```diff
	public enum TargetRuntime {
		Net_1_0,
		Net_1_1,
		Net_2_0,
		Net_4_0,
+             NetStandard2_0,
+             NetStandard2_1,
+             NetCore1_0,
+             NetCore1_1,
+             NetCore2_0,
+             NetCore2_1,
+             NetCore2_2,
+             NetCore3_0,
+             NetCore3_1,
+             Net5,
+             Net6,
+             Net7,
	}
```

**Comment by teo-tsirpanis** [comment]
Hello @deeprobin, the `TargetRuntime` enum does not signify the assembly's target frameowrk; this is actually stored in a [`System.Runtime.Versioning.TargetFrameworkAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.targetframeworkattribute). The enum is a compatibility vestige that should simply be set to `Net_4_0` for .NET Framework 4.0 and all frameworks after it.
