### ISSUE TITLE
Embedded PDBs not readable by VisualStudio

### ISSUE THREAD

**Issue by tom-englert** [jbevain/cecil#856]
With the latest changes 79b43e8 in `PortablePdb.cs` assemblies modified with cecil can no longer be debugged in VisualStudio when embedded pdbs are used. 

See https://github.com/Fody/Fody/issues/1110 for details how to reproduce.

**Comment by jbevain** [comment]
:(

Thanks for the heads-up!

**Comment by tom-englert** [comment]
I've created some test project without Fody, so this can be instantly checked within the cecil solution:
https://github.com/tom-englert/cecil/tree/%23856
![devenv_5EXsg5IJEt](https://user-images.githubusercontent.com/10229954/173795708-4e15d03e-4e35-4669-93c6-dbbae4e7e4f6.gif)
Just put a breakpoint on the unit test in the Testtee project and try to debug the test.

I've also reverted the changes to the PdbWriter to verify that this is the root cause:
https://github.com/tom-englert/cecil/tree/%23856_Fix
