### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by deliciouslytyped** [jbevain/cecil#865]
Instead of going into a long tirade about the lack of documentation for a long running project, and how it make uptake much harder for quick one-off projects,

\- as an alternative way to help knowledge transfer, would you be willing to have some sort of online community for more instant messaging style discussions? Say an IRC or Matrix room?

**Comment by ltrzesniewski** [comment]
You basically need to read [ECMA-335](https://www.ecma-international.org/wp-content/uploads/ECMA-335_6th_edition_june_2012.pdf) to be proficient with Cecil. There's no going around it. That's the real doc. 🙂 

The [wiki](https://github.com/jbevain/cecil/wiki) explains the Cecil-specific stuff, but yeah, I agree the learning curve is kinda steep.

I can also suggest [Fody](https://github.com/Fody) and its addins as a good repository of examples.

**Comment by deliciouslytyped** [comment]
@ltrzesniewski 
Can I contact you privately? If my abilities are up to it I'd like to turn this into a FOSS tool and write some public docs.

**Comment by ltrzesniewski** [comment]
I think you mean to contact @jbevain, he's the owner of this project.

**Comment by deliciouslytyped** [comment]
No I meant you, as the person who answered the thread with helpful information.

**Comment by deliciouslytyped** [comment]
I unilaterally and unofficially propose the #mono.cecil channel on the LiberaChat IRC network. I will now be idling there.
