### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Alex-Dobrynin** [jbevain/cecil#884]
I get this exception, when trying to build .netstandard 2.1 c# 9 code 
![image](https://user-images.githubusercontent.com/23138430/200048463-4b466429-7176-4acf-9b9f-b0d9fef00ce5.png)

BUT there is one nuance. this happens when I have a lot of methods in class or its subclasses, even if I override base class virtual method it can happen. when I remove many of them, the project can be build
When I say a lot I mean ~20 together with base class methods and overrides

this happens only in debug configuration

UPD
if I check this in project settings, project can be build
![image](https://user-images.githubusercontent.com/23138430/200050253-e5968ffe-6076-489e-8bcb-5d4de26e826e.png)

**Comment by jbevain** [comment]
Hi,

Thanks for filing this. Unfortunately there's not much I can do without a repro here. Could you attach or send privately the assembly that is read with Cecil in the `XamlCTask`?
