### ISSUE TITLE
Release a new version supporting RVA field alignment

### ISSUE THREAD

**Issue by sbomer** [jbevain/cecil#896]
There are many bugs which have been fixed since the last release. Notably, https://github.com/jbevain/cecil/pull/817 and https://github.com/jbevain/cecil/pull/888 are required to support reading/writing assemblies that use the `CreateSpan` helpers introduced in .NET 7. There is also support for other new language features, such as support for generic attributes (https://github.com/jbevain/cecil/pull/871), and significant fixes like determinism hardening (https://github.com/jbevain/cecil/pull/810).

See https://github.com/dotnet/runtime/issues/81835 for context, where code that is instrumented for code coverage using an old cecil crashes due to alignment issues related to `CreateSpan`.

@jbevain would it be possible to release a new version soon?

**Comment by jbevain** [comment]
Done, thanks again the contributions!
