### ISSUE TITLE
pdb roundtrip loses information

### ISSUE THREAD

**Issue by jbevain** [jbevain/cecil#90]

**Comment by jbevain** [comment]
There's a few issues at hand here. Round-tripping pdb files makes it so that we're losing some of the «custom metadata» of the pdb.

The plan to fix that I'm working on is as follows:

https://groups.google.com/forum/#!topic/mono-cecil/VSGWjgwDC7Y

I'm slowly putting more and more work into Cecil after an intense period of professional activity.

If a company using Cecil wants to speed things up, they can sponsor the work.

**Comment by user1568891** [comment]
Any progress on this? I've always wondered why the watch and immediate window never worked properly on my project that uses Fody. Finally found the answer on [StackOverflow] (http://stackoverflow.com/a/9494198/1568891) that sent me here.

**Comment by drauch** [comment]
Had to learn it the hard way also: https://stackoverflow.com/questions/34267811/vs2015-linq-in-debugger-watch-window

Would be nice if there is any follow-up on this :+1:

**Comment by xen2** [comment]
FYI, started to work on it again yesterday.
Promising results so far, hopefully a patch within a few days.
@jbevain, can you confirm that you didn't work on it yet so as to not overlap? (according to https://groups.google.com/d/topic/mono-cecil/VSGWjgwDC7Y/discussion)

**Comment by user1568891** [comment]
Thanks!

**Comment by drauch** [comment]
@xen2: Thank you for your time! :+1: Please let us know if we can help, e.g. testing, ...

**Comment by xen2** [comment]
@drauch If interested, you can cherry-pick 214b1a69a2d87d8cf64edca0d214f7816395de24 (early testing version, still various things to improve/cleanup/fix).

**Comment by xen2** [comment]
Quick update, 455f850 should be very close to final.

Only thing I wasn't really sure of, is why I need to sometime use offset and sometimes offset + 1 for my iterator scope end, but it seems to work as is.

The cool thing is I didn't do only the async locals but I also added support for many other PDB info:
- Using clauses (before `typeof(Console)` was broken in VS Watch window even when `using System` was in your file)
- Stepping over await code works (it will wait for the await call to be finished and go to next line instead of stepping out)

**Comment by davidroth** [comment]
@xen2 Cool! Thx for the fix! 
I have just quick tested it with Fody and works very well so far!
Very nice to have full debugging support back :)

@SimonCropp Would be cool if you could upgrade fody with this patched lib once it is tested.

**Comment by SimonCropp** [comment]
@davidroth yep timezone pending it will take me a couple of hours to apply and regression test. Just tell me when to start workiing on it.

**Comment by davidroth** [comment]
@SimonCropp No problems found so far, everything is working fine :+1:

**Comment by SimonCropp** [comment]
@jbevain have u had a chance to review this?

**Comment by jbevain** [comment]
@SimonCropp, I haven't yet. Have you run your test suite on it?

**Comment by SimonCropp** [comment]
@jbevain currently travelling. will get to it withing the week

**Comment by user1568891** [comment]
Any update on this? Really looking forward to this fix.

**Comment by SimonCropp** [comment]
@jbevain  i can confirm this passes all my smoke tests https://github.com/xen2/cecil/tree/pdb_roundtrip

really sorry for the delayed reply

**Comment by SimonCropp** [comment]
@jbevain is there anything else you need from me on this one?

**Comment by user1568891** [comment]
Is there anything I can do to help with this? 

In the mean time, can anyone post instructions for putting together the pieces to get full debugging support working again at least on my own project? I tried compiling xen2's fork, cloning Fody, building Fody with my local Cecil dll's, then referencing that in my project instead of the current Fody dlls, but I must have missed something as I didn't notice any changes.

**Comment by xen2** [comment]
Update: I added PDB scope info to #273
This allows locals to be scoped (and have proper mouse override behavior in case you have multiple variable with same name in different scopes)

**Comment by JustinBarker** [comment]
Any updates on this?
My company uses Fody.PropertyChanged and these issues are causing all kinds of heartburn.
@SimonCropp When will this be put into Fody.PropertyChanged? Are we waiting for @jbevain still?

**Comment by jbevain** [comment]
On the Cecil side of things we have complete roundtrip for portable pdb in Cecil 0.10-beta1, which is the recommended workaround.

**Comment by xen2** [comment]
FYI, I am reimplementing native PDB roundtrip on top of new API.

**Comment by xen2** [comment]
First version:
https://github.com/jbevain/cecil/pull/351

**Comment by jbevain** [comment]
And now we can close this dinosaur of a bug. Thanks @xen!
