### ISSUE TITLE
Specified method is not supported.

### ISSUE THREAD

**Issue by phani123hh** [jbevain/cecil#900]
I'm using ILRepack.MSBuild.Task 2.0.13 on .NET 7.0.202 with target netstandard2.0.
I don't get the error when I build inside Visual Studio.
I'm getting the following error when I run dotnet build on the command line:

![image](https://user-images.githubusercontent.com/80333615/227466473-630c9556-6068-4740-b4f5-ee36ce94a8c4.png)

Quick solution will be appreciated.

**Comment by SimonCropp** [comment]
you should raise that in the ilrepack project
