### ISSUE TITLE
Remove link in the about section in this repo

### ISSUE THREAD

**Issue by augustoproiete** [jbevain/cecil#919]
The link goes to a gambling/betting website, as pointed out by @rakosi2 via https://github.com/jbevain/cecil/issues/910#issuecomment-1629878505

<img width="669" alt="image" src="https://github.com/jbevain/cecil/assets/177608/e4d508f3-eacf-4770-9061-bd13a7a142e7">

**Comment by jbevain** [comment]
Thanks!
