### ISSUE TITLE
Stream based module reading 

### ISSUE THREAD

**Issue by mhutch** [jbevain/cecil#94]
Currently Cecil loads entire assemblies into memory, instead of using mmap or reading from the filestream as needed. This is a big problem when reading assemblies with large embedded resources. Cecil has an API for accessing a resource stream, but it's simply a MemoryStream over the buffer.

Ideally, it would also be possible to provide a stream when adding embedded resources to existing assemblies, and have these streamed into the file when writing it.

**Comment by jbevain** [comment]
Merged in master.
